### ISSUE TITLE
Remove unnecessary scrollbar from table component

### ISSUE THREAD

**Issue by Harshit-frontend** [bigbinary/neeto-ui#1007]
<img width="1440" alt="Screenshot 1943-12-30 at 4 09 02 PM" src="https://user-images.githubusercontent.com/83356733/159245265-8fc869a4-1ffe-4d98-836b-f6a5435840b7.png">

**Comment by amaldinesh7** [comment]
<img width="1440" alt="Screenshot 2022-04-11 at 1 41 26 PM" src="https://user-images.githubusercontent.com/33386004/162693323-099bedd5-28da-4c6f-9819-ff3840055eb6.png">

I think this scrollbar popup when mouse is connected.

**Comment by amaldinesh7** [comment]
@vysakh-m _a Can you please take a look at this issue?
