### ISSUE TITLE
[Syncing] form/FormFileSelector

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#101]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormFileSelector.jsx

Looks like a good candidate for syncing. Let me know if there needs to be any sorta modification required on this. Looks to me as if full file sync with helpers would do.

Let me know your thoughts on this before I start with it.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
We are not using this component anywhere right ? We don't need to sync it now.
