### ISSUE TITLE
[Syncing] form/FormField

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#102]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormField.jsx

Looks like legacy code that is not required.

But it's being referenced by several form components. Other than that I don't see it being used anywhere else.

Let me how we should deal with this.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
