### ISSUE TITLE
Increase the contrast of the success message

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#1020]
https://monosnap.com/file/6OOhKVCakJEuZDfTFpqWWx8PHbOL4A

Ref Thsi has slightly more contrast and it looks better. https://monosnap.com/file/2sTt1V1sQ7NU8E9P03TN3dQvzaVHFB

Also putting a green tick mark at the beginning kind of conveys the message that it's all good. 

@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
![Uploading Screenshot 2022-03-29 at 11.01.45 AM.png…]()
