### ISSUE TITLE
Enhancements in the storybook documentation for Table component

### ISSUE THREAD

**Issue by mohit-s96** [bigbinary/neeto-ui#1036]
Original comment: https://github.com/mohit-s96/wheel/pull/12#issuecomment-1085581353

- Clicking the `show code` on the [storybook](https://neetoui.netlify.app/?path=/docs/components-table--table) for the table component lists the entries for all the 200+ items in the table. It makes following the code a bit difficult and lags the browser sometimes. This could be limited to only a couple of entries.
- The documentation for the `render` property of the table columnData could be updated to specify the arguments it is called with (i.e. `key` property of the columnData object).

**Comment by karthiknmenon** [comment]
@mohit-s96 _a You can take this up. 

cc: @amaldinesh7 

documentation _t
