### ISSUE TITLE
Header search bar doesn't have clear button in firefox browser

### ISSUE THREAD

**Issue by ahammednafih** [bigbinary/neeto-ui#1039]
Ref: https://github.com/bigbinary/neeto-desk-web/issues/12581

**Comment by karthiknmenon** [comment]
@nehajamwalR _a

**Comment by nehajamwalR** [comment]
@karthiknmenon @ahammednafih The clear button problem is basically the problem of the input itself with type="search" in the firefox browser. The problem can be solved either by adding additional conditions and a clear button for type="search" or by disabling the default clear button from all browsers. Please let me know if anything needs to be done about this issue.
