### ISSUE TITLE
Fix UI issue in Alert component

### ISSUE THREAD

**Issue by josephmathew900** [bigbinary/neeto-ui#1041]
![Screenshot 2022-04-05 at 6 31 40 AM](https://user-images.githubusercontent.com/26121158/161683059-4c8996cd-1ba0-4be1-a3ac-a9c2304e4d20.png)

cc // @amaldinesh7

**Comment by amaldinesh7** [comment]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@josephmathew900 Could you please provide the file link?
