### ISSUE TITLE
Icon is missing in Toastr

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#1042]
Icons are not showing up on Toastrs in neetoForm.

Ref: 
![image](https://user-images.githubusercontent.com/22348659/161686447-642d145d-92b1-4d15-94a1-47060361a7c2.png)

**Comment by amaldinesh7** [comment]
@ajmaln _a Could you please try upgrading the version of `react-toastify` package to `8.0.2`?

**Comment by ajmaln** [comment]
> @ajmaln _a Could you please try upgrading the version of `react-toastify` package to `8.0.2`?

Thank worked, closing.
