### ISSUE TITLE
[Syncing] form/FormCodeEditor

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#105]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormCodeEditor.jsx

It's just used at one single spot in the whole codebase. [Refer here](https://github.com/bigbinary/neeto-help-web/blob/37e94f406bb420ed2891c1e275449ab66eca485a/app/javascript/Admin/Components/OrganizationTheme/Template/Edit/index.jsx#L111)

I'm not sure whether this is wrapper component over ace-editor that we currently use in neeto-help. If that is not that case, then we ought to remove this and replace the references with latest component code.

I need your inputs on this.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
We can take this up after [KB Themes Revamp](https://github.com/bigbinary/neeto-help-web/pull/9048) is done.

**Comment by edwinbbu** [comment]
@yedhink _a

**Comment by edwinbbu** [comment]
@karthiknmenon _a Can you check if the issue is valid anymore.

**Comment by karthiknmenon** [comment]
@edwinbbu We are using `FormCodeEditor` only for KB Themes. I don't think we need to sync this to `neetoui`

**Comment by edwinbbu** [comment]
Closing the issue as per above comments.
