### ISSUE TITLE
[Syncing] form/FormCheckbox

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#106]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormCheckbox.jsx

This is used at many places. But reading through the code I feel we can replace this with our Checkbox component.

Let me know your thoughts.

@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
