### ISSUE TITLE
closeOnOutsideClick prop is not operational in Dropdown component

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-ui#1078]
Adding the prop `closeOnOutsideClick={false}` still closes the`Dropdown` component.

bug _t
Demo: https://vimeo.com/698233998/c44506ddaa

**Comment by amaldinesh7** [comment]
@AbhayVAshokan  closeOnOutsideClick is working fine. Please refer to the video for the explanation https://vimeo.com/698512448/b27867ea4e.
