### ISSUE TITLE
[Syncing] form/FormSelectFieldType/**/*

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#108]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormSelectFieldType/index.jsx

This is just used at [one single spot](https://github.com/bigbinary/neeto-help-web/blob/b6a87e2873bd2d11f43b7c8f2f5f2e454ef57500/app/javascript/Admin/Components/Desk/Admin/TicketFields/Form.jsx#L195
) in the whole codebase. Therefore we should replace this folder itself, in my opinion.

Let me know your thoughts.

@edwinbbu _a
cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
