### ISSUE TITLE
[Syncing] form/FormRichText/**/*

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#109]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormRichText/index.jsx

Looks like this needs to be synced. I believe this is the replacement for `form/FormCodeEditor`.

Let me know your thoughts on syncing this before I start with it.
@edwinbbu _a
cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496

**Comment by edwinbbu** [comment]
RichText in not added to neetoui. Hence reopening the issues. Need to discuss on this since RichText using trix editor and might increase load to neetoui if added. Alternative approach is keep the RichText editor in the shared Folder.

**Comment by edwinbbu** [comment]
@yedhink _a

**Comment by edwinbbu** [comment]
Closing the issue since the RichText is being added as a separate package 
Ref https://github.com/bigbinary/neeto-editor
