### ISSUE TITLE
Fix Issue with Table header

### ISSUE THREAD

**Issue by PrateekArora03** [bigbinary/neeto-ui#1095]
While working on Neeto-Area51 [ #24](https://github.com/bigbinary/neeto-area51/issues/24), Found out that the Column header is broken when column data and width are not present.

With the `neeto-ui` Table component

![image](https://user-images.githubusercontent.com/25227096/163563769-8e23ecaa-ef07-46aa-a64d-9b18e4712156.png)

With `antd` Table component

![image](https://user-images.githubusercontent.com/25227096/163563629-c63400f7-59d7-478a-b75a-fe7abb5d2d9c.png)

**Comment by PrateekArora03** [comment]
@ajmaln _a, As per our discussion on call created a ticket for the issue. Please take a look.

**Comment by amaldinesh7** [comment]
@PrateekArora03 Providing a width to the column should fix this issue. If this is a dynamic column provide an approx width if you cannot decide the width for them.
