### ISSUE TITLE
[Syncing] form/DropDown/DynamicDropDown/**/*

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#110]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/DropDown/DynamicDropDown/index.jsx

Since this is just used at [one single spot](https://github.com/bigbinary/neeto-help-web/blob/78c67a4ba8898db84a1d02f982057cabdeb54f7b/app/javascript/Admin/Components/Insights/User/NewMessageDropDown.jsx#L34) within the codebase, I think we can replace this.

Let me know your thoughts on this.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
