### ISSUE TITLE
[Syncing] form/CustomSelectComponents/DropdownIndicator

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#111]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/CustomSelectComponents/DropdownIndicator.js

This is used within several form and one outside component. But I believe we can replace this.

Let me know your thoughts.

@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
