### ISSUE TITLE
Select with isCreatable does not support searching

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto-ui#1111]
Refer: https://github.com/bigbinary/neeto-kb-web/issues/1340

<img width="468" alt="image" src="https://user-images.githubusercontent.com/9862943/164776440-0a7a392a-5e88-4cad-a8d5-d8d26d31dd59.png">

In the above screenshot, there is one available option with label `JavaScript`.

**Comment by karthiknmenon** [comment]
@mohit-s96 _a Could you please debug and verify?
