### ISSUE TITLE
[Syncing] form/CustomSelectComponents/ClearIndicator

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#112]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/CustomSelectComponents/ClearIndicator.js

Unused. Will migrate.

@yedhink _a

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
