### ISSUE TITLE
Final sync before version update

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#114]
Some changes needs to be synced from NitroUI components excluding `form`.

This requires some manual work and time, since I have to go through the latest diffs once again.

@yedhink _a

**Comment by goutham-subramanyam** [comment]
@yedhink Please make sure the following things:

1. No component should have `dataTestId` prop. In the Demo Page (`index.js`) update all `dataTestId="blah-blah"` to `data-test-id="blah-blah-blah"`
2. All components with label should use our `Label` component internally.
