### ISSUE TITLE
Date Range Picker clear icon is not fully hiding the calendar icon

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#1160]
Ref: https://github.com/bigbinary/neeto-form-web/issues/3139

Video: https://vimeo.com/715855425/2ee690350b

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/22348659/172149229-f2dff647-70d7-4a1f-ac3b-4cd4e839272f.png">

**Comment by amaldinesh7** [comment]
@karthiknmenon _a

**Comment by ajmaln** [comment]
@ajmaln _a
