### ISSUE TITLE
Option to set a default sortBy value in Table component

### ISSUE THREAD

**Issue by shreyansh-g24** [bigbinary/neeto-ui#1171]
Current Status:
 - We can sort the rows in the `Table` component by any column in `asc OR desc` orders.
 - This action updates the UI of the column header by highlighting the arrow in the column.
 - If the host application is sorting by some column as a default, initially the `Table` doesn't highlight any arrow in the column header.
---
Suggestion:
 - If the table accepts a `defaultSortBy` option, it can be used to update the UI as per the default sort options being used in the host application.

The highlighted arrow:
<img width="856" alt="Screenshot 2022-06-13 at 11 57 40 AM" src="https://user-images.githubusercontent.com/40631571/173292683-4d57057c-172e-4edd-ba54-f0c9db97437a.png">

**Comment by amaldinesh7** [comment]
@shreyansh-g24 _a Could you please check this documentation and try it out - https://ant.design/components/table/#components-table-demo-head.

**Comment by shreyansh-g24** [comment]
Closing this as the `defaultSortOrder` is already present time the ant design documentation.
