### ISSUE TITLE
Checkbox in table cut off in lower screen resolutions

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/neeto-ui#1174]
Video walkthrough by @sachingiri29 : https://vimeo.com/718943350/27077471d8

This issue is present when the screen resolution seems to squeeze the components tight together in a single flex row,
and the padding of the neighbouring element to the checkbox seems to cut of the checkbox by a bit.

@amaldinesh7 _a

**Comment by amaldinesh7** [comment]
@vysakh-m _a

**Comment by amaldinesh7** [comment]
@vysakh-m _a
