### ISSUE TITLE
Add file upload component

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#1189]
@amaldinesh7 _A

**Comment by AbhayVAshokan** [comment]
![image](https://user-images.githubusercontent.com/35297280/176617262-159bb756-9bae-4e1d-b840-dc36565d76d3.png)
Ref: https://github.com/bigbinary/neeto-team-members/blob/master/src/components/Invitations/Csv/Uploader.jsx

@amaldinesh7 Here is an implementation of the file uploader for the invitations feature in the `neeto-team-members` repository. Showing upload instructions is necessary. While working on this feature, please do consider this requirement as well.

cc: @Thejus-Paul
