### ISSUE TITLE
Allow breadcrumb to be passed as child in header

### ISSUE THREAD

**Issue by mayanksharma4132** [bigbinary/neeto-ui#1190]
https://vimeo.com/725175785
cc: @akhil-gautam

**Comment by akhil-gautam** [comment]
It can be an independent component similar to https://mui.com/material-ui/react-breadcrumbs/#main-content. 

Currently, packages(neeto_tags_frontend) are throwing runtime errors when we pass `breadcrumbs` as a `prop` to the `Header`. As of now, we have no way to pass any `children` to the `Header` component. If we just allow `Header` to accept `children`, the implementation will become straightforward.

**Comment by akhil-gautam** [comment]
@amaldinesh7 _A Need your thoughts regarding the feasibility.

**Comment by akhil-gautam** [comment]
Closing this based on the reason Amal said in a call. Also, I fixed the issue with neeto-tags so this is no more needed.
