### ISSUE TITLE
Revert changes to layouts and update version to 0.7.5

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#120]
Build failed due to recent changes in layouts. Hence reverting layouts part.

<img width="1221" alt="Screenshot 2020-12-23 at 9 53 36 AM" src="https://user-images.githubusercontent.com/17916573/102959177-d7f0cb80-4504-11eb-8373-43a3e30f22d6.png">

@edwinbbu _a

cc @yedhink

**Comment by yedhink** [comment]
We have to have the latest build in neeto-help before the migration can be done. Otherwise it breaks stuff in neeto-help.

I will prioritise layout syncing.

**Comment by yedhink** [comment]
@edwinbbu 

I think this can be closed now.

**Comment by edwinbbu** [comment]
Fixed via PR #121
