### ISSUE TITLE
Update regarding neeto UI Kit v2

### ISSUE THREAD

**Issue by vysaghsekharbb** [bigbinary/neeto-ui#1221]
Hi @neerajdotname, 

I just finished migrating from neeto UI v1 to v2.. Please watch the video below and let me know your thoughts.

https://app.usebubbles.com/QtbdFmqKbYagRaTNA53Tz/neeto-ui-kit-v2-updates

Visual Designs
https://www.figma.com/file/9rPsUXEWN7GA3MNuwd66xC/neetoChat?node-id=7766%3A16782

Design System
https://www.figma.com/files/project/37650822/Design-System?fuid=1090206624484504509

cc @karthiknmenon 

Thank You.

**Comment by neerajdotname** [comment]
@vysaghsekharbb https://www.loom.com/share/5f65dc9da15f4e4fb3e28941ad575552

**Comment by vysaghsekharbb** [comment]
Thank You! I will work on the app switcher.

**Comment by karthiknmenon** [comment]
cc: @praveen-murali-ind
