### ISSUE TITLE
Extract Columns Dropdown as a molecule

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto-ui#1249]
https://www.loom.com/share/b406aecd83244789878e47a72ff4d254

@AbhayVAshokan @amaldinesh7 @karthiknmenon Let me know your thoughts.

**Comment by AbhayVAshokan** [comment]
I agree. It would be very useful to be extract this into neetoUI. We do have a lot of tables. This will make it easier to control long tables.

**Comment by chiraggshah** [comment]
@amaldinesh7 @karthiknmenon : Thoughts?

**Comment by karthiknmenon** [comment]
IMO, I would prefer not to do it. We were also discussing the pros of keeping the tag molecule inside of neetoUI. 

neetoUI was developed with a mindset of providing atomic components that can be reused or combined together in products as molecules. The column dropdown is basically a Dropdown component + Checkbox and Label. IMO, we should continue to keep neetoUI as atomic components that can be reused at different places. 

Molecules should be built at a product level or a different package/engine level.

Lmk your thoughts. 

@chiraggshah @AbhayVAshokan

**Comment by amaldinesh7** [comment]
Let's try and keep the neetoUI as simple as we can, even though it's grown very big. If there are more reusable molecules like this one, tags etc, we can think of creating another package. But my personal opinion is to keep it at the project level only, as the design/functionality of these molecules can change in one or more products at any time and these kinds of extraction shouldn't make the change difficult or we'll end up handling custom requirements of different products inside the extracted out code, which will again be hard to maintain. 

@AbhayVAshokan @chiraggshah If you have different thoughts, we can discuss them.

**Comment by chiraggshah** [comment]
@karthiknmenon @amaldinesh7 @AbhayVAshokan 
I understand the purpose of neetoUI to have atomic components, but I think it would also be worthwhile to have these molecules. The reason is, that the same functionality is needed in multiple applications and at various places in the same application.
Whether we keep these molecules in neetoUI or a separate package, that we can discuss.

We need to be careful of not creating lots of molecules, but only the ones which look to be self contained and might not require a lot of maintenance. 

Also tagging in @unnitallman @neerajdotname for their thoughts.

**Comment by neerajdotname** [comment]
> Whether we keep these molecules in neetoUI or a separate package, that we can discuss.

I'll say let's use Rails's philosophy. Over there everything starts outside of Rails as a plugin. If the plugin has wide option and it is felt that the plugin should be core part of Rails then its' merged into Rails. 

We can do the same here. Let's start with this outside of neetoUI.

**Comment by chiraggshah** [comment]
Sounds good. 
@karthiknmenon is there someone this can be assigned to? Again, this is not high priority.

**Comment by neerajdotname** [comment]
@Harshit-frontend _a Can you work on this after finishing your scribble.

**Comment by Harshit-frontend** [comment]
@neerajdotname I will start looking into it after finishing the scribble.

**Comment by chiraggshah** [comment]
@karthiknmenon _a : Can we reassign this?

**Comment by karthiknmenon** [comment]
@rishadp2747 _a

**Comment by neerajdotname** [comment]
I'm in a call @rishadp2747  him and he is not sure why this issue is assigned to him. May be it was assigned to him when he had lesser number of issues. Now he has issues to work on related to payments. @karthiknmenon _a  Please assign this issue to someone who is more familiar with neetoUI.

**Comment by karthiknmenon** [comment]
@Thejus-Paul _a
