### ISSUE TITLE
Don't show the limit

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#1254]
https://www.loom.com/share/5b8085f2970a48fc95845a7fca8306e3

If this will be fixed in the newer version of neeto-ui then we can wait.

**Comment by neerajdotname** [comment]
https://monosnap.com/file/2VHrlRROpfkxWyjfjwxmk5KealWx96

**Comment by vysaghsekharbb** [comment]
@neerajdotname 

https://www.loom.com/share/c8665df4030d4e6599ae3e125c177b56

Please watch the video

**Comment by neerajdotname** [comment]
@vysaghsekharbb https://www.loom.com/share/b7df3425bf5f49bfb9361b8d3f92163f

**Comment by vysaghsekharbb** [comment]
Plesae find the updated design

https://www.loom.com/share/3b7d0bb83db04d1ea5cfae2253070394

**Comment by neerajdotname** [comment]
@vysaghsekharbb looks good. Let's implement it.

**Comment by amaldinesh7** [comment]
@amaldinesh7 _A

**Comment by amaldinesh7** [comment]
This issue will be fixed in the new release.

**Comment by amaldinesh7** [comment]
Demo of the implementation -  https://vimeo.com/742959886/e88cf945e3

@neerajdotname @karthiknmenon @praveen-murali-ind @vysaghsekharbb Please share your thoughts.

**Comment by neerajdotname** [comment]
@amaldinesh7 looks good. 👍
