### ISSUE TITLE
Adding classNames to select dropdown

### ISSUE THREAD

**Issue by sagar18041** [bigbinary/neeto-ui#128]
Ref: #125 
https://www.loom.com/share/0b812a55089a42028b7da2c19afa9958

**Comment by yedhink** [comment]
@sagar18041 

I understand your point. Currently we can override the `classNamePrefix` by just passing it as a prop for our neetoui `Select` component.
```
<Select
   classNamePrefix="whatever"
/>
```

But a problem that we will face is with the stylesheets associated with it. Example:
https://github.com/bigbinary/neeto-ui/blob/8ca70221fe46803e1aa7d1e619fca85fd7407d4d/lib/styles/components/select.scss#L12
This is hardcoded assuming that the `classNamePrefix` will always be `nui-react-select`. If we change the prefix, then this stylesheet would get nullified. Thus if we are changing classNamePrefix, then we ought apply styles dynamically.

I believe the same thing applies to `className`. `nui-react-select-container` should be there inorder for the stylesheets to get applied.

@vinay0x @edwinbbu @goutham-subramanyam What are your thoughts on this?

**Comment by vinay0x** [comment]
If it's just for the container, we can do the following:
- Add a new prop `selectContainerClassName`
- Pass it to the `classnames` method along with `nui-react-select-container` here: https://github.com/bigbinary/neeto-ui/blob/8ca70221fe46803e1aa7d1e619fca85fd7407d4d/lib/components/Select.js#L49

For further customization, the only way is to change the prefix and copy the styles from neeto-ui and make needed changes. 

@sagar18041 You can try giving this a shot: https://react-select.com/styles. I don't clearly remember which style takes precedence though.

**Comment by sagar18041** [comment]
@vinay0x 

> If it's just for the container, we can do the following:

The change isn't required only for the container and neither do I require to add any styles.

From https://react-select.com/props#statemanager-props:

- classNamePrefix : All inner components will be given a prefixed className attribute.
- className: Sets a className attribute on the outer component.

These 2 properties can be used to pass a custom(unique) class name or prefix to class names, to the component and their child-components.
And by using this class name I can uniquely identify these elements and use them to write test cases on them.

> Add a new prop selectContainerClassName

This can be done and it will work. So just needed the confirmation for this.

This entire issue is just a patchwork for https://github.com/bigbinary/neeto-ui/issues/125 issue until we fix it.
