### ISSUE TITLE
Fix overlapping issue with dropdown component while using with fixed column in the table

### ISSUE THREAD

**Issue by philson-philip** [bigbinary/neeto-ui#1294]
@praveen-murali-ind _a Please check the loom video https://www.loom.com/share/8aee1434e15d42ddb1b3aaf29ec6e153
cc: @karthiknmenon

**Comment by praveen-murali-ind** [comment]
@philson-philip We can use the prop [appendTo](https://atomiks.github.io/tippyjs/v6/all-props/#appendto) with Dropdown to fix this. We have added a Storybook doc for this in #1314.
