### ISSUE TITLE
Example of `MenuBar` in neetoUI Doc updates state naively

### ISSUE THREAD

**Issue by vishnuMohanan01** [bigbinary/neeto-ui#1315]
Example given in [NeetoUI/MenuBar](https://neetoui.onrender.com/?path=/docs/layouts-menubar--menu-bar-story) tries to update state with previous value in a wrong way. The argument passed to `setIsSearchCollapsed` could be stale.

### existing code: 

```js
iconProps={[
            {
              icon: Search,
              onClick: () => setIsSearchCollapsed(!isSearchCollapsed),
            },
          ]}
```

### should be change to:

```js
iconProps={[
            {
              icon: Search,
              onClick: () => setIsSearchCollapsed(isSearchCollapsed => !isSearchCollapsed),
            },
          ]}
```

@yedhink

**Comment by yedhink** [comment]
@vishnuMohanan01 When you raise an issue point out why the code is wrong and what's the right way to handle it. Update your first comment with the same and lemme know.

**Comment by vishnuMohanan01** [comment]
@yedhink Done.

**Comment by yedhink** [comment]
@amaldinesh7 _a Please take this up.

Refer: https://academy.bigbinary.com/learn-react/pages/know-when-to-use-previous-state-for-state-update

**Comment by amaldinesh7** [comment]
@ajmaln _a
