### ISSUE TITLE
Colors does not match with the names in docs

### ISSUE THREAD

**Issue by udai1931** [bigbinary/neeto-ui#1320]
Color mentioned and shown are not the same in the documentation.
For example :
`--neeto-ui-white` is mentioned but `--neeto-ui-white` is shown
`--neeto-ui-gray-800` is mentioned but `--neeto-ui-gray-100` is shown

`gray-800` is supposed to be the darkest color but in almost all cases the lightest color is mentioned for 800 value

Refer: https://www.figma.com/file/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=1679%3A950

Places where I found this error:
https://neetoui.onrender.com/?path=/docs/foundation-colors--page
https://neetoui.onrender.com/?path=/docs/foundation-helpers-border-color--page
https://neetoui.onrender.com/?path=/docs/foundation-helpers-color--page

cc: @yedhink

**Comment by yedhink** [comment]
@udai1931 Can you also put up a short video pointing out the main issue so that it helps the one who is fixing it? Thanks.

@praveen-murali-ind _a Can you please take a look into this? Please assign to the right person.

**Comment by udai1931** [comment]
Refer: https://app.usebubbles.com/efURJF4ht28RLRmQbB3TG3/colors-problem

**Comment by praveen-murali-ind** [comment]
@yedhink @udai1931 These changes are a part of dark mode support and they are already been mentioned in the KB articles.

https://neeto-engineering.neetokb.com/articles/color-palette-enhancements
https://neeto-engineering.neetokb.com/articles/default-dark-theme-support-experimental

Now we have dynamic color palette based on light and dark mode. The darkest gray becomes the lightest gray in dark mode.  

![Group 1](https://user-images.githubusercontent.com/48869249/191055087-d0685d73-89f4-4b8f-8240-e6faf9d04202.png)

**Comment by yedhink** [comment]
Thanks for clarifying that. @praveen-murali-ind _a Please see if the following suggestion makes sense: https://www.loom.com/share/74852c3c9d264900a6136251a412651e

**Comment by praveen-murali-ind** [comment]
> @yedhink _a



> Thanks for clarifying that. @praveen-murali-ind _a Please see if the following suggestion makes sense: https://www.loom.com/share/74852c3c9d264900a6136251a412651e
> 
> If not, then please go ahead and close this issue.

True. We should use the light theme by default. 

@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@yedhink This will be fixed in #1322

Initially the dark theme was set based on the OS color scheme preference. Now we added `current` parameter to set the light theme as default. 

Ref - https://storybook.js.org/addons/storybook-dark-mode

> Order of precedence for the initial color scheme:
> 
> If the user has previously set a color theme it's used
> The value you have configured for current parameter in your storybook
> The OS color scheme preference
