### ISSUE TITLE
Header should be below pane/modal

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#133]
We need to make this `auto`: https://github.com/bigbinary/neeto-ui/blob/99009f77f0aae39b9611e5db561c75ea35782f6f/lib/styles/layout/header.scss#L12

Problem:
![Screenshot_20210104_170701](https://user-images.githubusercontent.com/31244999/103531664-d386c400-4eaf-11eb-8ba6-7ddf97486ed6.png)

@edwinbbu I will make a fix for this by changing it into `z-index: auto`

**Comment by yedhink** [comment]
@yedhink _a

**Comment by goutham-subramanyam** [comment]
@yedhink We should be updating `<Slider/>` to our `<Pane/>` component. That will fix the issue. Changing z-index to auto will cause other issues.
