### ISSUE TITLE
Add a command to upgrade neeto-ui version to v4 in neetoui

### ISSUE THREAD

**Issue by nancy-binani** [bigbinary/neeto-ui#1332]
@yedhink

**Comment by yedhink** [comment]
@nancy-binani I think you missed adding the relevant info in the first comment. Please add and lemme know once done.

**Comment by nancy-binani** [comment]
https://www.loom.com/share/1d70115f72b041ecaa52f54f531571ee

**Comment by nancy-binani** [comment]
https://www.loom.com/share/1d70115f72b041ecaa52f54f531571ee

**Comment by karthiknmenon** [comment]
@deepakjosp _a
