### ISSUE TITLE
Add content about neetoUI classnames.

### ISSUE THREAD

**Issue by abhijithsheheer** [bigbinary/neeto-ui#1333]
I happened to see `neeto-ui-text-transform-capitalize` classname which help me to reduce the JavaScript required to do the same for the srcibble application.
I found this classname and other classnames while going through the GitHub Repo, but the same was not mentioned, or related content is not present in the current documentation.

@yedhink

**Comment by yedhink** [comment]
@praveen-murali-ind _a Can you please take this up or assign this to the right person? Thanks.

**Comment by amaldinesh7** [comment]
@sreerag-ms _a

**Comment by karthiknmenon** [comment]
@deepakjosp _a Please followup on this thread and have a call with Praveen to understand the usage of classnames better.

cc: @praveen-murali-ind
