### ISSUE TITLE
Replace `dropdownClassName` with `popupClassName` prop in DatePicker component

### ISSUE THREAD

**Issue by vijay2136** [bigbinary/neeto-ui#1334]
https://github.com/bigbinary/neeto-ui/blob/e58a6fe859646d959ce160156b3a6d7726e554cb/lib/components/DatePicker.js#L72

**Comment by vijay2136** [comment]
@amaldinesh7 _a Please take a look into this. This is a blocker issue for the cypress team.

cc: @KaranTikellu7

**Comment by vijay2136** [comment]
These changes were reverted in this PR https://github.com/bigbinary/neeto-ui/pull/1384. Is there any reason why this change was made? 

Warning after updating to the latest version:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/48003440/198731065-6a0d8443-735b-4346-a3c8-bdc5ce6fac9d.png">

**Comment by amaldinesh7** [comment]
@vijay2136 DatePicker component styles were broken when we changed to popupClassName, thus reverted the changes as a quick fix. WIll be fixing this properly.
