### ISSUE TITLE
Pay more attention to the explanation of props in docs

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#1343]
https://www.loom.com/share/9ec12911f7db4896a3ca04a4ee83747d

@praveen-murali-ind _a Please look into this and assign to the right person.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/31244999/192974409-954e5a27-fd36-4c82-ba80-43d29c7a22c6.png">

cc: @karthiknmenon

**Comment by praveen-murali-ind** [comment]
@amaldinesh7 _a Please assign this to the right person.

**Comment by amaldinesh7** [comment]
@sreerag-ms _a

**Comment by sreerag-ms** [comment]
@amaldinesh7  Please take a look. https://youtu.be/aLDpYvIHxnA

PR with the changes mentioned in the video: https://github.com/bigbinary/neeto-ui/pull/1357

cc: @karthiknmenon, @yedhink
