### ISSUE TITLE
Missing Icon support for MenuBar Item Component 

### ISSUE THREAD

**Issue by paulsojan** [bigbinary/neeto-ui#1347]
@yedhink

**Comment by amaldinesh7** [comment]
Could you please elaborate on the usecase? @paulsojan

**Comment by amaldinesh7** [comment]
@paulsojan _a

**Comment by paulsojan** [comment]
@amaldinesh7 Please check out this video. [Link](https://www.loom.com/share/6e4948f165f34f68949e04beaec7fba0)

**Comment by karthiknmenon** [comment]
This is supposed to be a custom component. Closing the issue.
