### ISSUE TITLE
Icon Button is not synced properly 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#136]
https://www.loom.com/share/f832a72461ac478b878a84f1ca9190df

**Comment by edwinbbu** [comment]
@goutham-subramanyam _a

cc @yedhink

**Comment by goutham-subramanyam** [comment]
@edwinbbu This is happening because in neeto-ui, the class for the table is `nui-table` and right now in neetohelp we are using `nh-table`. We need to update the table classes to `nui-table` everywhere.

@yedhink Please handle that when you are replacing `NitroUI` imports with `neetoui`
