### ISSUE TITLE
Check feasibility of adding an eye dropper in ColorPicker

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#1363]
It would be nice to have an eye dropper in `ColorPicker` component. We have a use case in neetoForm theming to pick a color from a background image.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22348659/195073137-3aff1b33-0e85-4a31-84ed-f1a38c19d219.png">

**Comment by karthiknmenon** [comment]
@karthiknmenon _a Will look into this.

**Comment by amaldinesh7** [comment]
@amaldinesh7 _a
