### ISSUE TITLE
Fix `validateDOMNesting` warning in DatePicker component

### ISSUE THREAD

**Issue by vijay2136** [bigbinary/neeto-ui#1364]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/48003440/195152263-046ed8d5-69b4-4504-b047-6ca07003158c.png">

**Comment by vijay2136** [comment]
@amaldinesh7 _a Can you please look into this.

**Comment by karthiknmenon** [comment]
cc: @praveen-murali-ind
