### ISSUE TITLE
Prevent icons within the `iconProps` from being the `target` of any SynctheticEvents

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#1393]
https://www.loom.com/share/8f1a09da399946de84af4672f0dac7db

@Amaljith-K _a Can you please take a look into this and see if the solution mentioned in the video needs to be added to neetoUI itself? If yes, then we can assign this to someone from the neetoUI team.

Shout out to both @Amaljith-K and @AbhayVAshokan for providing me insights into debugging this issue.

The video was created targeting our freshers as the audience and to ensure that they can understand how to debug such issues with events in React. That's why the video is pretty long.

**Comment by Amaljith-K** [comment]
@yedhink it is already added: https://github.com/bigbinary/neeto-ui/pull/1376/commits/cd3f758f391a45f5587ef9c030037549054802cf

PR: https://github.com/bigbinary/neeto-ui/pull/1376

**Comment by yedhink** [comment]
That LGTM. We can close this issue.
