### ISSUE TITLE
Improve Toastr doc

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#1404]
- [x] Let’s provide documentation for the Toastr configuration or provide a link to the React-toastify docs page
- [x] Please verify the `duration: 5000` prop and it’s usage
- [x] Verify all the props in react-toastify is working when passed as custom config.

<img width="1440" alt="Screenshot 2022-11-07 at 12 56 28 PM" src="https://user-images.githubusercontent.com/48869249/200250541-0d61bf20-4b10-4369-ae87-f67b9b49e52d.png">

@deepakjosp _a

//cc @amaldinesh7

**Comment by deepakjosp** [comment]
@praveen-murali-ind changing estimate back to 0.5D to verify the props support[3rd checklist item in the description].

**Comment by deepakjosp** [comment]
@praveen-murali-ind 
1. [] Toastr story is updated to add a reference to the react-toastify page.
2. [] Duration prop is not supported now by react-toastify. That might be from an older version.
3. [] Verified all the props and those are not supported are listed in the story page.
