### ISSUE TITLE
Replace moment with dayjs

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#141]
dayjs is a fast 2kB alternative to Moment.js

Ref: https://www.npmjs.com/package/dayjs

@vinay0x please share your thoughts

cc @yedhink

**Comment by yedhink** [comment]
100% agree with the change.

- Moment.js is legacy now
- It's 4.28Mb in size

**Comment by vinay0x** [comment]
@edwinbbu Let's do it. Similar API so it should be fine!

**Comment by edwinbbu** [comment]
@edwinbbu _a
