### ISSUE TITLE
Dark mode is shown as default in Chromatic Storybook preview

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#1416]
In Storybook preview, dark mode is shown as the default mode. This is happening only for preview app.

@amaldinesh7 _a  Could you please check

<img width="1440" alt="Screenshot 2022-11-11 at 1 49 26 PM" src="https://user-images.githubusercontent.com/48869249/201296944-e200c5ae-3b45-4169-8478-9b60f6d08218.png">

**Comment by amaldinesh7** [comment]
Chromatic is caching the last used theme. Clearing browser cache will fix it.
