### ISSUE TITLE
Table UI issues

### ISSUE THREAD

**Issue by abhirampai** [bigbinary/neeto-ui#1426]
- Overflow is hidden for the column name
- The scroll bar is not displayed

<img src="https://user-images.githubusercontent.com/101595834/201321665-80ad424b-1767-4602-8887-5fe2f75a6a2c.png"/>

https://github.com/bigbinary/neeto-runner-web/issues/2872#issue-1445272861

@karthiknmenon _a

**Comment by karthiknmenon** [comment]
@abhirampai _a  This should be fixed on the product side. We need to specify the width of a column.

Also, we will only have side/bottom scrollbars if there is an overflow. Else, it would not be shown. However, it would be shown by default if you are using an external mouse.

Please close the issue if this solves the problem.

**Comment by abhirampai** [comment]
I tried with the overflow class, ut worked fine in mac but in windows it was showing multiple scrollbars. But ya giving column width makes sense, will try that. Thanks @karthiknmenon.

**Comment by karthiknmenon** [comment]
@abhirampai multiple scrollbars is an issue that needs to be solved on the product side. Please ping the UI lead of the product.
