### ISSUE TITLE
Pressing the `Enter` key on the `Form` component triggers the validation error

### ISSUE THREAD

**Issue by Thejus-Paul** [bigbinary/neeto-ui#1431]
Ref: https://www.loom.com/share/01453af0d3fe43259d4db9398303f089

cc: @karthiknmenon

**Comment by karthiknmenon** [comment]
@deepakjosp Let's only invoke `validateForm` when the form is dirty.

**Comment by deepakjosp** [comment]
> @deepakjosp Let's only invoke `validateForm` when the form is dirty.

That sounds good. I'll take up this once my current ticket is done!
