### ISSUE TITLE
Add Slider Component 

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#148]
@karthiknmenon _a

**Comment by yedhink** [comment]
@goutham-subramanyam 

Shouldn't we be replacing `Slider` component with `Pane`? 

Refer: https://github.com/bigbinary/neeto-ui/issues/133#issuecomment-753932831

**Comment by goutham-subramanyam** [comment]
@yedhink This is not that slider

**Comment by goutham-subramanyam** [comment]
Close by PR #149

**Comment by yedhink** [comment]
@goutham-subramanyam 

I migration process i'm replacing all `Slider` with `Pane`. So can you let me know what exactly is the use of this `Slider`? What's it's behaviour? 

Asking so that I can know which `Slider` to replace and which not to.

**Comment by goutham-subramanyam** [comment]
@yedhink https://blueprintjs.com/docs/#core/components/sliders

**Comment by goutham-subramanyam** [comment]
It is used in chat customization and KB theme customization.
