### ISSUE TITLE
Ability to "group by"

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#1560]
https://www.loom.com/share/fc05b084adcb4d6c81831e9e3336cc86

https://github.com/orgs/NangoHQ/projects/1

**Comment by sumanranjanpanda** [comment]
@amaldinesh7 _A Can you confirm whether are we done with all the table enhancement-related issues or not?

**Comment by amaldinesh7** [comment]
No. we have not done this feature as `on-hold` label was added to the issue. @sumanranjanpanda

**Comment by sumanranjanpanda** [comment]
> We'll come back to it later when other issues related to table enhancements are done. https://github.com/bigbinary/neeto-ui/issues/1560#issuecomment-1478435882

Okay, I was asking about this. As once we are done with  other issues related to table enhancements, we can start working on it.

**Comment by amaldinesh7** [comment]
[Table enhancements](https://github.com/bigbinary/neeto-ui/issues/1605) epic issue is closed now. 

@sumanranjanpanda [vimeo.com/810239115/ce27e4d433](https://vimeo.com/810239115/ce27e4d433) Please check this video 6:00 from this time.

It will be nearly an impossible task to achieve this feature with AntD table. We have 2 options

- implement this feature in neetoPlanner as the original requirement came from there. It's a different design for the projects page in planner and we are not using neetoUI table there. So first we have to think that, should we bring this feature to table or not.
- If we decide to add this feature to neetoUI table, We have to move away from AntD table.

**Comment by sumanranjanpanda** [comment]
@neerajdotname _A

**Comment by neerajdotname** [comment]
@Amaljith-K _a In one of the issues, you mentioned that we should write our version of AntD. Can you link to that issue?

**Comment by Amaljith-K** [comment]
@neerajdotname 
https://github.com/bigbinary/neeto-ui/issues/1605#issuecomment-1530888495

**Comment by neerajdotname** [comment]
Ref  https://github.com/bigbinary/neeto-ui/issues/1719
