### ISSUE TITLE
Fix eslint issues

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#1657]
Take up this issue only after https://github.com/bigbinary/neeto-ui/pull/1652 is merged

**Comment by Calvinwilson99** [comment]
Had to spend some time debugging an issue where we couldn't use aliases for neeto-icons import as tests would fail. Also spent time debugging an issue where moving named exports to the end of file made the stories not visible in the storybook app. Most changes in the stories folder were manual changes(Moving exports to the end of file and adding fix for stories not coming up when this was done) and took time. Changed the estimate to 1D
