### ISSUE TITLE
Fix issue in storybook url

### ISSUE THREAD

**Issue by soorajbhskrn** [bigbinary/neeto-ui#1665]
- Currently, `https://neeto-ui.neeto.com`  end up on a white screen. We should able to access the same using that URL. The same issue was resolved in `neeto-editor`.

Ref: https://github.com/bigbinary/neeto-editor/pull/650/files

**Comment by amaldinesh7** [comment]
FIxed via - https://github.com/bigbinary/neeto-ui/pull/1712
