### ISSUE TITLE
Remove molecules from here

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/neeto-ui#1684]
We have moved all molecules to neeto-molecules and have updated all products. Now we can delete those components from here.
Reference: https://github.com/bigbinary/neeto-molecules/issues/149

@KrishnapriyaSkk _a please work on this.

**Comment by KrishnapriyaSkk** [comment]
Keeping this issue `on-hold` till a decision is made whether or not to remove the components moved to `neeto-molecules`  from `neetoui`.
