### ISSUE TITLE
Bringing back Color prop to Tag component.

### ISSUE THREAD

**Issue by Nuzair46** [bigbinary/neeto-ui#1698]
Color prop to tag component allows to have custom colored tags which can be modified like Github issue labels. 
cc: @amaldinesh7

**Comment by amaldinesh7** [comment]
@Nuzair46 Can you post a video regarding the exact usecase?

**Comment by Nuzair46** [comment]
@amaldinesh7 _a https://app.usebubbles.com/6n2Kw7Kyz9a5m2oiKZLw82/colored-tags

**Comment by Nuzair46** [comment]
closing this as we will be modifying the component within neetoCode
