### ISSUE TITLE
Postcss warning when using neetoui in neeto-course-nextjs

### ISSUE THREAD

**Issue by sayoojtmc** [bigbinary/neeto-ui#1700]
ref: https://github.com/bigbinary/neeto-course-web/issues/2070

postcss is showing these warnings
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/32578593/235845256-c5008b76-6e97-4403-bdd7-af1ea17bfcca.png">

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/32578593/235845360-1667f4cd-8c82-4101-b2a2-bfd0a383bb21.png">

This is affecting NextJS fast-refresh.

When I went to node_modules/@bigbinary/neetoui/index.css 
and changed color-adjust to print-color-adjust, the app was compiling without any warnings.

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/32578593/235845555-66ce34d2-4fff-4b08-b2d7-a1b07afd821b.png">

**Comment by sumanranjanpanda** [comment]
@amaldinesh7 _a Can you please look into this issue asap?

**Comment by akashdotsrivastava** [comment]
@sumanranjanpanda @amaldinesh7 Can we get someone to take a look at this? The related issue is somewhat of a hassle in neetoCourse.

**Comment by amaldinesh7** [comment]
Will check and fix it ASAP.
