### ISSUE TITLE
Optgroup support

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#1703]
Native HTML `<select>` has grouped options support: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

Having a similar support in neetoUI's `<Select>` component will be a nice addition. A usecase needed in neetoCal is to have a grouped select for picking timezones. The timezones can be grouped into different continents.

**Comment by praveen-murali-ind** [comment]
@amaldinesh7 _a Could you please check the feasibility?
