### ISSUE TITLE
Fix multiple `Toastr`s being shown for a single invocation

### ISSUE THREAD

**Issue by vivek-viswam-rv** [bigbinary/neeto-ui#1713]
https://app.usebubbles.com/nZr1XyEcxz18ei411XaJ6V

cc: @Amaljith-K 

bug _t

**Comment by amaldinesh7** [comment]
@vivek-viswam-rv I could not reproduce the issue https://vimeo.com/831167694/5fc6bf8ca5. Let's connect and debug this.
