### ISSUE TITLE
neeto table component to replace Antd

### ISSUE THREAD

**Issue by neerajsingh0101** [bigbinary/neeto-ui#1719]
Creating this issue with references to other issues so that we can have the discussion in one single place. 

https://github.com/bigbinary/neeto-ui/issues/1560
https://github.com/bigbinary/neeto-ui/issues/1605#issuecomment-1530888495

https://github.com/bigbinary/neeto-ui/issues/1674
https://github.com/bigbinary/neeto-ui/issues/1673

@Amaljith-K _a Can you investigate this issue and come up with a blueprint of what needs to be done in what order and an estimate of the level  of effort needed to get this done.

**Comment by sheminanto** [comment]
@Amaljith-K: neetoTestify had implemented almost all the features needed for the tree component (mentioned in #1673). If you think the tree component will be useful in other products too then it can be added, but only for the neetoTestify's requirement, I won't say it's needed.

**Comment by Amaljith-K** [comment]
@ajmaln _a

**Comment by sumanranjanpanda** [comment]
@ajmaln Any update on this?

**Comment by ajmaln** [comment]
We have found a [possible solution](https://codesandbox.io/s/great-nobel-ku4mx?file=/src/App.js) for adding a `Tree Select` along with the current `Select` component implementation. We can add a prop `isTreeSelect` to enable it. It will be taken up by @amaldinesh7 in https://github.com/bigbinary/neeto-ui/issues/1674

The `Tree` component will be useful in neetoWireframe outliner as well along with neetoTestify, so I think we can add it to neetoUI. An implementation of tree select with features such as expand-collapse, reordering etc. [can be found here](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/docs/examples-tree-sortable--all-features). It uses `dnd-kit` drag-drop library.

I will look further into the requirement of the `Table` component and update the details here.

**Comment by ajmaln** [comment]
I have gone through neeto products and we are using multiple features of the antd table across the products:

- Sorting
- Scrollable table
- Resizable columns
- Reorderable columns
- Pagination and row selection
- Split cells: 

<img width="715" alt="image" src="https://github.com/bigbinary/neeto-ui/assets/22348659/9143808c-7fdb-49cc-b0d9-4248d1d2c4ab">

It would take a lot of effort to build these features from scratch if we were proceeding with a custom table component. From the original requirements in the issue, the reorderable columns and resizable columns features have been already implemented in neetoUI table. For the `Group-by` feature, I think extracting the custom table component from neetoPlanner would be better.

<img width="1099" alt="neetoPlanner table" src="https://github.com/bigbinary/neeto-ui/assets/22348659/87b8abf0-e61c-4bc1-bdff-c89c7387d84e">

@Amaljith-K Could you please suggest regarding the virtualization as discussed.

**Comment by Amaljith-K** [comment]
@ajmaln I agree with the points. Let us continue using antd table.
Since we can't use react-window or react-virtualized for antd, let's limit the number of rows per page.
@ajmaln _a please find an optimum number of items per page so that it doesn't affect the performance or force the user to click the next page too frequently. Let us standardize it.

**Comment by ajmaln** [comment]
I have gone through a few projects to check the current pagination size and the response size & time observed for the same. 

Product | API | Paginated at | Response size | Response time | 
--------|-----|-----------|----------------|--------------|
neetoForm | `forms` | `15` |  `2-3.5kb` | `200-500ms` |
neetoCal | `meetings` | No pagination (around 120 items) |  `11.9kb` | `2.8s` |
neetoDesk | `tickets` | `25` | `3.5kb` | `1.4s` |
neetoChat | `contacts` | `15` | `2.8kb` | `1.21s` |
neetoWireframe | `projects` | `15` | `3.2kb` | `600ms` |
neetoReplay | `replay_sessions` | `25` | `2.3kb` | `1.21s` |

From the above observation, the size and the response time depend on the complexity of queries and the amount of data per record returned from the backend. So picking an ideal pagination limit would be difficult based on this. 

From a previous [discussion](https://github.com/bigbinary/neeto-engineering-web/issues/347) regarding the pagination size, it was decided to go with `30` items per page. Currently, it is set as the default value for items per page in the neetoUI table. However, the value is being overridden at the host level on most products. I think we can enforce the items per page limit of `30` on all products.

@Amaljith-K LMK your thoughts

**Comment by Amaljith-K** [comment]
@subins2000 if neetoCal takes 2.8 seconds to respond with a list of 120 items in total, something is off.

**Comment by ajmaln** [comment]
Closing this issue, created an engineering issue for enforcing the items per page count: https://github.com/bigbinary/neeto-ui/issues/1719

**Comment by nithinkr1shna** [comment]
I guess this issue will enforce people to optimize DB queries 😄
