### ISSUE TITLE
Add ability to specify the first focusable element inside an Alert

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/neeto-ui#1734]
In some cases, we need to have the `primary` button focused when the `Alert` component is rendered. Currently, this is not supported. Let's keep the initial focus on the `primary` button. Also, there should be an option to change focus to some other element if required.

cc: @amaldinesh7, @sandip-mane

**Comment by sandip-mane** [comment]
IMO the primary button should always be in the focus.
Just for some odd cases, it could be made configurable. (Without any config, the primary button should be having the focus)

**Comment by praveen-murali-ind** [comment]
@amaldinesh7 _a Could you please check?

**Comment by amaldinesh7** [comment]
@sandip-mane @abilash-sajeev As per accessibility practices, Close button should be focused by default. Will add an option to configure it.

**Comment by sandip-mane** [comment]
@amaldinesh7 the modals can be closed with `esc`, I think `enter` should have the focus on primary actions. 
Instead of making it configurable, I think we should make it default, otherwise, it's the fix that we will have to do everywhere.

We can make it configurable for one-off cases.

**Comment by abilash-sajeev** [comment]
@sandip-mane Please find the reference issue for this requirement.
- https://github.com/bigbinary/neeto-desk-web/issues/16484

**Comment by sandip-mane** [comment]
I extracted that issue from a video that Neeraj posted. I was not able to find it, or probably it was during screen sharing on a call.

**Comment by abilash-sajeev** [comment]
@sandip-mane Neeraj shared that video on the Roadmap. 
- [Feedback on keyboard shortcuts](https://neeto-engineering.neetoplanner.com/ND/board/137)

**Comment by amaldinesh7** [comment]
@sandip-mane Please take a look at this video - https://vimeo.com/851250003/5e8e7b140a

cc: @ajmaln

**Comment by sandip-mane** [comment]
Seems fair but for some reason, I feel the primary button should always have focus. I would not click `enter` on a destructive modal even to close the modal. I would always use `esc`.

@neerajdotname please suggest your opinion as it's going to affect everywhere.

**Comment by neerajdotname** [comment]
Agree with @amaldinesh7 that the destructive action should not have the focus. What he showed in the video is the right way. So let's implement that.
