### ISSUE TITLE
Handle nested formik values (dot paths) in ScrollToErrorField component

### ISSUE THREAD

**Issue by josephmathew900** [bigbinary/neeto-ui#1741]
Ref: https://bigbinary.slack.com/archives/C03T5R6QYSC/p1688026200465819?thread_ts=1688019939.823089&cid=C03T5R6QYSC

@soorajjtk _a

**Comment by josephmathew900** [comment]
cc: @ajmaln

**Comment by ajmaln** [comment]
@Calvinwilson99 _a
