### ISSUE TITLE
Conditionally render confirmation message in alert component

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#175]
There is no option to hide/update confirmation message `Are you sure you want to continue?` in Alert component. 

<img width="893" alt="Screenshot 2021-02-18 at 3 07 35 PM" src="https://user-images.githubusercontent.com/17916573/108337822-8d858580-71fb-11eb-8824-2baeb5170ab2.png">

cc @goutham-subramanyam

**Comment by vinay0x** [comment]
@edwinbbu This is necessary. Otherwise people will start creating custom components for it.

**Comment by edwinbbu** [comment]
@edwinbbu _a
