### ISSUE TITLE
Dropdown popover has transparent bottom part

### ISSUE THREAD

**Issue by rishimohan** [bigbinary/neeto-ui#176]
We'll need to add background specifically to the popover container.

Issue: 
![2021-02-18 at 19 11](https://user-images.githubusercontent.com/14031295/108365320-1660e900-721d-11eb-8d9b-51c0643eddff.png)

**Comment by edwinbbu** [comment]
Related issue. The dropdown in navbar is also having transparent part.

<img width="394" alt="Screenshot 2021-02-19 at 11 16 18 AM" src="https://user-images.githubusercontent.com/17916573/108463166-ec063e80-72a3-11eb-806a-40a439785417.png">

cc @goutham-subramanyam
