### ISSUE TITLE
Spaces should not be allowed

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#1760]
Time to time I see issues like this one https://github.com/bigbinary/neeto-cal-web/issues/4117

Assuming that discount code is using neetoUI input field is it not something that neetoUI can take of universally by default?

@amaldinesh7 @ajmaln @Amaljith-K

**Comment by Amaljith-K** [comment]
We can add an `allowedCharacters` prop to neetoUI input component.
It will accept a regex. The regex will be tested against every input character.
The character will be registered only if it matches the given regex.

@ajmaln _a it should be minor work. Please assign someone to work on it.

**Comment by ajmaln** [comment]
@Calvinwilson99 _a
