### ISSUE TITLE
Make DateRange presets docs simpler

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#1763]
Instead of showing this expanded range presets which is very looooong

<img width="558" alt="Screenshot 2023-08-01 at 12 34 21 AM" src="https://github.com/bigbinary/neeto-ui/assets/2305675/1475d4ca-519a-4593-bbab-3c616248b830">

show the actual ranges which I found from the storybook: https://github.com/bigbinary/neeto-ui/blob/767c7c69ed1ed3524d38ee9591ca45ee373e5ff6/stories/Components/DateInput.stories.jsx#L157

<img width="688" alt="Screenshot 2023-08-01 at 12 35 07 AM" src="https://github.com/bigbinary/neeto-ui/assets/2305675/256c089d-2fa2-43e5-8158-48794ad51fb5">

**Comment by praveen-murali-ind** [comment]
@ajmaln _a
