### ISSUE TITLE
Set the date without requiring ok

### ISSUE THREAD

**Issue by aryanandarnav13** [bigbinary/neeto-ui#1765]
Ref: [issue](https://github.com/bigbinary/neeto-planner-web/issues/4329)

**Comment by aryanandarnav13** [comment]
@ajmaln _a

**Comment by ajmaln** [comment]
While looking into the issue, came across `onSelect` prop which gets executed whenever the user selects a date. This could be used to set the date value as soon as the user clicks on a date or time.

**Comment by ajmaln** [comment]
Closing as the issue is resolved.
