### ISSUE TITLE
Support for adding icon in input fields

### ISSUE THREAD

**Issue by rishimohan** [bigbinary/neeto-ui#177]
Ability to add icon in the start or end of the input field would be great in case of search box etc. @vinay0x @goutham-subramanyam thoughts?

![2021-02-18 at 19 13](https://user-images.githubusercontent.com/14031295/108365694-81aabb00-721d-11eb-9313-dd72f0fa3467.png)

**Comment by vinay0x** [comment]
@rishimohan This is good. This could be useful addition 👍🏻

**Comment by goutham-subramanyam** [comment]
@rishimohan We already have `prefix` and `suffix` prop which can be used for the same purpose.

Eg:

<img width="930" alt="Screenshot 2021-02-23 at 8 49 28 PM" src="https://user-images.githubusercontent.com/24496302/108864881-a1285600-7618-11eb-9b8a-faf72f158985.png">

**Comment by rishimohan** [comment]
@goutham-subramanyam That works great, I missed it since it wasn't in docs in catalog, I'll just update the catalog with documentation for `prefix` and `suffix` props.
