### ISSUE TITLE
Buttons used for tab labels need an appropriate type attribute

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#1777]
The buttons tab labels are using needs a `type="button"` attribute.

<img width="619" alt="Screenshot 2023-08-12 at 1 08 20 AM" src="https://github.com/bigbinary/neeto-ui/assets/2305675/27298f2d-f8dc-494d-b115-7d6646274271">

**Comment by praveen-murali-ind** [comment]
@AkhilXavier95 _a
