### ISSUE TITLE
Add data-cy attributes to all missing elements

### ISSUE THREAD

**Issue by VarunSriram99** [bigbinary/neeto-ui#1779]
Current elements missing data-cy label:

|     Element                |         Current Selector                  |
|---------------------|--------------------------------|
| checkbox            | .neeto-ui-checkbox             |
| paneBody            | .neeto-ui-pane__body           |
| paneHeader          | .neeto-ui-pane__header         |
| selectOption        | .neeto-ui-react-select__option |
| toastCloseButton    | .neeto-ui-toastr__close-button |
| windowAlert         | #alert-box                     |
| toastIcon           | .Toastify__toast-icon          |
| paneModalCrossIcon  | .neeto-ui-pane__close          |
| alertModalCrossIcon | .neeto-ui-modal__close         |
| backDrop            | [data-testid='backdrop']       |
| tooltip             | .tippy-box                     |
| neetoUiSwitch | .neeto-ui-switch |
| placeholderFieldText | .neeto-ui-react-select__placeholder |
| optionSelectDropdownMenu | .neeto-ui-react-select__menu |
| dropdownContainer | .neeto-ui-react-select__value-container |
| modalHeader | .neeto-ui-modal__header |
| modalBody | .neeto-ui-modal__body |
| selectInputContainer | .neeto-ui-react-select__input-container |
| selectInput | .neeto-ui-react-select__input |
| inputError | .neeto-ui-input__error |
| modalFooter | .neeto-ui-modal__footer |
| modalHeaderDescription | .neeto-ui-modal__header-desc |

Table selectors:

|     Table element        |           current selector                 |
|-------------|--------------------------------|
| column   | td   |
| tableBody   | .ant-table-body                |
| tableHeader | .ant-table-thead th            |
| tableRow    | .ant-table-tbody tr            |
| spinner     | .ant-spin                      |
| heading  | tr > th |
| checkbox | .ant-checkbox-input |

Profile Selectors:

profileOptionsContainer: '[class="tippy-box sidebar-featured-tooltip__content"]'

Date Selectors: 

|     Table element        |           current selector                 |
|-------------|--------------------------------|
| todayButton | .ant-picker-today-btn |
| nowButton | .ant-picker-now-btn |
| nowClass | .ant-picker-now |
| datePanel | .ant-picker-date-panel |
| nextMonthNavigationButton | .ant-picker-header-next-btn |
| calendarsPanel | .ant-picker-panels |
| clearDate | .ant-picker-clear |
| meetingDateInput | .ant-picker-input |

**Comment by VarunSriram99** [comment]
@KrishnapriyaSkk _a

CC: @neerajdotname

**Comment by KrishnapriyaSkk** [comment]
Some of the provided selectors are from `react-select` and `antd`. 
For `react-select` we can provide `data-cy` by giving [custom components](https://react-select.com/components). 
Updating the estimate to make this changes to components and find out a way to pass `data-cy` to `antd` components, if possible.

**Comment by KrishnapriyaSkk** [comment]
It doesn't seem like it is possible to pass `data-cy` attributes to `antd` components, for specific elements. The only way is to wrap everything within a `div` . But, this is not an acceptable approach. Hence, I have added `data-cy` for all other selectors except `antd` selectors.

cc: @ajmaln

**Comment by neerajdotname** [comment]
@ajil-paul Please note the last comment.

**Comment by KrishnapriyaSkk** [comment]
@ajil-paul 
I have corrected the comment above. I have added `data-cy` for `tippy-box`.
