### ISSUE TITLE
ScrollToErrorField component does not scroll for `Select` component

### ISSUE THREAD

**Issue by CalvinChiramal** [bigbinary/neeto-ui#1785]
The `Select` component and any other component that is using `react-select` internally has issues with `ScrollToErrorField` in formik. The specified `name` attribute to be used with formik forms is added to an input field of type `hidden`.  If such a field has an error, it cannot be scrolled to since it's hidden.
We need to find a work around in either the `Select` component or `ScrollToErrorField` component.

**Comment by ajmaln** [comment]
@AkhilXavier95 _a

**Comment by ajmaln** [comment]
Demo: https://youtu.be/U2oiD_j2fD4

This issue is a blocker for: https://github.com/bigbinary/neeto-desk-web/issues/17637
