### ISSUE TITLE
Dark theme related documentation is broken

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#1798]
<img width="1269" alt="image" src="https://github.com/bigbinary/neeto-ui/assets/31244999/8a865e21-cee3-4f40-8479-88946eae44d3">

@praveen-murali-ind _a Please assign this to someone.

**Comment by praveen-murali-ind** [comment]
@yedhink I am unable to recreate the issue. It is working for me.

<img width="1440" alt="Screenshot 2023-09-06 at 4 12 27 PM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/be8009fc-b0b5-4a7d-ad24-6540b3fa38dd">

**Comment by praveen-murali-ind** [comment]
Closing this issue for now.
