### ISSUE TITLE
neetoui is not compatible with Next.js framework - neetoui components need to be SSR ready

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#180]
## Context
Please refer this video: https://youtu.be/BQs2VIUmp8s

## Steps to reproduce
Create a `Next.js` application and import any neetoui component in say the `Home` page.

## Possible Cause of Error
Explained in video

cc: @rishimohan @edwinbbu

**Comment by vinay0x** [comment]
@yedhink There are some references to the window object in the compiled module. Hence the error. See if it's working with any other components than Input. We have a lot of third-party stuff such as Blueprint and Formik. If any of those are incompatible with SSR, that drips down into NeetoUI too. 

And I'm not sure if the situation warrants the need to port neeto-ui to Next.js at the moment. BigBinary website doesn't follow the NeetoUI design styles/patterns. It's styled differently. And we want to make sure that catering to 1% doesn't break the 99%. You can take a look at (or anyone seeing this for that matter) it if you get free time and reopen the issue if it is an easy fix and won't break neeto-ui for the main neeto applications that use it.
