### ISSUE TITLE
Table header content is not center aligned when sort option is present

### ISSUE THREAD

**Issue by goutham-subramanyam** [bigbinary/neeto-ui#1806]
![Group 2](https://github.com/bigbinary/neeto-ui/assets/24496302/fb2f873f-f9bc-4173-a610-046cec601aea)
![Group 1](https://github.com/bigbinary/neeto-ui/assets/24496302/64e538db-f73b-4266-ad7f-e9420cea2cf3)

cc: @praveen-murali-ind

**Comment by praveen-murali-ind** [comment]
Closing this issue for now. We have checked and noticed that currently there is no workaround for this issue since the sort icons are visible only on the hover. The alignment is slightly off because of the reserved space for the sort icon.
