### ISSUE TITLE
Fix issues in color picker

### ISSUE THREAD

**Issue by ajil-paul** [bigbinary/neeto-ui#1812]
Ref: https://vimeo.com/863993279/bc2175834a

**Comment by ajil-paul** [comment]
cc @ajmaln

**Comment by ajmaln** [comment]
@adityamahajan-io _a

**Comment by sumanranjanpanda** [comment]
@ajmaln  What's the current status of this issue?

If we leave issues with the `priority` label unaddressed for a longer period, people may become desensitized to the importance of the `priority` label.

If this issue is not a priority, please remove the label.

**Comment by ajmaln** [comment]
@sumanranjanpanda This will be fixed in https://github.com/bigbinary/neeto-ui/pull/1815
