### ISSUE TITLE
Make title and message in `BlockNavigation` component customizable

### ISSUE THREAD

**Issue by vishnuMohanan01** [bigbinary/neeto-ui#1819]
Met with a use case in `neetoDesk` where we need to show context specific title and message in a `BlockNavigation` alert. 

For more details watch from `1 minute and 50 seconds` of the recording posted in https://github.com/bigbinary/neeto-desk-web/issues/17320#issuecomment-1706514723.

cc: @sandip-mane

**Comment by sandip-mane** [comment]
@ajmaln can we take it up on priority? Seems like a small change. We will be blocked until it's done.

**Comment by ajmaln** [comment]
Will get it done today
