### ISSUE TITLE
Fix console warnings for checkbox

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto-ui#182]
![image](https://user-images.githubusercontent.com/9862943/108701040-76150800-752d-11eb-920b-74de2cdbf2eb.png)

**Comment by Harshit-frontend** [comment]
Team why we are using both controlled and uncontrolled component approach for Input Component.

The above warning occurs because we do not pass onChange event handler to components.

cc @vinay0x

**Comment by Harshit-frontend** [comment]
Sharing Absolute Path 

_neeto-ui/lib/components/Input.js_

**Comment by edwinbbu** [comment]
I feel `onChange` should be passed down from the application where neetoui checkbox is being used. 

Another option is have a default `onChange = {()=>{}}` but that won't trigger warning if a person forgets to add onChange in the client application.

**Comment by edwinbbu** [comment]
@vinay0x _a Please add your input and feel free to close the issue if everything looks good.

**Comment by Harshit-frontend** [comment]
@edwinbbu  Yes, we can pass `onChange` to get rid of this warning. But why we are using both a controlled and uncontrolled approach in Input component?

**Comment by vinay0x** [comment]
@Harshit-frontend Add a propTypes validation making it mandatory. If `value` is passed, `onChange` must be there. Else it's ok. It's up to the host app to choose a controlled or uncontrolled approach.

**Comment by Harshit-frontend** [comment]
Both `value` and `onChange` has to be there in order to work Input component properly.

Let's not make the Input Component  complicated for user. I believe its better to go ahead and use only controlled component approach.

**Comment by vinay0x** [comment]
If we plan to enforce it, we'd need to do it across all components. It's not a pressing issue. This way we leave the component as similar to plain HTML elements. Default elements allow both controlled and uncontrolled functionality. Let's not change that for now. 

Closing the issue.

**Comment by Harshit-frontend** [comment]
Team, 

I can still see the warning in my local. Please have a look in below attached screenshot

<img width="1437" alt="Screenshot 1943-02-14 at 11 53 06 AM" src="https://user-images.githubusercontent.com/83356733/116967253-84bb3080-accf-11eb-8753-c98e2742fc0e.png">

**Comment by goutham-subramanyam** [comment]
@Harshit-frontend I have fixed the console errors in #246
