### ISSUE TITLE
Issue with SubHeader layout component 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#183]
Unable to reuse SubHeader.

Issue came up while testing in NeetoAuth.
<img width="1792" alt="Screenshot 2021-02-22 at 6 05 14 PM" src="https://user-images.githubusercontent.com/17916573/108713958-ef692680-753e-11eb-8a31-05ca426cc738.png">

cc @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
We don't need to have `Layout` components in neetoui since they'll be mostly customized from product to product

**Comment by edwinbbu** [comment]
Reopening the issue since we have a similar layout in `neeto-kb-web` and `neeto-chat-web`

**Comment by edwinbbu** [comment]
@edwinbbu _a

**Comment by edwinbbu** [comment]
Fixed via PR #188
