### ISSUE TITLE
Remove `ClearIndicator: null` for `MultiEmailInput`

### ISSUE THREAD

**Issue by AkhilXavier95** [bigbinary/neeto-ui#1832]
ref: https://github.com/bigbinary/neeto-molecules/issues/545

Remove `ClearIndicator` added in the custom components for `MultiEmailInput`

cc: @ajmaln

**Comment by praveen-murali-ind** [comment]
@AkhilXavier95 _a Can we use the same `clear` icon we are using for neetoUI Select component?

**Select icon vs existing icon difference**

<img width="397" alt="Screenshot 2023-10-06 at 11 11 18 AM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/4cbc0e9c-31f6-4731-a4ca-c8177564b801">

<img width="408" alt="Screenshot 2023-10-06 at 11 12 26 AM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/4818ac81-4fb1-4088-8b8b-e55f891c8978">
