### ISSUE TITLE
Improve Storybook documentation for neetoUI

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#1838]
- [x] [Using Storybook](https://neetix.neetokb.com/articles/using-storybook)
- [x] [Color](https://neetix.neetokb.com/articles/color)
- [x] [CSS variables](https://neetix.neetokb.com/articles/css-variables-support)
- [x] [Dark mode](https://neetix.neetokb.com/articles/dark-mode)
- [x] [Customise neetoUI](https://neetix.neetokb.com/articles/customise-neetoui)

@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@nitinprojects _a As discussed, please update the documentation.

**Comment by nitinprojects** [comment]
@praveen-murali-ind  Can we add the colours for each use-case just like [Tailwind](
https://tailwindcss.com/docs/text-color#arbitrary-values) has in table format?

https://neetix.neetokb.com/articles/text-color?version=draft

Please share your thoughts on whether this is worth the effort?

**Comment by nitinprojects** [comment]
@praveen-murali-ind  Ignore the above comment - I see we already have it in neetoUI - https://neeto-ui.neeto.com/?path=/docs/foundation-helpers-color--page
