### ISSUE TITLE
Bug reported by Sagar

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#1851]
https://pragetx.neetorecord.com/watch/7588c9da-ff34-4cf2-925a-8604d14c099e

**Comment by CalvinChiramal** [comment]
The source link redirects to the `neeto-icons` repo. Since the repo is private, anyone who does not have access to the bigbinary organization will get the 404 error.
If we do not plan to make the source code for `neeto-icons` public, we can remove the link from the storybook.

cc: @ajmaln

**Comment by ajmaln** [comment]
I think we can remove the link for now, will discuss and decide if we want to make `neeto-icons` public.
