### ISSUE TITLE
View more in Card component is not working properly

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#186]
@edwinbbu _a

cc @goutham-subramanyam

**Comment by Harshit-frontend** [comment]
Team, I don't see any issue when I checked it on local with the master branch.

Attaching a video of it 
https://www.loom.com/share/e41408fcf8664020aa63fafb0880917a

@vinay0x

**Comment by edwinbbu** [comment]
@Harshit-frontend Please check the issue which is faced in neetoDesk
https://www.loom.com/share/a507b738713e40a58e9e3940ad170d35
