### ISSUE TITLE
Info toastr not available

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#19]
Info toastr is exported while the success and error toastr is works fine

**Comment by vinay0x** [comment]
Do we really use info Toastrs? I haven't seen any place where we need to use it. That's why I had excluded it. If you see any places where it could be useful, please handle it. Otherwise let's defer.

**Comment by edwinbbu** [comment]
@vinay0x In NitroForm we have a button `Copy Link` which copies the url to clipboard. We were showing info toastr in this case. Toastr broke after updating the nitroui. 
<img width="1480" alt="Screenshot 2020-11-02 at 10 52 47 AM" src="https://user-images.githubusercontent.com/17916573/97832744-978d8200-1cf9-11eb-85e2-7bf5d2c8e33e.png">

**Comment by edwinbbu** [comment]
Closing the issue. Didn't require the change till now. Can reopen if the required in the future.
