### ISSUE TITLE
Can `Typography` support `required` prop?

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto-ui#1919]
At places, we have such labels where we would like to add an asterisk. 
![Screenshot 2023-10-25 at 5 01 07 PM](https://github.com/bigbinary/neeto-ui/assets/9862943/85f2b3d7-ec4a-4a11-9887-362aefbd2c7f)

These labels are created using the `Typography` component.

Example:
https://github.com/bigbinary/neeto-kb-web/blob/c6db197dded5a3a629db6706ef9be803fc88cbef/app/javascript/src/components/Settings/Customize/Sidebar/General/FormBody.jsx#L94-L102

Is it fair to ask for the support of `required` prop for the `Typography` component?

---

Current approach without the above-requested support:
1. Create a duplicate translation with `*` at the end
2. Use the new translation

**Comment by sandip-mane** [comment]
@ajmaln _a please check

**Comment by praveen-murali-ind** [comment]
@sandip-mane Instead of Typography component please use the neetoUI Label component in the above mentioned areas. No need to override the default label styles.

**Comment by ajmaln** [comment]
@sandip-mane As discussed, let's use the neetoUI label is these cases without any style overrides. Closing

**Comment by sandip-mane** [comment]
@praveen-murali-ind @ajmaln 
Please check if the following cases are fine:
## 1.
#### Before:
![Screenshot 2023-10-25 at 7 00 00 PM](https://github.com/bigbinary/neeto-ui/assets/9862943/af54428e-597f-4f35-8448-73770b5d6e9d)

#### After:
![image](https://github.com/bigbinary/neeto-ui/assets/9862943/725a8b89-b5a8-4452-8b4b-9e75a8ec39ae)

## 2.
#### Before:
![Screenshot 2023-10-25 at 6 56 22 PM](https://github.com/bigbinary/neeto-ui/assets/9862943/8f98094c-f719-4738-9a07-358258b1efc8)

#### After:
![Screenshot 2023-10-25 at 6 57 21 PM](https://github.com/bigbinary/neeto-ui/assets/9862943/913f116b-fea9-4459-abee-09b0c1b33273)

**Comment by praveen-murali-ind** [comment]
@sandip-mane 

I think these asterisks are not needed as they are not adding any value here. The rest of the changes look good to me.

![image](https://github.com/bigbinary/neeto-ui/assets/9862943/f5084dd0-2cae-4815-8369-9c3ee1808768)

**Comment by ajmaln** [comment]
@sandip-mane I agree with @praveen-murali-ind, The color inputs will be always having a value and a user can't clear it so, the asterisks doesn't add much value here. Rest LGTM

**Comment by sandip-mane** [comment]
Yes, I've reverted that change.
