### ISSUE TITLE
Enhance pagination URL param handling in the Table component

### ISSUE THREAD

**Issue by vijay2136** [bigbinary/neeto-ui#1957]
Things to do: 
1. Check different products and see if something would break if we make preserveTableStateInQuery true by default.
2. Standardize pagination keywords in neetoui as well
3. We don’t need preserveTableStateInQuery prop. If handlePageChange is provided, we will let host project manage entire thing. Otherwise, we will use query params style.
4. I can see a lot of functions from neeto-cist copied to src/components/Table/utils.js. We don’t need that. Use the package neeto-cist it is very lightweight & supports treeshaking.

cc: @Amaljith-K

**Comment by Amaljith-K** [comment]
Also: Pagination component in neeto-ui needs change.
If navigate prop is provided, execute it.
If it is not provided, we will run the query param logic.
