### ISSUE TITLE
Add data-cy for description error on tickets page 

### ISSUE THREAD

**Issue by DhruviKamani** [bigbinary/neeto-ui#1959]
Current selector: ".neeto-ui-input__error"
Refer below screenshot:
<img width="1423" alt="Screenshot 2023-11-07 at 12 28 40 PM" src="https://github.com/bigbinary/neeto-ui/assets/78584248/8a76e295-6761-4e91-833f-3a9312a3ebb9">

**Comment by KrishnapriyaSkk** [comment]
Closing this issue as this needs to be fixed from `neeto-editor`.
