### ISSUE TITLE
Upgrade to latest `@testing-library/user-event`

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#1962]
This would need some update to the current tests to make it compatible.

@CalvinChiramal _a

**Comment by Amaljith-K** [comment]
@ittyjose _a please take care of this

**Comment by ittyjose** [comment]
@Amaljith-K and @ajmaln,  


I was able to reduce the test suits failing from 40+ to 12

Related to 12 test suites,

user.type have some issues even if we add async await. This is already mentioned as an issue in the lib [github](https://github.com/testing-library/user-event/issues/1150) itself.

I have tried for `waitFor` and with timeout in options and none of them resolved the issue. Only the setTimeout is working here and resolve. But we can't use that in the test cases which will increase the time to test and create uncertainty. 

Let me know your thoughts on this.
