### ISSUE TITLE
Add data-cy to date-time picker today button

### ISSUE THREAD

**Issue by yatharthvij** [bigbinary/neeto-ui#1982]
Add data-cy to date-time picker today button. 
Ref: 
<img width="1440" alt="Screenshot 2023-11-16 at 4 26 57 PM" src="https://github.com/bigbinary/neeto-ui/assets/75108777/12a32d21-7b42-4c03-94ef-43e748d1d538">

**Comment by adityamahajan-io** [comment]
The `Today` button is part of https://ant.design/components/date-picker. `data-cy` cannot be added as passing props to this button is not supported.

**Comment by yatharthvij** [comment]
@adityamahajan-io _a Since we cannot add data-cy to this element, we can close this issue.
