### ISSUE TITLE
Unable to set initial values for the grouped select

### ISSUE THREAD

**Issue by devukurup** [bigbinary/neeto-ui#1988]
<img width="1430" alt="Screenshot 2023-11-20 at 10 56 16 AM" src="https://github.com/bigbinary/neeto-ui/assets/40559138/5e8edd90-8457-4fa0-8b9c-c6b9152946d2">

When we set the `isMulti` value to `false`, the default value is not set even if its present.

**Comment by yedhink** [comment]
@ajmaln _a Please look into this.

**Comment by ajmaln** [comment]
@ittyjose _a Please look into the default value issue when passing grouped options.
