### ISSUE TITLE
Value at Index position 1 is set as the current/default value

### ISSUE THREAD

**Issue by nithinkr1shna** [bigbinary/neeto-ui#203]
I was working with `SubHeader` component in the `Layouts` section. I was trying to set the default value or the current `sortProp` for [ a PR in neeto-chat-web](url)
https://github.com/bigbinary/neeto-ui/blob/a85dff7db2bbd07987c952bb2c233a5db92af8a2/lib/layouts/SubHeader.js#L45-L50

It was found that the index position 1 is set as the current `sortProp`. Is there any specific reason for setting the value at index position 1, as default?
Similar is the case for direction.

**Comment by edwinbbu** [comment]
@nithinkr1shna Index position 1 doesn't need to be set as current `sortProp`. 
The change first came up in PR https://github.com/bigbinary/neeto-desk-web/pull/9996/files which only handles a specific use case. Then the Subheader was synced to neetoui.
This change can be reverted and index can be 0 itself.
