### ISSUE TITLE
Typo in table header options "Desceding" should be "Descending"

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto-ui#2052]
![SCR-20231222-mzqk](https://github.com/bigbinary/neeto-ui/assets/6805530/4d10fad6-ffbf-4ca4-a46b-923378225cf7)

**Comment by praveen-murali-ind** [comment]
@akkshaylawrence _a

**Comment by akkshaylawrence** [comment]
@praveen-murali-ind This will be fixed in https://github.com/bigbinary/neeto-ui/pull/2051
