### ISSUE TITLE
Table styles are broken/unavailable

### ISSUE THREAD

**Issue by farhanlatheef** [bigbinary/neeto-ui#2057]
Table styles are broken/unavailable in v6.1.0. 

<img width="1258" alt="Screenshot 2024-01-03 at 12 14 00 PM" src="https://github.com/bigbinary/neeto-ui/assets/10956193/67de4f08-112b-412a-9f99-76dc13a1d1f3">
<img width="1259" alt="Screenshot 2024-01-03 at 12 15 38 PM" src="https://github.com/bigbinary/neeto-ui/assets/10956193/8ab164b0-b1a2-46c4-b6d6-b185ac636d96">

**Comment by praveen-murali-ind** [comment]
@farhanlatheef I couldn't recreate this issue on [Storybook](https://neeto-ui.neeto.com/?path=/story/components-table--default&hash=5feb7ad51af92d0d1197204f651687db7a09523b). Could you please specify where you were able to see this issue?

<img width="1440" alt="Screenshot 2024-01-03 at 7 36 43 PM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/d2cdb95e-70db-4ffa-9f80-b9ec25002fc4">

**Comment by farhanlatheef** [comment]
@praveen-murali-ind _a Yes Issue is not recreatable in storybook. I think issue is in the bundling process. For now I switch to  5.2.46 Which doesn't have the issue. I inspected the `index.css` after bundling and when I search table related styles it is missing there.

**Comment by praveen-murali-ind** [comment]
@farhanlatheef Could you please specify where you were able to see this issue?

**Comment by farhanlatheef** [comment]
@praveen-murali-ind  I am working on a new repo(https://github.com/bigbinary/neeto-seo-audit-electron). Issue was with `antd` version, in readme it is mentioned `antd@4.24.3` as dependency. but when I look at other neeto products it is using `antd@5.9.2` and when I switched to it the issue is resolved. May be just update the readme. For now we can close the issue.
