### ISSUE TITLE
Add support for adding custom actions to table header

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/neeto-ui#2067]
For example, `neeto-form` needs to display `edit` and `delete` options for some columns in the table header actions.

![More actions for table header cell](https://github.com/bigbinary/neeto-ui/assets/35305344/ad745ee8-23b7-4ca7-83ec-60e98dace203)

Ref: https://github.com/bigbinary/neeto-form-web/issues/9090

**Comment by chiraggshah** [comment]
@josephmathew900 : Can we prioritize this?

**Comment by josephmathew900** [comment]
@farhanlatheef _a Please check this issue.
