### ISSUE TITLE
Fix time picking logic in DateTimePicker and also add a prop to remove time picker

### ISSUE THREAD

**Issue by lakshyakanungo** [bigbinary/neeto-ui#2086]
https://lakshya.neetorecord.com/watch/64daaa69-9941-42ce-919c-db651ede9c2f
cc: @yedhink

**Comment by yedhink** [comment]
@farhanlatheef _a Please take a look into this with some priority. Some of the PRs in planner are dependent on this issue.

cc: @josephmathew900

**Comment by farhanlatheef** [comment]
@yedhink, I discussed the issue with @lakshyakanungo . I informed her that if the requirement only involves a date, she can simply use the `DatePicker` from `neetoui`, which is the same component used in the DateTimePicker for picking dates.

**Comment by yedhink** [comment]
@farhanlatheef I understand your point. But I was a bit confused on why we are maintaining a `DatePicker` and a `DateTimePicker` in neetoUI. Aren't both these is similar with just a addition of Time field? Like do we need to maintain two versions of it?

cc: @praveen-murali-ind

**Comment by philson-philip** [comment]
@yedhink There is no bug with `DateTimePicker` component. Please check this video https://philson.neetorecord.com/watch/57e62fc2-ce9c-4a74-9a01-d09f53fd6833
cc: @lakshyakanungo

**Comment by josephmathew900** [comment]
@praveen-murali-ind @philson-philip @farhanlatheef @yedhink https://joseph-mathew.neetorecord.com/watch/41dbe1ee-ee93-418d-a9b5-95dc80597c6e LMK your thoughts.

**Comment by farhanlatheef** [comment]
@josephmathew900  https://farhan-ck.neetorecord.com/watch/fe368116-0ae1-43ea-be0f-f5afd79e1451.

**Comment by philson-philip** [comment]
@josephmathew900 https://philson.neetorecord.com/watch/6692e085-5484-4845-ab8b-774f4dfeb342

**Comment by josephmathew900** [comment]
@farhanlatheef @philson-philip Agreed.

Action Items:

- [ ] Remove `showTime` prop from `DatePicker` component.
- [ ] Remove `TimePicker` component.
- [ ] Rename `TimePickerInput` to `TimePicker`.

Migration is handled in this issue - https://github.com/bigbinary/neeto-engineering-web/issues/630. Once this issue is closed, we can proceed with this.

**Comment by farhanlatheef** [comment]
This issue will be picked up once the rollout is complete. https://github.com/bigbinary/neeto-engineering-web/issues/630.

**Comment by josephmathew900** [comment]
This will be addressed in https://github.com/bigbinary/neeto-ui/issues/2234.
