### ISSUE TITLE
Cursor should stay on the clicked page in Pagination component

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#2089]
https://yedhin.neetorecord.com/watch/4dedc045-d4b5-426d-b83b-41b38ac14628

@farhanlatheef @josephmathew900 @AbhayVAshokan @praveen-murali-ind Lemme know your thoughts.

**Comment by josephmathew900** [comment]
@yedhink https://joseph-mathew.neetorecord.com/watch/2abbc72c-47ea-4bd2-9ac8-4eae759f51b3

**Comment by yedhink** [comment]
Got it. That makes sense. Closing the issue.
