### ISSUE TITLE
Position of Checkbox when custom children are passed as label

### ISSUE THREAD

**Issue by CalvinChiramal** [bigbinary/neeto-ui#2091]
With the neetoUI checkbox, we can add custom children which comes up as the label of the checkbox. In such a case, the checkbox is center aligned.
![image](https://github.com/bigbinary/neeto-ui/assets/35304653/433d0397-a85a-4eec-9921-2156bdf6852e)

in `neeto-form-nano`, we were using a custom implementation of the checkbox component, but there the checkbox is aligned to the top.
![image](https://github.com/bigbinary/neeto-ui/assets/35304653/dbfb1232-d37b-483d-b408-7c270da2206c)

To keep the same UI, I had to override the neetoUI checkbox styles with the following:
```css
.neeto-ui-checkbox {
    align-self: flex-start;
    margin-top: 4px;
}
```

Is this something that should be handled inside neetoUI by default, or should we keep the current style?
@praveen-murali-ind _a.

**Comment by praveen-murali-ind** [comment]
@CalvinChiramal The `margin-top` value depends on the font size and line height of the custom children. You can override the default style by adding a custom class. The default alignment works well for all other use cases.
