### ISSUE TITLE
Ability to type in the "time" component 

### ISSUE THREAD

**Issue by neerajsingh0101** [bigbinary/neeto-ui#2105]
https://neerajsingh0101.neetorecord.com/watch/62a7d2bb-b7ba-4f1c-a81e-8740e449197f

**Comment by farhanlatheef** [comment]
@neerajsingh0101  @josephmathew900  https://farhan-ck.neetorecord.com/watch/b02d3c21-0d0d-485e-91e0-4268366cec9e

**Comment by neerajsingh0101** [comment]
@farhanlatheef https://neerajsingh0101.neetorecord.com/watch/86bf15c7-15ce-4014-bb5a-79effe8c1aee
