### ISSUE TITLE
Date picker not able to handle "enter" event

### ISSUE THREAD

**Issue by sreehari2003** [bigbinary/neeto-ui#2118]
https://sreehari-jayaraj.neetorecord.com/watch/e580e894-2817-4da3-87fd-1acf3cd25cb9

**Comment by farhanlatheef** [comment]
@farhanlatheef _a

**Comment by sreehari2003** [comment]
Closing the issue: The calendar accepts a date in MM/DD/YYYY format, whereas I was using the DD/MM/YYYY format.
