### ISSUE TITLE
Issue with datepicker after antd version upgrade

### ISSUE THREAD

**Issue by lakshyakanungo** [bigbinary/neeto-ui#2129]
https://lakshya.neetorecord.com/watch/ccdd0c1e-a6f5-430f-8914-e6731846a5f8

The Datepicker functionality is not working in Neeto-planner.
Please look into this @farhanlatheef 

cc: @yedhink

**Comment by sumanranjanpanda** [comment]
priority _t

**Comment by farhanlatheef** [comment]
@abilash-sajeev _a Please debug this issue further https://github.com/bigbinary/neeto-form-web/issues/9950 and see if we can apply fix there itself. If we have to downgrade we will loose the min and max date feature.

**Comment by abilash-sajeev** [comment]
@farhanlatheef _a I will fix this issue at the nano level.

**Comment by farhanlatheef** [comment]
Both reported issues can be fixed at the product/nano side. closing this for now.
