### ISSUE TITLE
Add data-cy to `InputContainer`

### ISSUE THREAD

**Issue by Prasannams97** [bigbinary/neeto-ui#2169]
- InputContainer: [class="neeto-ui-input neeto-ui-input--medium"]

<img width="1440" alt="Screenshot 2024-04-04 at 4 40 18 PM" src="https://github.com/bigbinary/neeto-molecules/assets/75472228/b8b5a61d-274b-4b78-ab78-ff60fa2ed4ee">

**Comment by Prasannams97** [comment]
@ajmaln _a

**Comment by josephmathew900** [comment]
@Prasannams97 _a Since this is a small change, could you please raise a PR for it?

**Comment by josephmathew900** [comment]
@Prasannams97 this issue was opened 2 months back and it's a small change, but the issue is still not closed. Is there any blocker here?

**Comment by Prasannams97** [comment]
@josephmathew900 _a Could not find the exact component to add `data-cy` please assign it to someone.
