### ISSUE TITLE
Bug editing time in DatePicker

### ISSUE THREAD

**Issue by jagannathBhat** [bigbinary/neeto-ui#2170]
Related to bigbinary/neeto-kb-web#6054

[How to reporduce](https://neeto-engineering.neetoreplay.net/replay/a8aa61c7-7c54-41b4-a63d-8f1485a5a1c1)

**Comment by josephmathew900** [comment]
@gaagul _a

**Comment by gaagul** [comment]
The issue is being closed as it is no longer reproducible.
