### ISSUE TITLE
Build the `Progress` component

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-ui#2172]
Refer the [ProgressBar](https://github.com/bigbinary/neeto-form-web/blob/e0e544b632d387a32ae5463084c2e3ebc4a99943/app/javascript/src/components/commons/ProgressBar.jsx) component from neetoForm.

- `progressValue` should be optional. If not provided, it should be equal to `progressPercentage%`.
---

**Rollout**

- [ ] neetoForm - export submissions
- [ ] neetoQuiz - export submissions
- [ ] neeto-image-uploader-nano
- [ ] neeto-editor
- [ ] -- check for file upload implementations --

---

engineer-needed _t

**Comment by josephmathew900** [comment]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@gaagul _a As discussed, could you please take this up? You can assign the PR to UI team for UI polishing.

cc: @josephmathew900
