### ISSUE TITLE
Scrollbar always showing in tables

### ISSUE THREAD

**Issue by melvinthomasdev** [bigbinary/neeto-ui#2174]
Ref: https://melvinthomasdev.neetorecord.com/watch/90c69ebc-ed18-4f5a-ad5a-24cb0edbfa43

The ideal behavior in my opinion, is to show the scroll region only when we need to scroll

PS: I think this was added to an update on antd. When I upgraded the antd version in another project, I faced the same issue.

bug _t

**Comment by josephmathew900** [comment]
@praveen-murali-ind _a Please check this.

**Comment by praveen-murali-ind** [comment]
If we override the default table scroll behaviour, it will affect the Table column width. We had faced that issue before. Let’s wait for the proper solution from antd. Closing this issue.
