### ISSUE TITLE
Check the feasibility of showing the color palette above the picker in the ColorPicker

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#2184]
<img width="250" alt="Screenshot 2024-05-08 at 5 35 46 PM" src="https://github.com/bigbinary/neeto-ui/assets/48869249/3acfef0c-ce7c-4339-85be-d8f184eafd30">

@deepakjosp _a

**Comment by josephmathew900** [comment]
@navaneethsdk _a
