### ISSUE TITLE
Fix ColorPicker's `onChange` handler type

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#2188]
https://github.com/bigbinary/neeto-ui/blob/25ca66f38cf8db317ba93620fda79acee03f28e5/types/ColorPicker.d.ts#L4-L18

Currently argument type is set to `string` but it returns an object:

<img width="342" alt="image" src="https://github.com/bigbinary/neeto-ui/assets/22348659/29de4916-a806-4a9b-9012-e306a263c6b5">

cc: @josephmathew900

**Comment by josephmathew900** [comment]
@gaagul _a
