### ISSUE TITLE
Multiple API requests on pressing Enter key multiple times

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/neeto-ui#2200]
Pressing the Enter key multiple times in an input field leads to multiple API requests being fired, causing unintended duplicate submissions. 

https://github.com/bigbinary/neeto-ui/assets/35305344/6119df9a-c9a5-474c-a50f-ad74d9e3366b

cc: @josephmathew900

**Comment by josephmathew900** [comment]
@navaneethsdk _a
