### ISSUE TITLE
Enhancements for MultiEmailInput component

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#2218]
https://yedhin.neetorecord.com/watch/d661f51b-8d28-4533-94ec-b8b98be460c5

https://github.com/bigbinary/neeto-ui/blob/5a9a8d7f55c0be1b572890607b4de0f996062921/src/components/MultiEmailInput/index.jsx#L98

@farhanlatheef _a Please take this up.

cc: @subins2000

**Comment by josephmathew900** [comment]
@josephmathew900 _a
