### ISSUE TITLE
Add support for displaying tooltips for disabled buttons in NoData component

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/neeto-ui#2240]
We are updating `neeto-form-nano` to use the `NoData` component from `NeetoUI`. We need to display a tooltip message when the primary button is disabled. Please add support for displaying the tooltip message for disabled buttons.

<img width="1440" alt="NoData page in form-nano" src="https://github.com/bigbinary/neeto-ui/assets/35305344/82918cf5-8101-412d-943e-8def2f28188a">

**Comment by josephmathew900** [comment]
@gaagul _a
