### ISSUE TITLE
404 Page when clicking an URL present in the documentation

### ISSUE THREAD

**Issue by aashishpsaini** [bigbinary/neeto-ui#2247]
In the [readme](https://github.com/bigbinary/neeto-ui?tab=readme-ov-file#readme) section, we have a [link](https://github.com/bigbinary/neeto-ui/tree/main/src/components/formik) under text `formik folder` to open Formik components, currently its broken and returns a 404. It needs to be fixed.

**Comment by josephmathew900** [comment]
@josephmathew900 _a

**Comment by josephmathew900** [comment]
@aashishpsaini For these kinds of minor issues, you can raise a PR directly. You don't need to wait for the UI team to pick it up.
