### ISSUE TITLE
Create a playground for NeetoUI in the storybook

### ISSUE THREAD

**Issue by josephmathew900** [bigbinary/neeto-ui#2253]
Create a playground for NeetoUI in the storybook using the storybook live examples plugin

Plugin: https://storybook.js.org/addons/storybook-addon-live-examples

NeetoEditor sandbox implementation: https://github.com/bigbinary/neeto-editor/pull/1179

**Comment by josephmathew900** [comment]
@deepakjosp _a

**Comment by deepakjosp** [comment]
@josephmathew900  we were planning to use `storybook-addons-live-exmple` plugin which would have required refactoring almost all the stories that we have in the storybook. The addon has a few compatibility issues with features like args table that we extensively use in the storybook. Hence we decided to try out an alternative approach which has comparatively lesser effort. Hence reducing the ETA to 0.5D _t.
