### ISSUE TITLE
Menubar.Item views are fluctuating 

### ISSUE THREAD

**Issue by kpssachin** [bigbinary/neeto-ui#226]
In the chat application the tags are fluctuating on mouse hover. https://github.com/bigbinary/neeto-chat-web/issues/356 .

**Comment by kpssachin** [comment]
@goutham-subramanyam _a Unable to verify the changes in the MenuBar.Item. Please help me to verify that.

**Comment by goutham-subramanyam** [comment]
@kpssachin I have fixed the issue.
