### ISSUE TITLE
Issues due to transition delay in closing alerts

### ISSUE THREAD

**Issue by abilash-sajeev** [bigbinary/neeto-ui#2289]
https://abilash-sajeev.neetorecord.com/watch/b2461567-b907-40cc-87ce-aa97f479866a

cc: @praveen-murali-ind

**Comment by josephmathew900** [comment]
@deepakjosp _a https://joseph-mathew.neetorecord.com/watch/f9945dc8-b4d2-4525-829c-39e0828ae35e
