### ISSUE TITLE
[Formik][Input] The touched properties are not correct

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#23]
https://github.com/bigbinary/neeto-ui/blob/60bcbe3372b78dfb0b178c987a5a9c581486f88a/lib/components/formik/Input.js#L10

@vinay0x 
@edwinbbu 

From my understanding, `touched` consists of all the `values` associated in Formik. 

If we need to check either one of the fields/values is touched or not, we need change it to the following:-
```js
  <Input error={meta.touched && meta.error} {...rest} {...field} />
```

Currently all fields under show error popup/message when touched either one of them.

**Comment by vinay0x** [comment]
I'll check this @vinay0x _a

**Comment by vinay0x** [comment]
It was built for each field initially. Need to check what changed.

**Comment by yedhink** [comment]
We could just use `meta` for accessing properties or state associated with the particular field we are dealing with, from my understanding of Formik.

The change is pretty simple I believe. But I don't know how many components would have to be reflected with the same kinds of changes.

Eg of another change that can be made:
https://github.com/bigbinary/neeto-ui/blob/60bcbe3372b78dfb0b178c987a5a9c581486f88a/lib/components/formik/Switch.js#L12

```js
          error={meta.error}
```

**Comment by vinay0x** [comment]
https://github.com/bigbinary/neeto-ui/blob/60bcbe3372b78dfb0b178c987a5a9c581486f88a/lib/components/formik/Switch.js#L12
There is some reason why this change was made. Some corner case.
