### ISSUE TITLE
Rollout the ProgressBar component

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-ui#2323]
Ref: https://neeto-ui.neeto.com/?path=/docs/components-progressbar--docs

The ProgressBar component will be used in file upload and image upload implementations. This component was extracted to NeetoUI from NeetoForm.

- [x] ~NeetoForm~
- [x] NeetoReplay
- [x] ~NeetoEditor~
- [x] NeetoImageUploaderNano
- [x] Delete the [ProgressBar.jsx](https://github.com/bigbinary/neeto-form-web/blob/main/app/javascript/src/components/commons/ProgressBar.jsx) file from the NeetoForm. [[ref]](https://bigbinary.slack.com/archives/C03EKGPU6UT/p1727959406004439?thread_ts=1727957223.752419&cid=C03EKGPU6UT)

@yashjais _a

<img width="216" alt="Screenshot 2024-10-03 at 8 23 12 PM" src="https://github.com/user-attachments/assets/f5d0d728-2e49-4d89-8c3c-3d0272106f15">

**Comment by yashjais** [comment]
@AbhayVAshokan _a
Opened up the PR's in respective repos.
- [NeetForm](https://github.com/bigbinary/neeto-form-web/pull/11671)
- [NeetoReplay](https://github.com/bigbinary/neeto-replay-web/pull/4554)
- [NeetImageUploaderNano](https://github.com/bigbinary/neeto-image-uploader-nano/pull/707)

**Comment by AbhayVAshokan** [comment]
Closing the epic since all the subissues are merged.
