### ISSUE TITLE
Add support for stacked tabs 

### ISSUE THREAD

**Issue by dineshpanda** [bigbinary/neeto-ui#233]
Currently, `Tab` component shows items in a row.
It would be useful if `Tab` component can be configured (using props say `stacked`) to show items in a column.

**Comment by edwinbbu** [comment]
@goutham-subramanyam _a

**Comment by goutham-subramanyam** [comment]
@dineshpanda Can you show me a use case so I can get a better idea?

**Comment by dineshpanda** [comment]
@goutham-subramanyam In AceInvoice, we need both tabs spreading horizontally as well vertically.
Right now, by default tabs appear horizontally. I think it would be useful to support vertical tabs as well ?
 

![stacked_tab](https://user-images.githubusercontent.com/10043667/116745913-6a582d00-aa19-11eb-9b68-fa2f72a57050.png)

**Comment by goutham-subramanyam** [comment]
@dineshpanda For vertical navigation, we usually use the following UI instead of Tabs:

<img width="827" alt="Screenshot 2021-05-03 at 11 00 18 PM" src="https://user-images.githubusercontent.com/24496302/116910526-60c20580-ac63-11eb-94f6-774386262bfe.png">

**Comment by dineshpanda** [comment]
@goutham-subramanyam Okay, will follow this design. Thanks
