### ISSUE TITLE
Formik - Input component of type date

### ISSUE THREAD

**Issue by rishavkr08** [bigbinary/neeto-ui#236]
In lib/components/formiks - 
`Input` component of type - date works fine in `chrome` but didn't worked in `safari`.

**Comment by edwinbbu** [comment]
@rishavkr08 _a You can give it a try.

**Comment by edwinbbu** [comment]
@amaldinesh7 _a Can you take a look

**Comment by amaldinesh7** [comment]
It is working fine in safari.
<img width="1440" alt="Screenshot 2021-07-19 at 12 20 34 PM" src="https://user-images.githubusercontent.com/33386004/126115468-fa9d0dd9-0234-4683-9689-e2ce674d2c76.png">
I am closing this issue @edwinbbu @rishavkr08
