### ISSUE TITLE
Icon classname and other props not reflected to the toastr icon

### ISSUE THREAD

**Issue by deepanshu-rajput-git** [bigbinary/neeto-ui#2379]
Ref: https://deepanshu-bigbinary.neetorecord.com/watch/6d687768-a417-407a-9d3d-1e0bfd406697

@praveen-murali-ind _a
Please take a look at the issue.

**Comment by praveen-murali-ind** [comment]
@deepakjosp _a I have fixed the class name typo in the icon. The icon shown in the second image is added by React Toastify by default. Could you please work on disabling the default icons as we discussed during the call?

<img width="366" alt="Screenshot 2024-11-27 at 10 07 05 AM" src="https://github.com/user-attachments/assets/733a9071-fa45-49d9-b7ae-403177686879">
<img width="359" alt="Screenshot 2024-11-27 at 10 05 50 AM" src="https://github.com/user-attachments/assets/1679b620-49a9-4db6-8d8d-8a7587dbfb1f">
