### ISSUE TITLE
404 page not found toastr shown on each page load

### ISSUE THREAD

**Issue by deepanshu-rajput-git** [bigbinary/neeto-ui#2389]
Ref: https://deepanshu-bigbinary.neetorecord.com/watch/70bbabdb-16fa-4793-a95a-ae0d577114aa

@praveen-murali-ind _a, Please take a look at the issue.
bug _t
caught-by-playwright _t
priority _t

**Comment by praveen-murali-ind** [comment]
@deepakjosp _a

**Comment by deepakjosp** [comment]
@deepanshu-rajput-git the issue is not reproducible in staging or development. Could you please provide the steps to reproduce.

**Comment by deepanshu-rajput-git** [comment]
@deepakjosp: I got this error during signup but cannot reproduce it now.

**Comment by deepakjosp** [comment]
@deepanshu-rajput-git _a it will probably be an issue within NeetoCal. Could you please assign this to someone from the team?

**Comment by deepanshu-rajput-git** [comment]
@sayoojtmc _a, can you please take a look?

**Comment by sayoojtmc** [comment]
Tried creating a new org in staging, couldn't reproduce this. Closing for now.
