### ISSUE TITLE
Display color palette by default in ColorPicker

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#2397]
Action item

- Update the color picker to display the color palette by default, using the color scheme provided in the attached Figma design.

[Figma](https://www.figma.com/design/iZqd7a5oh42RCdk9qZ2eXe/UI?node-id=872-379&t=7Zb1bG7A7Px4ppMf-4)

@josephmathew900 _a Could you please assign someone to work on it.

cc @deepakjosp

**Comment by deepakjosp** [comment]
@deepakjosp _a
