### ISSUE TITLE
Unable to enter anything inside Input Component

### ISSUE THREAD

**Issue by Harshit-frontend** [bigbinary/neeto-ui#241]
Attaching a video link of the issue for reference.

https://www.loom.com/share/3ae5e702637743f5987b05b46ebea446

**Comment by edwinbbu** [comment]
@Harshit-frontend NeetoUI changelog is a documentation site and is currently not a platform to try it out. 
NeetoUI repo itself can be tried out in development mode.

**Comment by Harshit-frontend** [comment]
@edwinbbu  Thanks for the info.
