### ISSUE TITLE
Display full text for tabs

### ISSUE THREAD

**Issue by amaljosea** [bigbinary/neeto-ui#266]
Please refer https://github.com/bigbinary/aceinvoice-web/issues/7555#issuecomment-834237566

**Comment by edwinbbu** [comment]
Seems like duplicate of https://github.com/bigbinary/neeto-ui/issues/233

cc @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
@amaljosea The AceInvoice UI is being updated in the following PR: https://github.com/bigbinary/aceinvoice-web/pull/7620

Closing the issue.
