### ISSUE TITLE
Toastr Component

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#29]
Part of #25 

Logic of toastr component is quite different in case of neetohelp and has to handled carefully.

cc @vinay0x , @yedhink

**Comment by vinay0x** [comment]
Toastr in neetoui should be the better version. This should be handled very carefully since it relies on peerDependencies too. @edwinbbu _a Can you please take this up when you have time?

**Comment by edwinbbu** [comment]
There is no changed required in neetoui toastr component. 
The neetoui toastr needs to be used everywhere in neeto-help and showToastr implemented needs to be removed once migrated. 

showToastr is being replaced with neetoui toastr component by @josephv7 as part of api migrations. (Ref https://github.com/bigbinary/neeto-help-web/issues/9797)

Hence closing the issue and mention the same in the neetohelp.
