### ISSUE TITLE
Add custom button support for the Toastr component.

### ISSUE THREAD

**Issue by mayankagnihotri7** [bigbinary/neeto-ui#296]
There is no support for adding the custom button along with the `Toastr` component.

**Comment by goutham-subramanyam** [comment]
@mayankagnihotri7 _a Can you please explain the use case ?

**Comment by mayankagnihotri7** [comment]
@goutham-subramanyam _a Please refer <a href="https://github.com/bigbinary/neeto-desk-web/pull/10944#discussion_r639627289">comment.</a>
