### ISSUE TITLE
Remove edit icon on selecting the view in menubar

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#299]
<img width="275" alt="Screenshot 2021-05-27 at 11 28 13 AM" src="https://user-images.githubusercontent.com/17916573/119779698-9f578280-bee6-11eb-86fc-f6f59b0484e4.png">

cc @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
@edwinbbu _a Do we need to remove it completely? We can show the icon only on the hover of the badge instead of hovering on the item.

**Comment by edwinbbu** [comment]
@goutham-subramanyam _a, I think it was intended for editing the view out there. But there is no functionality right now. 
We can conditionally render the edit icon based on the prop. So that once the functionality is being added, they just need to pass the props.

**Comment by goutham-subramanyam** [comment]
Okay. I thought the functionality was already there. I will update the behavior as you mentioned 👍🏼
