### ISSUE TITLE
Animation seems to be quite fast for pane and modal

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#325]
https://www.loom.com/share/13080cd58ad049b8a5d687cdef3928d8

@goutham-subramanyam _a

**Comment by goutham-subramanyam** [comment]
@edwinbbu 

1. If we wrap the Pane or Modal with the isOpen conditions, then the animations won't work.
2. The animations are from BlueprintJS and we are not overriding anything in that regard.

Anyway in neetoui 2.0 we'll be using our own custom components for both. So we can make the animations consistent there.

Closing for now.
