### ISSUE TITLE
Table borders are not working properly in brave browser

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#329]
<img width="1736" alt="Screenshot 2021-07-05 at 2 47 53 PM" src="https://user-images.githubusercontent.com/17916573/124448460-1adb0800-dda0-11eb-8cf6-55e3de06c945.png">

Browser specific.

**Comment by edwinbbu** [comment]
@vyshnavrajs2019 _a Can you take a look at this?

**Comment by goutham-subramanyam** [comment]
@edwinbbu _a Not able to reproduce the issue.
