### ISSUE TITLE
[Syncing] Button

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#33]
## Points to note
- Component in action - `Button.js`
- Github Urls to this component:
  * [neeto-ui/Button.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Button.js)
  * [NitroUI/Button.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Button.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Button.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**
- The `useRef` doesn't add any value from my understanding

## Diff
```diff
--- NitroUI/Button.js	2020-11-28 16:54:23.826521600 +0530
+++ neetoui-official/Button.js	2020-11-28 16:49:18.735162200 +0530
@@ -1,4 +1,4 @@
-import React, { useEffect, useRef } from "react";
+import React from "react";
 import classnames from "classnames";
 import { BeatLoader } from "react-spinners";
 import { Link } from "react-router-dom";
@@ -22,17 +22,10 @@
     dataTestId,
     size,
     href,
-    focus,
     ...otherProps
   } = props;
 
   let innerContent = label;
-  const buttonRef = useRef(null);
-  useEffect(() => {
-    if (focus) {
-      buttonRef.current && buttonRef.current.focus();
-    }
-  }, []);
 
   if (icon) {
     if (iconPosition === "right") {
@@ -66,13 +59,12 @@
 
   return (
     <Parent
-      ref={buttonRef}
       to={to}
       href={href}
       onClick={handleClick}
-      type={Parent === "button" ? type : null}
+      type={type}
       className={classnames(
-        [`nh-btn nh-btn--${style || "primary"}`, className],
+        [`nui-btn nui-btn--${style || "primary"}`, className],
         {
           "px-4 py-2": size === "large",
           "w-full justify-center py-2.5": fullWidth,
@@ -91,7 +83,7 @@
 
 const Loader = () => {
   return (
-    <div className="nh-btn--loader">
+    <div className="nui-btn--loader">
       <BeatLoader size={8} />
     </div>
   );
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a Sync is required. `type` prop should be passed with a check. Refer this [PR](https://github.com/bigbinary/neeto-help-web/pull/8388)
