### ISSUE TITLE
[Syncing] Callout

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#34]
## Points to note
- Component in action - `Callout.js`
- Github Urls to this component:
  * [neeto-ui/Callout.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Callout.js)
  * [NitroUI/Callout.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Callout.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Callout.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/Callout.js	2020-11-28 16:54:23.839930700 +0530
+++ neetoui-official/Callout.js	2020-11-28 16:49:18.735340300 +0530
@@ -13,18 +13,16 @@
   danger: "ri-spam-fill"
 };
 
-const Callout = ({ icon, style = "info", children, className }) => {
+const Callout = ({ icon, showIcon, style = "info", children, className }) => {
   const baseClasses = calloutStyles[style];
   return (
     <div
       className={classnames(["rounded-md p-4 text-sm", baseClasses, className])}
     >
       <div className="flex flex-row items-start justify-start">
-        {icon && (
           <div className="flex flex-row items-start justify-center flex-shrink-0 mr-3 text-lg">
             <i className={icon || calloutIcons[style]} />
           </div>
-        )}
         <div>{children}</div>
       </div>
     </div>
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a

1. `showIcon` prop can be removed.
2. `icon &&` check is needed, else there will be a margin of `mr-3` unnecessarily.
