### ISSUE TITLE
Double the timeout for Error toastrs

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/neeto-ui#350]
Neeraj suggested that we should double the time the error toastrs are visible. Something like this in the file `lib/components/Toastr.js`:

```javascript
const showErrorToastr = (errorObject, buttonLabel, onClick) => {
  let errorMessage;
  if (isError(errorObject)) errorMessage = errorObject.message;
  else if (errorObject.error) errorMessage = errorObject.error;
  else if (errorObject.errors) errorMessage = R.join("\n", errorObject.errors);
  else errorMessage = "Something went wrong.";
  toast.error(<ToastrComponent type="error" message={errorMessage} buttonLabel={buttonLabel} onClick={onClick} />, {
    position: toast.POSITION.BOTTOM_CENTER,
    transition: Slide,
    autoClose: 5000, // This line should be added here
  });
};
```

@edwinbbu Please upvote this comment if the above code looks good. Will issue a PR for the same.

**Comment by amaldinesh7** [comment]
One way of calculating the time period of the toaster is 50ms multiplied by the length of the error message, and we should set a minimum time of 2000 or 3000, and we can have a maximum threshold of 7000 or something. Setting it to 5000 will also work fine, but just a suggestion. @ghousemohamed @edwinbbu

**Comment by edwinbbu** [comment]
@ghousemohamed Code looks good. 5000ms is the duration in the `react-toastify` site as well. 
I would like to know what is the current duration provided. It looks like 5000ms is the default duration.
