### ISSUE TITLE
Add data-cy selector attribute in Toastr close button

### ISSUE THREAD

**Issue by Vishal24367** [bigbinary/neeto-ui#364]
1. Toast message close button. For all the toast messages close buttons include the error toast messages, the data-cy name would be "toast-message-close-button".

![toastr](https://user-images.githubusercontent.com/33788287/126991552-0076a6c3-a6af-4be2-aaa6-fbc2535537fb.png)
![toastr2](https://user-images.githubusercontent.com/33788287/126991581-f25a3a86-11ca-459d-826d-747a86655d75.png)

**Comment by amaldinesh7** [comment]
@Vishal24367 

Since `toastr` is not our custom component, there is some difficulty in adding data-cy props for the close button. We will get this fixed in neetoUI v2. 

There is a data-cy prop added for the whole toaster component, if that suits your use case, you can make use of that.

**Comment by Vishal24367** [comment]
@amaldinesh7 Please look into this.

**Comment by edwinbbu** [comment]
Closing the issue since we are freezing the changes in v1.
