### ISSUE TITLE
[Syncing] DateInput

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#38]
## Points to note
- Component in action - `DateInput.js`
- Github Urls to this component:
  * [neeto-ui/DateInput.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/DateInput.js)
  * [NitroUI/DateInput.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/DateInput.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `DateInput.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/DateInput.js	2020-11-28 16:54:23.892121600 +0530
+++ neetoui-official/DateInput.js	2020-11-28 16:49:18.735944700 +0530
@@ -48,8 +48,8 @@
           ref={ref}
           minDate={minDate}
           maxDate={maxDate}
-          formatDate={date => moment(date).format(DATE_FORMAT)}
-          parseDate={inputStr =>
+          formatDate={(date) => moment(date).format(DATE_FORMAT)}
+          parseDate={(inputStr) =>
             inputStr
               ? moment(inputStr, DATE_FORMAT, true).isValid()
                 ? moment(inputStr, DATE_FORMAT, true)
```

**Comment by edwinbbu** [comment]
Closing the issue since there is no file diff. Only lint changes.
