### ISSUE TITLE
[Syncing] DateRangeInput

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#39]
## Points to note
- Component in action - `DateRangeInput.js`
- Github Urls to this component:
  * [neeto-ui/DateRangeInput.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/DateRangeInput.js)
  * [NitroUI/DateRangeInput.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/DateRangeInput.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `DateRangeInput.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**
- I'm not sure about the use case of `allowSingleDayRange={true}`.

## Diff
```diff
--- NitroUI/DateRangeInput.js	2020-11-28 16:54:23.897920900 +0530
+++ neetoui-official/DateRangeInput.js	2020-11-28 16:49:18.736107300 +0530
@@ -27,7 +27,12 @@
     ref
   ) => {
     return (
-      <div className={classnames(["nh-date-range--input", className])}>
+      <div
+        className={classnames([
+          "flex flex-col items-start justify-start",
+          className
+        ])}
+      >
         {label && (
           <Label
             label={label}
@@ -41,11 +46,10 @@
         )}
         <Input
           ref={ref}
-          allowSingleDayRange={true}
           minDate={minDate}
           maxDate={maxDate}
-          formatDate={date => moment(date).format(DATE_FORMAT)}
-          parseDate={inputStr =>
+          formatDate={(date) => moment(date).format(DATE_FORMAT)}
+          parseDate={(inputStr) =>
             inputStr
               ? moment(inputStr, DATE_FORMAT, true).isValid()
                 ? moment(inputStr, DATE_FORMAT, true)
```

**Comment by edwinbbu** [comment]
Sync required. `allowSingleDayRange={true}` needs to be added.
