### ISSUE TITLE
Add tags to v2 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#402]
<img width="1036" alt="Screenshot 2021-08-05 at 9 25 39 AM" src="https://user-images.githubusercontent.com/17916573/128289468-836596b5-b21b-43fa-91b3-f4326574fc9e.png">

**Comment by edwinbbu** [comment]
@akkshaylawrence _a

**Comment by akkshaylawrence** [comment]
@edwinbbu can you provide links to this design.

**Comment by edwinbbu** [comment]
@akkshaylawrence https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=0%3A1
