### ISSUE TITLE
[Syncing] Input

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#41]
## Points to note
- Component in action - `Input.js`
- Github Urls to this component:
  * [neeto-ui/Input.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Input.js)
  * [NitroUI/Input.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Input.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Input.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**
- `nakedInput` is named as `naked` in neetoui. But i'm not sure what exactly it's used for. What exactly does prefixing with `naked` mean from `className` perspective? 

## Diff
```diff
--- NitroUI/Input.js	2020-11-28 16:54:23.974302100 +0530
+++ neetoui-official/Input.js	2020-11-28 16:49:18.736973600 +0530
@@ -1,10 +1,10 @@
-import React from "react";
+import React, { Component } from "react";
 import classnames from "classnames";
 import Label from "./Label";
 
-const Input = React.forwardRef(
-  (
-    {
+class Input extends Component {
+  render() {
+    const {
       size,
       type,
       label,
@@ -16,21 +16,20 @@
       helpText,
       onChange,
       className,
+      inputClassName,
+      naked,
       maxLength,
       labelProps,
-      nakedInput,
       dataTestId,
-      contentSize,
       placeholder,
       leadingIcon,
       required = false,
       hideCharacterCount,
       ...otherProps
-    },
-    ref
-  ) => {
+    } = this.props;
+
     const baseClasses =
-      "form-input block w-full text-sm flex flex-row justify-start items-center transition-all duration-200";
+      "form-input block w-full sm:text-sm sm:leading-5 flex flex-row justify-start items-center transition-all duration-200";
     const errorClasses =
       "border-red-400 text-red-800 placeholder-red-300 focus-within:shadow-focus-red";
 
@@ -44,7 +43,7 @@
     return (
       <div
         className={classnames([
-          "flex flex-col items-start justify-start flex-grow",
+          "flex flex-col items-start justify-start",
           className
         ])}
       >
@@ -62,11 +61,7 @@
             {label}
           </Label>
         )}
-        <div
-          className={classnames(["relative w-full rounded-md"], {
-            "shadow-sm": !nakedInput
-          })}
-        >
+        <div className={classnames("relative w-full rounded-md", { "shadow-sm": !naked, "border-none": naked })}>
           {leadingIcon && (
             <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
               <i className={leadingIcon}></i>
@@ -74,42 +69,39 @@
           )}
           <div
             className={classnames(baseClasses, {
-              "focus-within:shadow-focus-purple focus-within:border-purple-400":
-                !inputError && !nakedInput,
-              [errorClasses]: !!inputError,
+              "focus-within:shadow-focus-purple focus-within:border-purple-400": !inputError && !naked,
+              [errorClasses]: !!inputError && !naked,
+              "border-none": naked,
               "bg-gray-50 cursor-not-allowed": disabled,
               "pr-10": !suffix && !!inputError,
               "pl-10": leadingIcon,
-              "py-1.5": size === "small",
-              "border-none px-0": nakedInput
+              "py-1.5": size === "small"
             })}
           >
             {prefix && (
               <div className="flex items-center pr-1">
-                <span className="flex flex-row items-center justify-start text-gray-500">
+                <span className="text-gray-500 sm:text-sm sm:leading-5">
                   {prefix}
                 </span>
               </div>
             )}
             <input
-              ref={ref}
               onChange={onChange}
-              value={value ?? ""}
+              value={value || ""}
               type={type}
               placeholder={placeholder}
               className={classnames(
-                ["w-full focus:outline-none bg-transparent"],
+                ["w-full focus:outline-none bg-transparent", inputClassName],
                 { "cursor-not-allowed": disabled }
               )}
               disabled={disabled}
               data-test-id={dataTestId}
               maxLength={maxLength}
-              size={contentSize}
               {...otherProps}
             />
             {suffix && (
               <div className="flex items-center pl-1">
-                <span className="flex flex-row items-center justify-start text-gray-500">
+                <span className="text-gray-500 sm:text-sm sm:leading-5">
                   {suffix}
                 </span>
               </div>
@@ -123,7 +115,7 @@
       </div>
     );
   }
-);
+}
 
 const ErrorSVG = () => (
   <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none fadeIn">
```

**Comment by yedhink** [comment]
@edwinbbu

Would you be able to clarify what prefixing with `naked` for attributes mean? Thanks.

**Comment by edwinbbu** [comment]
@yedhink `naked` attribute signifies that the input don't need border.
We should be using `nakedInput` instead of `naked`. 

@goutham-subramanyam Please provide more clarifications as required.

**Comment by goutham-subramanyam** [comment]
@yedhink Syncing is required. Input.js from NitroHelp should be copied to neeto-ui. The prop name can be `naked` or `nakedInput`
If we are changing it to `naked`, we need to update instances in NitroHelp.

**Comment by yedhink** [comment]
@goutham-subramanyam Can you clarify what exactly are the additions in NitroHelp `Input.js` from the one in neeto-ui `Input.js`?

From my understanding, there are only few naming differences and passing `ref` in props. Other than that I don't see any enhancements/removal in the code.

Naming changes that I see:
- `naked` to `nakedInput`
- `maxLength` to `size`
etc

Also had a question regarding the usage of `forwardRef` in NitroHelp Input.js:
```js
-const Input = React.forwardRef(
-  (
-    {
```
I understand this was used since we are passing a `ref`. I see that in the `NitroHelp` components at a lot of places we have passed in a `ref`. Is is necessary to persist the same in `neeto-ui`? Meaning do we need the `ref` logic in all these components in `neeto-ui` too? What all will be disadvantages/caveats if leave the `ref`? 

Just trying to learn the best practices. Let me know your thoughts.

**Comment by goutham-subramanyam** [comment]
@yedhink 

1. MaxLength & contentSize is different. `contentSize` is used for settings `size` attribute for input. ([Ref](https://www.w3schools.com/tags/att_input_size.asp))
2. I have removed unwanted classes in NitroHelp Input.js. So that needs to be updated in neeto-ui as well
3. We need ref for settings focus manually (when autoFocus won't do the trick)
4. We can keep the inputClassname prop

**Comment by goutham-subramanyam** [comment]
Also `value={value || ""}` was updated to `value={value ?? ""}` by @danedavid since the former didn't allow entering value `0`
