### ISSUE TITLE
Add Tooltip component [v2]

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#416]
Move away from the blueprint.

**Comment by edwinbbu** [comment]
@amaldinesh7 _a

**Comment by amaldinesh7** [comment]
@praveen-murali-ind _a. Please make the styling changes.

**Comment by edwinbbu** [comment]
@amaldinesh7 Can you provide the branch you have worked on.

**Comment by amaldinesh7** [comment]
`416-add-tooltip-component` @edwinbbu

**Comment by praveen-murali-ind** [comment]
@edwinbbu Applied the tooltip styles. Could you please review.

**Comment by edwinbbu** [comment]
> @edwinbbu Applied the tooltip styles. Could you please review.

Please raise a PR for the same.
