### ISSUE TITLE
Errors not shown when trying to submit form without touching any inputs

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/neeto-ui#423]
This line:
https://github.com/bigbinary/neeto-ui/blob/94ad50717fb9748bd51e7aa6514594d6218397fb/lib/components/formik/Input.js#L10

should be changed to this:
```js
<Input {...field} error={(meta.isSubmitting || meta.touched) && meta.error} {...rest} />
```

**Comment by edwinbbu** [comment]
Please disable the submit button when the user didn't touch any of the input field. 
Closing the issue. We have build v2 of neetoui and no more updates are to be provided for v1.
