### ISSUE TITLE
Make `Toastr` component's `error` handler much more consistent

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#429]
Refer: https://github.com/bigbinary/wheel/pull/589#issuecomment-905167224

**The following comments should be read after going through above linked comment. Then only proper context would be set.**

Let's take the case of these two conditions  which are currently:

```js
else if (errorObject.error) errorMessage = errorObject.error;
else if (errorObject.errors) errorMessage = R.join("\n", errorObject.errors);
```

>  This condition is provided because there are someplace where the error is sent as an array and in some places as a string from the backend.
There are also places where the error is sent as { message: errorMessage } as well { error: errorMessage } from the backend in multiple projects. If there is a uniform pattern, then we can reduce the logic lot more.

Let's talk a bit more about the above mentioned conditions and the mentioned reason for having such a condition.

-  If from Rails side we send back `{error: "msg"}` or `{errors: ["msg1", "msg2"]}`, then it can only be accessed via the Axios response object. Because it's the result of an API call.
- Let's say that we send back `{error: "msg"}`.
- With the current logic, we'd have to invoke the Toastr like either of the following:

```js
Toastr.error(axiosResponse.data)

or 

Toastr.error({error: axiosResponse.data.error});
```

And both the ways I have shown above are not really good patterns to be followed in my opinion. Reasons:
- In the first invocation we are sending `axiosResponse.data`, where `data` may contain details more than just the error details, to a method that expects an `errorObject`.
- In the second invocation we are creating a custom object with an `error` key just for the sake of satisfying a condition within the component. Passing a key named `error` to a chained method which is already named `error` as in `Toastr.error` is very redundant and unintuitive in my opinion.

So as mentioned in the parent comment. What I'd propose is accepting Axios responses as argument, then pick an error message from the response automatically(either `error` or `errors`) and display it and also accept strings as arguments. 

>There are also places where the error is sent as { message: errorMessage }

This is something that should be corrected. Errors should be sent back in the `{ error: "msg" }` or `{ errors: [] }` format from the Rails side.

**Comment by edwinbbu** [comment]
@ajmaln _a Can you take a look
