### ISSUE TITLE
[Syncing] Modal

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#43]
## Points to note
- Component in action - `Modal.js`
- Github Urls to this component:
  * [neeto-ui/Modal.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Modal.js)
  * [NitroUI/Modal.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Modal.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Modal.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/Modal.js	2020-11-28 16:54:23.994894100 +0530
+++ neetoui-official/Modal.js	2020-11-28 16:49:18.746378900 +0530
@@ -23,16 +23,16 @@
         onClose={onClose}
         className={classnames(
           [
-            "relative bg-white rounded-lg overflow-hidden shadow-xl nh-modal--wrapper",
+            "relative bg-white rounded-lg overflow-hidden shadow-xl nui-modal--wrapper",
             className
           ],
           {
-            "nh-modal--wrapper__sm": size === "small",
-            "nh-modal--wrapper__md": size === "medium",
-            "nh-modal--wrapper__lg": size === "large",
-            "nh-modal--wrapper__footer": showFooter,
-            "nh-modal--auto-height": autoHeight,
-            "nh-modal--auto-width": autoWidth
+            "nui-modal--wrapper__sm": size === "small",
+            "nui-modal--wrapper__md": size === "medium",
+            "nui-modal--wrapper__lg": size === "large",
+            "nui-modal--wrapper__footer": showFooter,
+            "nui-modal--auto-height": autoHeight,
+            "nui-modal--auto-width": autoWidth
           }
         )}
         {...otherProps}
```

**Comment by edwinbbu** [comment]
Closing the issue since there are no significant file diff.
