### ISSUE TITLE
Fix URL in the npmjs.com page

### ISSUE THREAD

**Issue by jagannathBhat** [bigbinary/neeto-ui#434]
The [page](https://www.npmjs.com/package/@bigbinary/neetoui) currently displays the wrong URL to the neetoUI website in the **Homepage** section.

**Comment by edwinbbu** [comment]
@jagannathBhat Could you specify exactly where the issue is?

**Comment by JaganKaartik** [comment]
![Screenshot 2021-09-02 at 10 22 09 PM](https://user-images.githubusercontent.com/20874468/131885341-59db24f3-fb47-4baa-b467-bad5ecda8c04.png)

It's currently `neeto-ui.netlify.app` instead of `neetoui.netlify.app`
