### ISSUE TITLE
[Syncing] PageLoader

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#44]
## Points to note
- Component in action - `PageLoader.js`
- Github Urls to this component:
  * [neeto-ui/PageLoader.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/PageLoader.js)
  * [NitroUI/PageLoader.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/PageLoader.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `PageLoader.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/PageLoader.js	2020-11-28 16:54:23.996346400 +0530
+++ neetoui-official/PageLoader.js	2020-11-28 16:49:18.748010500 +0530
@@ -5,7 +5,7 @@
   return (
     <div className="relative w-full h-full">
       <div className="absolute top-0 left-0 flex flex-row items-center justify-center w-full h-full">
-        <BeatLoader size={16} color={"#252f3f"} />
+        <BeatLoader size={16} color={"#5469D4"} />
       </div>
     </div>
   );
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a The color was tweaked by @vinay0x. That needs to be updated.

**Comment by vinay0x** [comment]
Yeah. Use the new dark color instead of purple.
