### ISSUE TITLE
Toastr component has bugs when react-toastify is upgraded to latest version

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#441]
@edwinbbu @karthiknmenon 

This is a priority issue in my opinion since it has the potential to affect neeto products and client products that uses neeto-ui.

We should upgrade `react-toastify` to latest version in neetoUI. Updating to latest version would also mean we should update the logic in `Toastr` component.

There is a bug when updating `react-toastify` to the latest version. I'm able to replicate this in neeto products too.

To understand the error please go through this issue: 
https://github.com/bigbinary/bigbinary-website/issues/1459

**Comment by yedhink** [comment]
React Toastify version should be upgraded to be at least 8.0.2 or greater.

**Comment by karthiknmenon** [comment]
@karthiknmenon _a

Taking this up with the current neetoUI-v2 update. 

cc: @edwinbbu
