### ISSUE TITLE
Add Typography component [v2]

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#446]
@praveen-murali-ind _a

<img width="720" alt="Screenshot 2021-09-09 at 2 34 45 PM" src="https://user-images.githubusercontent.com/48869249/132657880-defec1a5-e731-4974-a0be-83c462002049.png">

**Comment by edwinbbu** [comment]
Let's have a component `Typography` which can have type prop `heading`, `title`, `subtitle`, `description`.

Ref: https://ant.design/components/typography, https://material-ui.com/components/typography/
