### ISSUE TITLE
Add App Switcher to neetoui layouts.

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#447]
I was thinking on the app switcher part feels like to don't need to have a separate package just for 1 file. We could add that on the neetoui layouts. 

@karthiknmenon Let me know your thoughts

**Comment by edwinbbu** [comment]
Figma Link: https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/?node-id=407%3A1728

**Comment by karthiknmenon** [comment]
I agree. The current trigger for the app switcher is from the sidebar, we can add that inside `neetoui/layouts` just like we have the sidebar component.

cc: @neerajdotname

**Comment by edwinbbu** [comment]
@edwinbbu _a
