### ISSUE TITLE
Create collapsible filter menu in neetoUI v2 layouts

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#458]
@ajmaln _a

Please refer the [design](https://www.loom.com/i/27a9d19ace9449efa94213154c559a5c) for more details. A similar component was created in neetoUI v1. 

cc: @edwinbbu, @praveen-murali-ind

**Comment by edwinbbu** [comment]
Figma ref in neetoChat: https://www.figma.com/file/9rPsUXEWN7GA3MNuwd66xC/neetoChat?node-id=35%3A1213
