### ISSUE TITLE
[Syncing] Pane

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#46]
## Points to note
- Component in action - `Pane.js`
- Github Urls to this component:
  * [neeto-ui/Pane.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Pane.js)
  * [NitroUI/Pane.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Pane.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Pane.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/Pane.js	2020-11-28 16:54:24.011501400 +0530
+++ neetoui-official/Pane.js	2020-11-28 16:49:18.750476600 +0530
@@ -16,21 +16,21 @@
   } = props;
   return (
     <Drawer
-      className={classnames(["nh-pane--wrapper", className])}
+      className={classnames(["nui-pane--wrapper", className])}
       size={"40%"}
       canEscapeKeyClose
       canOutsideClickClose
       {...otherProps}
     >
       <div
-        className={classnames(["nh-pane--body"], {
-          "nh-pane--body__has-footer": showFooter
+        className={classnames(["nui-pane--body"], {
+          "nui-pane--body__has-footer": showFooter
         })}
       >
         {loading ? <PageLoader /> : children}
       </div>
       {showFooter && (
-        <div className="nh-pane--footer">
+        <div className="nui-pane--footer">
           <Button
             label="Cancel"
             size="large"
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a Sync is required. ([Ref](https://github.com/bigbinary/neeto-help-web/pull/8695/files#diff-d34e9a819b35a62ad3a7cffbc32d0cbf8124f255781c7c0bbde682dbae970fcb))
