### ISSUE TITLE
Add max-width for input fields

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#466]
@praveen-murali-ind _a

Please refer to the following [screenshot](https://www.loom.com/i/f9b7dd9170634c1eae5a35c30332e089). I feel that we don't need a full-width input field in most scenarios. Could you please discuss the same and change accordingly? 

cc: @edwinbbu

**Comment by praveen-murali-ind** [comment]
> @praveen-murali-ind _a
> 
> Please refer to the following [screenshot](https://www.loom.com/i/f9b7dd9170634c1eae5a35c30332e089). I feel that we don't need a full-width input field in most scenarios. Could you please discuss the same and change accordingly?
> 
> cc: @edwinbbu

Usually text input widths are 100%. We can easily make fixed width inputs by adjusting the wrapping container width based on context. If we give some fixed widths as props in neetoUI it would be bit difficult to handle the responsiveness in some cases. 

But if there are repeating patterns(width) in design we can consider giving them as props (pincode, small number inputs etc). But I think most of the cases we can simply adjust the container width to fix such issues. Please let me know your thoughts on this.

**Comment by karthiknmenon** [comment]
True. We can fix it at a project level rather than doing it here.
