### ISSUE TITLE
Update Sidebar styles to match the design

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#476]
[Figma Link](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=774%3A1990)

@praveen-murali-ind _a

<img width="601" alt="Screenshot 2021-10-05 at 3 05 36 PM" src="https://user-images.githubusercontent.com/48869249/135998516-e8bebab7-2990-48a2-9d2f-1741f4636d45.png">

**Comment by praveen-murali-ind** [comment]
@amaldinesh7 The left sidebar background color has been updated to `#E9EBED` in design. Please check this [design](https://www.figma.com/file/9rPsUXEWN7GA3MNuwd66xC/neetoChat?node-id=665%3A8009).
