### ISSUE TITLE
Should menubar title be aligned with sidebar and page title

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#479]
<img width="1476" alt="Screenshot 2021-09-28 at 11 56 34 AM" src="https://user-images.githubusercontent.com/17916573/135034680-e59df6e5-db9e-4be0-b4c8-59508a1b8555.png">

@karthiknmenon _a Please share your thoughts.

**Comment by karthiknmenon** [comment]
Yes. We need to bring consistency here. 

cc: @vysaghsekharbb  @praveen-murali-ind

**Comment by vysaghsekharbb** [comment]
Both headers must be aligned on a single horizontal line. From the top, each will have a 24px padding. @karthiknmenon @edwinbbu

**Comment by edwinbbu** [comment]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
[Figma link](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=1021%3A3648)
