### ISSUE TITLE
[Syncing] Select

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#48]
## Points to note
- Component in action - `Select.js`
- Github Urls to this component:
  * [neeto-ui/Select.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Select.js)
  * [NitroUI/Select.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Select.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Select.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/Select.js	2020-11-28 16:54:24.108520100 +0530
+++ neetoui-official/Select.js	2020-11-28 16:49:18.753276500 +0530
@@ -7,7 +7,6 @@
   render() {
     const {
       label,
-      labelProps,
       required,
       type,
       placeholder,
@@ -31,7 +30,7 @@
         ])}
       >
         {label && (
-          <Label required={required} className="mb-1" {...labelProps}>
+          <Label className="mb-1" required={required}>
             {label}
           </Label>
         )}
@@ -40,10 +39,10 @@
           value={value}
           type={type}
           placeholder={placeholder}
-          className={classnames(["nh-react-select-container"], {
-            "nh-react-select-container--error": !!error
+          className={classnames(["nui-react-select-container"], {
+            "nui-react-select-container--error": !!error
           })}
-          classNamePrefix="nh-react-select"
+          classNamePrefix="nui-react-select"
           {...otherProps}
         />
         {!!error && <p className="mt-1 text-xs text-red-600">{error}</p>}
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a Sync is required. `labelProps` is needed.
