### ISSUE TITLE
Update Modal component to match the design

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#482]
@praveen-murali-ind  _a

**Comment by edwinbbu** [comment]
Figma: https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=624%3A1711

**Comment by edwinbbu** [comment]
@praveen-murali-ind From the design, the button sizes are the same for all the alerts. Let's support multiple sizes for the alert component as in the figma.

**Comment by edwinbbu** [comment]
cc @karthiknmenon

**Comment by praveen-murali-ind** [comment]
> @praveen-murali-ind From the design, the button sizes are the same for all the alerts. Let's support multiple sizes for the alert component as in the figma.

It would be better if we provide option to set size of buttons too. For example, In neeto Auth only buttons inside the Alerts have small size, all other buttons have large size.

**Comment by edwinbbu** [comment]
@praveen-murali-ind 
> It would be better if we provide option to set size of buttons too. For example, In neeto Auth only buttons inside the Alerts have small size, all other buttons have large size.

Let's fix the same size for the button for all the Alert components. It can be small/large but should respect the design.
