### ISSUE TITLE
[Syncing] Tab

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#49]
## Points to note
- Component in action - `Tab.js`
- Github Urls to this component:
  * [neeto-ui/Tab.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Tab.js)
  * [NitroUI/Tab.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Tab.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Tab.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/Tab.js	2020-11-28 16:54:24.155519600 +0530
+++ neetoui-official/Tab.js	2020-11-28 16:49:18.758387400 +0530
@@ -8,7 +8,7 @@
   return (
     <div
       className={classnames([
-        "nh-tab--wrapper flex flex-row justify-start items-end",
+        "nui-tab--wrapper flex flex-row justify-start items-end",
         className
       ])}
     >
@@ -32,8 +32,7 @@
   }
   return (
     <Parent
-      type="button"
-      className={classnames(["nh-tab", className], {
+      className={classnames(["nui-tab", className], {
         active
       })}
       onClick={onClick}
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a `tab.scss` needs to be synced.
