### ISSUE TITLE
Support CSS variables or SASS export

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#490]
Currently, the neetoUI SASS theme variables and mixins have scope only inside the neetoUI.  
If we need a mixin or theme variable on the project side we need to copy-paste it from neetoUI.

If we support SASS export or CSS variables, we can use the CSS variables and mixins we define in neetoUI on the project side also.

Another advantage is we can create different themes based on the project with minimal effort. 

Let’s consider this once we release a stable version of neetoV2.

**Comment by edwinbbu** [comment]
@praveen-murali-ind _a Since we have separated out in CSS bundle file. Can you take a look into exporting CSS variables and mixins as you have discussed.

**Comment by praveen-murali-ind** [comment]
@karthiknmenon _a
