### ISSUE TITLE
Add layouts `Header`, `Subheader` to storybook [documentation]

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#491]
@vipul-goel _a

Task:

- [x] Add Header
- [x] Add subheader
- [x] Add controls to sidebar

Controls missing in sidebar.
<img width="1792" alt="Screenshot 2021-10-01 at 11 52 38 AM" src="https://user-images.githubusercontent.com/17916573/135641387-74be30b1-424b-41f1-ab38-023557fa8a81.png">

**Comment by karthiknmenon** [comment]
Fixed via https://github.com/bigbinary/neeto-ui/pull/494
