### ISSUE TITLE
Modal close icon is misaligned 

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#493]
@praveen-murali-ind _a Please cross-check with the Figma design. 

Ref - 
![image](https://user-images.githubusercontent.com/41678651/135881137-bea90ae2-f4cf-4303-84aa-88ecabdcca10.png)

UI _t bug _t

**Comment by praveen-murali-ind** [comment]
@vysaghsekharbb _a Could you please verify.

Figma [Link](https://www.figma.com/file/Ur7M4IquUbQ57Jpyx1ciMH/Neeto-UI-Kit?node-id=542%3A1545)

In Modal design we are missing the close icon. Considering usability and accessibility it would be nice to have close icon in Modal.

//cc @karthiknmenon

**Comment by praveen-murali-ind** [comment]
@praveen-murali-ind _a
