### ISSUE TITLE
The color of Tag component should be customisable

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#496]
@ajmaln _a We should be allowing a user to customize the color of Tag component by passing props to it. Please work on this issue. The same tag component will be used in neetoInvisible and neetoKb. 

Ref - 
![image](https://user-images.githubusercontent.com/41678651/136017467-a17f6585-d481-4be7-ab2b-57c5b237620c.png)

cc: @praveen-murali-ind, @edwinbbu

**Comment by karthiknmenon** [comment]
@praveen-murali-ind We need to allow a set of colors to be passed from the front end as props. Should we map it to`nui-pastel` colors? Please let me know your thoughts on this. 

cc: @vysaghsekharbb

**Comment by praveen-murali-ind** [comment]
> @praveen-murali-ind We need to allow a set of colors to be passed from the front end as props. Should we map it to`nui-pastel` colors? Please let me know your thoughts on this.
> 
> cc: @vysaghsekharbb

Right. We need to map it to `neeto-color-palette`.
