### ISSUE TITLE
v2: Doc says to import "ClockIcon" but "Clock" is the one that actually work

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#503]
Been trying out neetoUI2. The [Iconography docs](https://neetoui-v2.netlify.app/?path=/docs/foundation-iconography--iconography) say to import items with a "Icon" at the end of the name. But this import doesn't work. I had to use just "Clock" to get it working.

Example code :
```
import { Clock } from "@bigbinary/neeto-icons";
...
<Button icon={Clock} style="link" size="large" />
```

![image](https://user-images.githubusercontent.com/2305675/136538079-b9785c79-3fa4-4456-bb86-b07c03929f49.png)

cc @yedhink

**Comment by yedhink** [comment]
@praveen-murali-ind _a

Can you please take a look into this? Thanks.

Please note that TB3 folks will be using neetoUI-v2 as part of their work. Thus I think it would be good to fix this issue with some priority, given that the docs are the first point of reference.

cc: @karthiknmenon @edwinbbu
