### ISSUE TITLE
[Syncing] Tooltip

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#51]
## Points to note
- Component in action - `Tooltip.js`
- Github Urls to this component:
  * [neeto-ui/Tooltip.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/Tooltip.js)
  * [NitroUI/Tooltip.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Tooltip.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `Tooltip.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **Yes**

## Diff
```diff
--- NitroUI/Tooltip.js	2020-11-28 16:54:24.193653900 +0530
+++ neetoui-official/Tooltip.js	2020-11-28 16:49:18.764088400 +0530
@@ -9,7 +9,6 @@
         "flex flex-row items-center justify-center",
         className
       ])}
-      targetClassName="flex flex-row justify-center items-center"
       popoverClassName={classnames({
         [`bp3-tooltip--${size}`]: size
       })}
```

**Comment by yedhink** [comment]
@yedhink _a

**Comment by goutham-subramanyam** [comment]
`tooltip.scss` needs to be synced as well. ([Ref](https://github.com/bigbinary/neeto-help-web/pull/8695/files#diff-8d501e4c253990631fb0d39d2a1c2a3e1d79392dee0f571e127d71c883eed41f))

**Comment by yedhink** [comment]
I'm closing this issue. There aren't any diff changes for both component as well scss file. Do let me know if i'm missing something here.

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
@yedhink _a Both component and scss files needs to be updated.

Refer https://github.com/bigbinary/neeto-help-web/pull/8766/files#diff-8d501e4c253990631fb0d39d2a1c2a3e1d79392dee0f571e127d71c883eed41f for the scss changes

Also, `targetClassName="flex flex-row justify-center items-center"` is needed.
