### ISSUE TITLE
[Syncing] formik/Input

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#53]
## Points to note
- Component in action - `formik/Input.js`
- Github Urls to this component:
  * [neeto-ui/formik/Input.js](https://github.com/bigbinary/neeto-ui/tree/67ee4a5188c5feccbeca2767107651fb24932764/lib/components/formik/Input.js)
  * [NitroUI/Formik/Input.js](https://github.com/bigbinary/neeto-help-web/tree/0b11a7b0f98ac7c533df1e9ec37cf900b4cbc901/app/javascript/Admin/Components/NitroUI/Formik/Input.js)
- :green_circle: Green color signifies how that particular line is written in `neeto-ui` package
- :red_circle: Red color signifies how that particular line is written in `NitroUI` internals

## Sync Required or Not
- Are there significant changes for `formik/Input.js` that needs to be synced to `neeto-ui` package from `NitroUI`? - **No**

## Diff
```diff
--- NitroUI/formik/Input.js	2020-11-28 16:54:23.933435600 +0530
+++ neetoui-official/formik/Input.js	2020-11-28 16:49:18.769930700 +0530
@@ -6,12 +6,9 @@
 export default function FormikInput({ name, ...rest }) {
   return (
     <Field name={name}>
-      {({ field, form: { errors }, meta }) => {
-        const errorMessage = errors[field.name] || rest.error;
-        return (
-          <Input {...field} {...rest} error={meta.touched && errorMessage} />
-        );
-      }}
+      {({ field, meta }) => (
+        <Input error={meta.touched && meta.error} {...rest} {...field} />
+      )}
     </Field>
   );
 }
```

**Comment by goutham-subramanyam** [comment]
@yedhink _a Sync is required. The props were reordered by @danedavid to fix some issue. ([Ref](https://github.com/bigbinary/neeto-help-web/pull/8380))
