### ISSUE TITLE
Email not shown after passing it through profile info on Sidebar component.

### ISSUE THREAD

**Issue by Nuzair46** [bigbinary/neeto-ui#549]
[Here](https://neetoui-v2.netlify.app/?path=/story/layouts-sidebar--sidebar-with-app-switcher),
In the Sidebar component the email is not shown under the profile name even though it is passed as a property.

<img width="859" alt="Screenshot 2021-10-18 at 7 05 12 PM" src="https://user-images.githubusercontent.com/38219313/137741928-b69d24f5-3e5e-4e25-a7ea-3b7c06e12340.png">

Issue also present in a local app.

How it is supposed to look:

<img width="1007" alt="Screenshot 2021-10-18 at 7 07 08 PM" src="https://user-images.githubusercontent.com/38219313/137742297-3ce011dc-4868-4b7c-91c8-b29623b4ff8c.png">

@yedhink @karthiknmenon

**Comment by edwinbbu** [comment]
@karthiknmenon _a I think the decision was made to not show the email in the sidebar profile. Might have missed updating the documentation. Please take a look.

**Comment by karthiknmenon** [comment]
Closing this as a design decision was taken to not include email in the sidebar. 
The reason was that there's a high chance that we would have to truncate emails as they grow longer.
