### ISSUE TITLE
[Syncing] Components that require full sync from NitroUI to neetoui and vice versa

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#56]
This list will be updated constantly.

## Components that are only part of neetoui package but not NitroUI internals
- neetoui/IconPicker.js
- neetoui/Alert.js

## Components that are only part of NitroUI internals but not neetoui package
- NitroUI/ColorPalette.js
- NitroUI/ColorPicker.js
- NitroUI/TableLoader.js
- NitroUI/Formik/RichText.js

@edwinbbu 
I will bring in the components from NitroUI that are missing in neetoui. Let me know if the same should be done vice versa and we should add `IconPicker` to neeto-help-web/NitroUI internals

@yedhink _a

**Comment by edwinbbu** [comment]
@yedhink Other than `IconPicker` there is also another component `Alert` which is only in neetoui. Once the package is installed, we can access all the components. Hence reverse syncing is not required.
