### ISSUE TITLE
Suggestions for improvements in table 

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui#571]
https://www.loom.com/share/8f7b6af1ef6143c1ac73aa013e192e38

**Comment by karthiknmenon** [comment]
@neerajdotname Please view this [loom video](https://www.loom.com/share/a0a718acf29944729b53420acb1944aa) for the updates on `Table` component.

**Comment by neerajdotname** [comment]
@karthiknmenon The new table component looks great. 😍
