### ISSUE TITLE
v2 <Alert> doesn't have style prop, v2 <Modal> doesn't support size=large prop

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#574]
* [ ] v1's `<Alert>` has a `style` prop which is useful in simply making decorative alerts for dangerous actions like deletion. This prop is not available in v2.

This is `<Alert style="danger">` in v1:

<img width="589" alt="Screenshot 2021-10-19 at 11 32 27 PM" src="https://user-images.githubusercontent.com/2305675/137965744-71b66d5c-417d-477c-8507-4a622cfe0c4f.png">

[v1 also supported "info", "warning" values](https://neetoui.netlify.app/#/alert) for the `style` prop. Will v2's `<Alert>` support this `style` prop ? This is a very handy feature.

* [ ] v2's `<Model>` doesn't support "large" size (`size="lg"`). In v1, if `size="lg"` then the modal will use full-height/width of the page.

[Loom video explaining both](https://www.loom.com/share/e26588ecbd4b43f88af1e3de1f03f28f)

cc @karthiknmenon @edwinbbu

**Comment by karthiknmenon** [comment]
Closing wrt https://github.com/bigbinary/neeto-ui/issues/591. 
We will be taking up `fullScreen` modal in a separate issue since it needs UX input.

**Comment by subins2000** [comment]
Okay, please cc me in it when that issue is made. Thanks

**Comment by subins2000** [comment]
@karthiknmenon Any updates on the fullscreen modal ? Shall I make a new issue for it ?
