### ISSUE TITLE
Remove outline and text decoration On Accordion Component Focus and Panel click.

### ISSUE THREAD

**Issue by mohitharshan123** [bigbinary/neeto-ui#595]

**Comment by karthiknmenon** [comment]
@mohitharshan123 _a Could you please post a loom video for this issue?

**Comment by mohitharshan123** [comment]
> @mohitharshan123 _a Could you please post a loom video for this issue?

https://www.loom.com/share/e7370266406a49839c97997fb1822794

**Comment by karthiknmenon** [comment]
@praveen-murali-ind _a I guess we would need an outline for better accessibility. Could you please confirm the behavior?

**Comment by praveen-murali-ind** [comment]
@karthiknmenon let’s style the hover, focus and focus-visible states.

**Comment by praveen-murali-ind** [comment]
@ajmaln _a
