### ISSUE TITLE
Avatar: Revoke object URL once blob is set/loaded to `img` tag

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#601]
https://github.com/bigbinary/neeto-ui/blob/7db216619999ae309481785f0587e5e3a7d4c2f9/lib/components/Avatar.js#L113

I think we should remove the object URL reference once the blob has actually been loaded to DOM.

Refer: https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL

@karthiknmenon @praveen-murali-ind 

Can you folks please take a look into this when you are free? It's like a best practice kinda thing from what I read.

**Comment by karthiknmenon** [comment]
@labeebklatif _a Please check.

**Comment by labeebklatif** [comment]
@yedhink Going through the code, I haven't seen any of the createObjectURL reference created anywhere in the component. Seems like we are directly passing the URL reference to the img tag. If I understand correctly, The createObjectURL is used when we have a File or Blob objects that we need to use as a URL reference. revokeObjectURL has to be used only when we have created any reference using createObjectURL, right? Am I missing something here?

**Comment by yedhink** [comment]
@labeebklatif

>I haven't seen any of the createObjectURL reference created anywhere in the component

We do this in the application logic rather than delegating it to neetoUI.

- Let's take the case where we need to upload an Avatar image for the user.
- Once we upload the image, we need to invoke `createObjectURL` to get the URL of the image
- Once we get that we pass it to `Avatar` component.
- The URL revocation should be done in the `onLoad` attr of img tag. Refer: https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#example_using_object_urls_to_display_images
- You can even allow passing a custom `onLoad` to `Avatar`. This way the application can take care of the revoke logic.

**Comment by labeebklatif** [comment]
I will check this out and revert

**Comment by karthiknmenon** [comment]
@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@yedhink _a please go through my observations regarding this issue. Please share your thoughts on the same. https://vimeo.com/662884198/ee22cce11f

**Comment by yedhink** [comment]
@AbhayVAshokan Thanks for the detailed video. Appreciate it.

I think for the time being we needn't add this enhancement since like you had mentioned, in most cases, image is loaded via API call itself.

Closing this issue.
