### ISSUE TITLE
Issue with sidebar tooltip in collapsed view

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#605]
@vysaghsekharbb _a Currently, we are showing the tooltips in the collapsed state of the sidebar. However, with the `AppSwitcher` open, should we show the tooltips for each navLink? 

Ref - 
![image](https://user-images.githubusercontent.com/41678651/139780980-4ffba140-6327-4f5e-bfa5-d23be0c2ec91.png)

**Comment by edwinbbu** [comment]
@karthiknmenon The current implementation looks fine. The tooltip is on top app switcher looks good.

<img width="572" alt="Screenshot 2021-11-19 at 11 52 08 AM" src="https://user-images.githubusercontent.com/17916573/142575147-1c832ec1-75ab-4695-ad8f-141942013411.png">

@karthiknmenon _a Please close the issue if it's satisfactory.
