### ISSUE TITLE
Fix Avatar text in Table component.

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#606]
@ajmaln _a Please take this up.

The `last_name` letter in Avatar is static here. It is showing as `o` for all last names.

<img width="377" alt="Screenshot 2021-11-02 at 11 42 37 AM" src="https://user-images.githubusercontent.com/48869249/139796040-f365ed9b-edbb-4fec-9b80-76bf7b2865b4.png">

//cc @karthiknmenon

**Comment by karthiknmenon** [comment]
@karthiknmenon _a Taking this up, along with few other improvements in table.
