### ISSUE TITLE
Fix Page Size issue in Table Component when setting defaultPageSize.

### ISSUE THREAD

**Issue by mohitharshan123** [bigbinary/neeto-ui#607]
Table Pagination is not working correctly now.

I think the issue is in passing prop as defaultPageSize instead of pageSize.

**Comment by ajmaln** [comment]
@mohitharshan123 Could you please record and post a video of the issue?

**Comment by mohitharshan123** [comment]
> @mohitharshan123 Could you please record and post a video of the issue?

 I'm closing this one. The issue is when new data is loaded and passed asynchronously.
