### ISSUE TITLE
Icon in navLinks are not really center aligned when collapsed

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#609]
Issue origin: https://github.com/bigbinary/neeto-wireframe-web/pull/672#issuecomment-957273741

![image](https://user-images.githubusercontent.com/2305675/139836218-44173f5d-2e7e-4ecc-9485-79207d01ba7f.png)

The icon in navLinks are not really center (for both SVG and `<i>`). This can be clearly seen when the navLink is highlighted.

There's a `justify-center` in the immediate wrapper of the icon but not in the next parent (which is also a flex container). I was able to center align the icons by adding `justify-center` class for the next parent which is `<NavLink>`: https://github.com/bigbinary/neeto-ui/blob/master/lib/components/layouts/Sidebar.js#L172

But doing so will make the icon center during the animation of `!collapsed` to `collapsed`.

This can be seen in [neetoPlanner too](https://spinkart.neetoplanner.net/)

**Comment by yedhink** [comment]
@praveen-murali-ind Please take a look into this when you are free.

**Comment by praveen-murali-ind** [comment]
> @praveen-murali-ind Please take a look into this when you are free.

It’s fixed in the latest neetoUI update.

**Comment by praveen-murali-ind** [comment]
> Issue origin: [bigbinary/neeto-wireframe-web#672 (comment)](https://github.com/bigbinary/neeto-wireframe-web/pull/672#issuecomment-957273741)
> 
> ![image](https://user-images.githubusercontent.com/2305675/139836218-44173f5d-2e7e-4ecc-9485-79207d01ba7f.png)
> 
> The icon in navLinks are not really center (for both SVG and `<i>`). This can be clearly seen when the navLink is highlighted.
> 
> There's a `justify-center` in the immediate wrapper of the icon but not in the next parent (which is also a flex container). I was able to center align the icons by adding `justify-center` class for the next parent which is `<NavLink>`: https://github.com/bigbinary/neeto-ui/blob/master/lib/components/layouts/Sidebar.js#L172
> 
> But doing so will make the icon center during the animation of `!collapsed` to `collapsed`.
> 
> This can be seen in [neetoPlanner too](https://spinkart.neetoplanner.net/)

Could you please upgrade the neetoUI version and try.

**Comment by yedhink** [comment]
@subins2000 _a

Please verify and close this PR if the issue is already fixed in latest neetoUI version.

**Comment by subins2000** [comment]
@praveen-murali-ind Just checked it now. It's fixed. Thanks
