### ISSUE TITLE
Display the selected time in the DatePicker

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#610]
Please check out the video: https://vimeo.com/641491318/c236de5eaa

@ajmaln _a

enhancement _t

**Comment by amaldinesh7** [comment]
Updating the format to `MM-DD-YYYY HH:mm:ss` fulfilled the use case. But if we set `showTime` prop to `true`, then the time should appear in the field by default right? @ajmaln

**Comment by ajmaln** [comment]
@karthiknmenon Could you please suggest on this? I think one way to go is to update the default format to include time when `showTime` is `true`, or should we display time always when `showTime` is `true` Let me know your thoughts.

**Comment by karthiknmenon** [comment]
@ajmaln Let's include time in `MM-DD-YYYY HH:mm:ss` when showTime is true.

**Comment by karthiknmenon** [comment]
@karthiknmenon _a Fixed.
