### ISSUE TITLE
Fix utility classes in Safari

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#617]
@praveen-murali-ind _a

<img width="1440" alt="Screenshot 2021-11-05 at 11 28 08 PM" src="https://user-images.githubusercontent.com/48869249/140556908-c217a496-c070-4aaa-a5a0-285d89af41d0.png">

**Comment by praveen-murali-ind** [comment]
Fixed color utilities in Safari.

<img width="1440" alt="Screenshot 2021-11-05 at 11 40 57 PM" src="https://user-images.githubusercontent.com/48869249/140558541-49c6cc04-23e5-4f05-a01f-3b1f8ed77a33.png">

**Comment by praveen-murali-ind** [comment]
@karthiknmenon _a Could you please check this issue. The changes are not reflected in our JS bundle.

**Comment by edwinbbu** [comment]
@praveen-murali-ind _a https://www.loom.com/share/6c68acea5f304b5a90eccbe0776e334e

cc @karthiknmenon
