### ISSUE TITLE
Do we need a button for info in label?

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#619]
<img width="320" alt="Screenshot 2021-11-08 at 3 02 27 PM" src="https://user-images.githubusercontent.com/33386004/140717832-8df20bac-b059-407d-a582-0986685d199b.png">

Instead of a button, we can use an icon right?

Painpoints
- Background on hover looks weird since this is placed near a text (label)
- Icon color is darker than the text color (Imoprtance is for the text right?)
<img width="284" alt="Screenshot 2021-11-08 at 3 07 43 PM" src="https://user-images.githubusercontent.com/33386004/140718503-5cf91298-544c-461d-9bec-5ab924af6f9f.png">
- Spacing between the icon and text can be changed to 4px (If we are opting icon)
<img width="148" alt="Screenshot 2021-11-08 at 3 09 17 PM" src="https://user-images.githubusercontent.com/33386004/140718917-fe38eb2d-467a-43d1-9db9-fc4b4ba0e770.png">

@karthiknmenon Please share your thoughts on this.

@ajmaln _a

**Comment by karthiknmenon** [comment]
cc: @praveen-murali-ind

**Comment by praveen-murali-ind** [comment]
Let’s not use Button component for info icon.
