### ISSUE TITLE
Option to remove Checkbox from Tables

### ISSUE THREAD

**Issue by Nuzair46** [bigbinary/neeto-ui#621]
https://neetoui-v2.netlify.app/?path=/docs/components-table--template

here, the checkbox can be disabled by passing `rowSelection={false}` to the Table component. would be nice to have this on the docs.

Also, its possible to customize the Checkbox to radio by passing 
```jsx
rowSelection={{type: "radio"}}
```

**Comment by karthiknmenon** [comment]
@Nuzair46 Adding docs for `rowSelection={false}`. However, let's not support `radio` for now. The current design system does not have a use case where will be needing a `radio` selector. 
If we do, we will add it then.
