### ISSUE TITLE
Fix dependabot security alerts

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/neeto-ui#646]
https://github.com/bigbinary/neeto-ui/security/dependabot

We have 21 alerts on neeto-ui and since neeto-ui is used everywhere else, this might cause security issues on all neeto apps. It is worth fixing these. 

I have turned on "Dependabot security updates" and it has already created a few PRs. Please get them merged as well.

@edwinbbu _a

**Comment by edwinbbu** [comment]
@amaldinesh7 _a

**Comment by karthiknmenon** [comment]
@AbhayVAshokan _a Most of them are fixed, there are a few left out. Please take care of them.

**Comment by AbhayVAshokan** [comment]
Closing since no more dependabot PRs is remaining.

**Comment by karthiknmenon** [comment]
@jagannathBhat _a

**Comment by jagannathBhat** [comment]
Closing since there are no open dependabot PRs.
