### ISSUE TITLE
Fix neeto-ui "Table" causes app to crash

### ISSUE THREAD

**Issue by sahilLikes2Code** [bigbinary/neeto-ui#672]
Observed the bug while working on neeto-crm-web.

Importing the `Table` from neetoui/v2 and calling it in any component raises following warning:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

Most importantly, this causes the app the crash and not display anything. In order to debug this further, I copied over the code of neetoui Table to a local file, found out that [this](https://github.com/bigbinary/neeto-ui/blob/03807f9c59ac18026a1a649d7f4bc271c0ca6d25/lib/components/Table.js?_pjax=%23repo-content-pjax-container#L36) is causing the issue.

Therefore if we switch,
`emptyText: <Typography style="body2">No Data</Typography>` with` emptyText: 'No Data'` . Everything gets back to functional state. 

All in all, is it necessary to wrap the string with `Typography`

**Comment by sahilLikes2Code** [comment]
@ajmaln _A

**Comment by ajmaln** [comment]
Closing this issue, since it was fixed after upgrading `neeto-ui`
