### ISSUE TITLE
Add documentation wrt neetoUI 3.0

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#673]
@ajmaln _a Please add proper documentation on how to use neetoUI 3.0.x.

**Comment by yedhink** [comment]
@ajmaln Reiterating that this is a very high priority issue. Things are breaking for certain folks and documentation is not helping them.

@praveen-murali-ind @edwinbbu @karthiknmenon 
Also, moving forward, it would be really great if we can make sure that whenever a major upgrade or changes in setup happen, we make sure to document the same. Thanks.

**Comment by karthiknmenon** [comment]
@karthiknmenon _a
