### ISSUE TITLE
Toastr not working as expected

### ISSUE THREAD

**Issue by Nuzair46** [bigbinary/neeto-ui#693]
@yedhink 

* Styling for Toastr not mentioned in the neetoui/v2 doc.
```css
@import "react-toastify/dist/ReactToastify.min.css";
```

* React-Toastify is not installed with neeto-ui.

**Comment by yedhink** [comment]
@edwinbbu  _a

Can you please take a look into this? Thanks. 

cc: @karthiknmenon @praveen-murali-ind

**Comment by karthiknmenon** [comment]
@Nuzair46 As far as I understand this is a documentation issue right? If not, please add the `bug` label back  to the issue.

**Comment by Nuzair46** [comment]
@karthiknmenon its a documentation issue and also react-toastify is not getting installed with neetoui as it is a dependency.

**Comment by yedhink** [comment]
@karthiknmenon The following is the confusing part for me that made me feel this might be a bug. Shouldn't all css styles get loaded if we add the below import statement to our css pipeline? Why is that we need to add react-toastify css separately?

Refer this screenshot of readme:

![image](https://user-images.githubusercontent.com/31244999/144443976-7da03772-2f90-4918-a419-ddda7a115394.png)

**Comment by edwinbbu** [comment]
@yedhink Please check https://www.loom.com/share/ad2e461ae9f1412181b9d0cc8b007fe5. 
It will give some context.

**Comment by yedhink** [comment]
@edwinbbu _a

Valid point. Bundle size should be kept as small as possible.

Let's use this issue to update the documentation for react-toastify. Let's handhold the reader and make them understand what all they need to do inorder to use the Toastr component from neetoUI.

Similarly, let's also update the readme, and point out that the peer-depedencies like say react-toastify needs to be installed manaully within each project where neetoUI is used.

Assigning this issue to you now. You can assign this to someone else if need be.

Thanks.

**Comment by edwinbbu** [comment]
@ajmaln _a Please take it up.
