### ISSUE TITLE
Allowing custom dropdown in profileInfo section in sidebar

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-ui#694]
In neetoChat, we have a custom dropdown for the profile menu in the sidebar. This is to allow a few options which are particular to a product with minute UI changes. 
IMO, we should be allowing a custom dropdown for profile info as there might be a few toggles, UI changes wrt an application. 

@amaldinesh7 _a  Please let me know your thoughts on this. 

Ref - 
![image](https://user-images.githubusercontent.com/41678651/144564487-ce6e3a81-a10b-4569-bfdd-53073d41f68a.png)

cc: @edwinbbu, @ajmaln

discussion _t

**Comment by amaldinesh7** [comment]
Closing the issue since the sidebar design has changed.
