### ISSUE TITLE
On blur event is not working on Formik Select component

### ISSUE THREAD

**Issue by vyshnavrajs2019** [bigbinary/neeto-ui#710]
The default onBlur action (mark the field as touched) is not executing.
https://www.loom.com/share/3911459a9da44719a57897f4b45c6180

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a Please verify.

**Comment by AJIL-PAUL** [comment]
@amaldinesh7 _a Please review

cc @karthiknmenon
