### ISSUE TITLE
Embed CSS are repeating across all neetoproducts and minification are missing. 

### ISSUE THREAD

**Issue by edwinbbu** [bigbinary/neeto-ui#714]
This was originally posted by @Harshit-frontend in slack.

https://www.loom.com/share/efd85a7037b14ce4ad6cbe73d6630814

**Comment by edwinbbu** [comment]
@karthiknmenon One of the reasons for this could be v1 bundle files in neetoui.

**Comment by edwinbbu** [comment]
Not sure why we have the `v1.scss` file which contains tailwind. 

<img width="1292" alt="Screenshot 2021-12-17 at 10 40 17 AM" src="https://user-images.githubusercontent.com/17916573/146492347-e149c2f5-3c0e-41ef-8427-54f05a1b1a55.png">

Please add folder `.storybook` to npmignore file to avoid it in the bundle file.

**Comment by edwinbbu** [comment]
@amaldinesh7 _a

**Comment by karthiknmenon** [comment]
> One of the reasons for this could be v1 bundle files in neetoui.

I agree. This could be the reason. I will look into this.
