### ISSUE TITLE
v2 <Modal> doesn't support size=large prop (full size modal)

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#723]
This is a follow-up of #574

v2's `<Modal>` doesn't support "large" size (`size="lg"`). [In v1](https://neetoui.netlify.app/#/modal), if `size="lg"` then the modal will use full-height/width of the page.

This fullsize model is being used in neetoWireframe for previewing the output of the wireframe. For preview, we'd need a fullsize modal and other sizes won't satisfy the requirement.

[Loom video explaining it (until 0:35)](https://www.loom.com/share/e26588ecbd4b43f88af1e3de1f03f28f).

The migration of neetoWireframe from neetoUI v1 to v2 will be completed when this is supported: https://github.com/bigbinary/neeto-wireframe-web/issues/707

cc @karthiknmenon @Harshit-frontend

**Comment by amaldinesh7** [comment]
Large-sized modal is rarely used, if there is any use case as such, a medium-sized modal can be customized to achieve it. Thus closing the issue.
