### ISSUE TITLE
Toast message text different from response

### ISSUE THREAD

**Issue by ajith-jaban** [bigbinary/neeto-ui#725]
https://www.loom.com/share/7286bca1700e412b9854f80884998e74

**Comment by ajith-jaban** [comment]
Please refer this [Video](https://www.loom.com/share/6b4b50b0858a4cad860519fe9a13e16e)

**Comment by ajith-jaban** [comment]
bug _t

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a Could you please look into it?

**Comment by AJIL-PAUL** [comment]
@amaldinesh7 _a Please review

cc @karthiknmenon
