### ISSUE TITLE
Input does not handle null values

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-ui#740]
**Problem**: Input does not properly handle `null` when provided as a value. It raises an error.

- It is quite common for the input to be set `null` when initialValues in Formik directly accepts data from the API response.

**Solution**:
```js
- value={value}
+ value={value ?? ""}
```

@karthiknmenon _a please have a look: https://vimeo.com/662569717/d808e949be

**Comment by amaldinesh7** [comment]
@AbhayVAshokan _a Please raise a PR with the suggested solution.
