### ISSUE TITLE
Add `JSX content inside` feature on hover as well in the tooltip.

### ISSUE THREAD

**Issue by nehajamwalR** [bigbinary/neeto-ui#746]
We need to have an option in the tooltip which enables the tooltip window to stay on hover.
@praveen-murali-ind _a 
cc @yedhink

**Comment by yedhink** [comment]
@nehajamwalR Please add a video showing the exact requirement. Thanks.

**Comment by praveen-murali-ind** [comment]
> We need to have an option in the tooltip which enables the tooltip window to stay on hover.

If the Tippy has interactive content inside it, please use this prop `interactive` so that it can be hovered over and clicked inside without hiding.

**Comment by nehajamwalR** [comment]
Thanks Praveen, the requirement is fulfilled by the `interactive` prop.
Hence closing the issue.
