### ISSUE TITLE
Typography colors don't change in dark mode

### ISSUE THREAD

**Issue by tejasaithal** [bigbinary/neeto-ui#748]
When in dark mode, the typography examples stay black.

Link: https://neetoui.netlify.app/?path=/docs/foundation-typography--heading-1&globals=outline:true;backgrounds.value:!hex(333333);backgrounds.grid:true

Ref: 
![reference](https://user-images.githubusercontent.com/63770683/148532912-e31c8075-28d0-4ba7-96ef-bbdd3d242f04.png)

**Comment by karthiknmenon** [comment]
@tejasaithal _a
We are not taking into consideration a theme toggle for any of our components till now. Is there a use-case where you'd be needing this?

**Comment by tejasaithal** [comment]
No usecase. Figured the issue should be known. It's typography afterall.
