### ISSUE TITLE
Select component inside Alert causes scroll behaviour

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-ui#758]
- Opening the `Select` component inside the `Alert` component leads to an overflow scroll.
![Select inside Modal](https://user-images.githubusercontent.com/35297280/149270094-bb3fc7ce-3f26-4ab3-9b8d-2b0df962e989.gif)

- Making the size to increase dynamically or making the select options appear above the modal are possible alternatives.

@praveen-murali-ind _a could you please check if there is a possible fix for this?

**Comment by praveen-murali-ind** [comment]
@ajmaln _a Could you please check this issue.

[Reference](https://react-select.com/advanced#portaling)
