### ISSUE TITLE
Animation issue with Overlays

### ISSUE THREAD

**Issue by josephmathew900** [bigbinary/neeto-ui#761]
https://www.loom.com/share/ae4f787d16a348d794052f983a007d8b
Sandbox link: https://codesandbox.io/s/neetoui-animation-issue-1zbu3

@ajmaln _a Could you please check this issue.
cc @amaldinesh7 @karthiknmenon

**Comment by ajmaln** [comment]
I noticed a few issues after the change on neetoForm, especially after changing routes to different pages with Portals. It is preventing the Modal, Pane components from opening after a route change. Re-opening this issue.
