### ISSUE TITLE
Add data-cy for sidebar elements

### ISSUE THREAD

**Issue by emidhun** [bigbinary/neeto-ui#776]
* Add data-cy for the sidebar.
* Add data-cy for sidebar header elements. 
* Add data-cy for AppSwitcher.

![neeto-runner](https://user-images.githubusercontent.com/20367955/150182233-21e0eb2e-0c80-4e45-af60-09a2a11a104b.png)

**Comment by emidhun** [comment]
@amaldinesh7 _a Please have a look into this.

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a
