### ISSUE TITLE
Add data-cy for Menubar Toggle button

### ISSUE THREAD

**Issue by AlishaSaxena09** [bigbinary/neeto-ui#782]
Add data-cy for Menubar Toggle button

<img width="1436" alt="Screenshot 2022-01-21 at 8 47 09 PM" src="https://user-images.githubusercontent.com/56445633/150552315-99ea3577-132b-4b20-8b38-f556291fe3cd.png">

**Comment by AlishaSaxena09** [comment]
@karthiknmenon_a  Please have a look into this.

**Comment by AlishaSaxena09** [comment]
@karthiknmenon _a Please have a look into this.

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a
