### ISSUE TITLE
Default value for DatePicker breaks the application while trying to open the calendar.

### ISSUE THREAD

**Issue by shreyansh-g24** [bigbinary/neeto-ui#785]
Getting an error while trying to open the calender in DatePicker with a default value

```
index.js:391 Uncaught TypeError: t.weekday is not a function
    at Object.getWeekDay (index.js:391)
    at index.js:98
    at me (index.js:98)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at HTMLUnknownElement.func.___hb (honeybadger.js:1477)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
```

Code

```js
<DatePicker
   className="w-full"
   type="range" 
   defaultValue={[dayjs().subtract(1, "day"), dayjs()]}
/>
```

Clearing the value before opening the calendar works.

**Comment by shreyansh-g24** [comment]
@karthiknmenon

**Comment by karthiknmenon** [comment]
@shreyansh-g24 Have you tried updating neetoUI to the latest version?

**Comment by shreyansh-g24** [comment]
I'll check and update.

**Comment by shreyansh-g24** [comment]
@karthiknmenon Updating the library to v3, breaks import statements.

Updating import statements from `neetoui/v2/*` to `neetoui` fixes it.

It still doesn't fix the dropdown issue.

The dropdown issue is not there in storybook example with DatePicker range.

**Comment by karthiknmenon** [comment]
@amaldinesh7 _a Could you please look into this?

**Comment by amaldinesh7** [comment]
@shreyansh-g24 can you try adding this code snippet to the particular file?

```
import localeData from "dayjs/plugin/localeData";
import utc from "dayjs/plugin/utc";
import weekday from "dayjs/plugin/weekday";

dayjs.extend(weekday);
dayjs.extend(localeData);
dayjs.extend(utc);
```

**Comment by shreyansh-g24** [comment]
@amaldinesh7 Thanks it is working with the plugins.

**Comment by shreyansh-g24** [comment]
Please close this issue, if it doesn't need any updates for neetoui.
