### ISSUE TITLE
Add data-cy for sidebar elements and row element

### ISSUE THREAD

**Issue by harsha2211** [bigbinary/neeto-ui#786]
In neeto-invisible-web
- Add data-cy for row in table 
- Add data-cy for sidebar elements,seesions,member,settings, and app switcher
- Add data-cy for  expandAndCollapseButton
<img width="1440" alt="Screenshot 2022-01-24 at 3 52 40 PM" src="https://user-images.githubusercontent.com/67581198/150766522-838c4c84-7284-4c79-8fa1-1dfbd8c6d4a4.png">
   

<img width="1440" alt="Screenshot 2022-01-24 at 3 55 09 PM" src="https://user-images.githubusercontent.com/67581198/150766653-baccdf2d-c0c1-48e3-9721-e088e05145a4.png">

<img width="1436" alt="Screenshot 2022-01-25 at 4 27 07 PM" src="https://user-images.githubusercontent.com/67581198/150964392-2e9af7e9-8af7-4b21-b471-7426a0c19a30.png">

**Comment by harsha2211** [comment]
@karthiknmenon  _a Please have a look into this.

**Comment by karthiknmenon** [comment]
@AJIL-PAUL _a

**Comment by AJIL-PAUL** [comment]
@karthik I think there is nothing to do with neetoui. We need to add data-cy from neeto-invisible-web itself

**Comment by karthik** [comment]
Wrong person
