### ISSUE TITLE
Add data-cy for side nav bar

### ISSUE THREAD

**Issue by harsha2211** [bigbinary/neeto-ui#793]
In neeto form Please add
1. data-cy for side bar i.e all forms ,favourite , trash  and members.
2 .data-cy for app switcher and what's new

<img width="1440" alt="Screenshot 2022-01-25 at 10 32 49 PM" src="https://user-images.githubusercontent.com/67581198/151023950-cf2490a0-b9da-4337-a4b0-cfdcb3eead0c.png">

**Comment by harsha2211** [comment]
@AJIL-PAUL _a Please look into it

**Comment by AJIL-PAUL** [comment]
@harsha2211  I think data-cy for  forms ,favourite , trash and members should be added from the neetoForm istself.
But we can add data-cy for what's new button in neetoUI
