### ISSUE TITLE
Unable to use URL with query string in Sidebar Navlinks

### ISSUE THREAD

**Issue by rishabhanand12** [bigbinary/neeto-ui#807]
https://www.loom.com/share/1bdfa41789824fc08dd0b3cca822184b

The Navlink inside the Sidebar doesn't get rendered properly if the URL constains a query string. 

I believe the issue is because of the following line of code:  https://github.com/bigbinary/neeto-ui/blob/14e4751d9e478fadb2301e07a6b1ca5949b93a8f/lib/components/layouts/Sidebar/Links.js#L24

cc: @yedhink @karthiknmenon

**Comment by karthiknmenon** [comment]
@ajmaln _a Could you please look into it?

**Comment by yedhink** [comment]
@ajmaln It would be great if you can look into this with high priority. Wheel revamp PRs will be blocked until this issue is fixed.

**Comment by ajmaln** [comment]
@rishabhanand12 I was able to reproduce the issue on the main Nav links and it will be fixed through #808. 

Please note that sub nav items are removed from the latest neetoUI release, so the sub-items you currently have in the sidebar will be removed when you update neetoUI.
