### ISSUE TITLE
[Syncing] form/Switch

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#81]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/Switch.jsx

I think a direct full sync can be done. Let me know if this requires any other changes on sync.

@goutham-subramanyam 

@yedhink _a

**Comment by yedhink** [comment]
@edwinbbu 
@goutham-subramanyam 

On second thoughts, I don't think we need to sync this. Our `Switch` component can replace it.

Please close this issue, if you feel the same way.

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
