### ISSUE TITLE
Add data-cy for Add Form button 

### ISSUE THREAD

**Issue by harsha2211** [bigbinary/neeto-ui#810]
In neeto-form-web
- Add data-cy for **Add Form** button
- Add data-cy for **Add Form** Text in add form popup
- Add data-cy for **Create an amazing form to collect data easily** text in add form popup
- Add data-cy for **Start From Scratch** button and text in add form popup
- Add data-cy for  **Use Template** button and text in add form popup
- Add data-cy for **cross** button in add form popup in add form popup

<img width="1440" alt="Screenshot 2022-02-01 at 11 23 13 PM" src="https://user-images.githubusercontent.com/67581198/152023489-dd330d25-9668-419e-8aea-b750f255b695.png">

<img width="1440" alt="Screenshot 2022-02-01 at 11 15 48 PM" src="https://user-images.githubusercontent.com/67581198/152023002-25abe77c-5be6-4779-8cb2-87f78f142908.png">

<img width="1440" alt="Screenshot 2022-02-01 at 11 09 07 PM" src="https://user-images.githubusercontent.com/67581198/152021129-0833f5d4-1ca8-46d6-ac9c-7acbe6a35f31.png">

**Comment by harsha2211** [comment]
@AJIL-PAUL  _a Please look into it

**Comment by AJIL-PAUL** [comment]
@harsha2211  We have to pass the data-cy props to the neetoui components while we are using it. So we need to add data-cy from the corresponding application (here neeto-forms) . Can you please raise an issue in neeto-form on the same? There is nothing to do in this repo.
