### ISSUE TITLE
Option to open menu bar from the right

### ISSUE THREAD

**Issue by shreyansh-g24** [bigbinary/neeto-ui#815]

**Comment by karthiknmenon** [comment]
@shreyansh-g24 _a Please provide a screenshot or a loom video of what is expected here.

**Comment by shreyansh-g24** [comment]
https://www.loom.com/share/d09a11ea484f441080037e7126372137

**Comment by shreyansh-g24** [comment]
@karthiknmenon _a Please check

**Comment by karthiknmenon** [comment]
@shreyansh-g24 As per the new design system, our layouts would only have collapsible menus on the left. For the current usecase, wouldn't a Pane suffice?

**Comment by shreyansh-g24** [comment]
@karthiknmenon Thank you for the update. Yes a pane would be perfect.
