### ISSUE TITLE
[Syncing] form/FormTreeDropdown

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#82]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormTreeDropdown.jsx

From my understanding, this is not used anywhere in neeto-help. Let me know if there is a spot where this is used.

If not used, then no sync required.

@goutham-subramanyam _a

cc: @edwinbbu

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
