### ISSUE TITLE
[Syncing] form/FormRecaptcha

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#83]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormRecaptcha.jsx

Unused in neeto-help from my understanding. Let me know if this is used somewhere.

Currently syncing not required.

@edwinbbu _a

cc: @goutham-subramanyam

**Comment by edwinbbu** [comment]
Component Recaptcha is unused so we can close the issue.

**Comment by edwinbbu** [comment]
@yedhink _a Since the component is unused, create a PR for removing the component in NeetoHelp.

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
