### ISSUE TITLE
Un-minify neeto-ui npm package for dev environment

### ISSUE THREAD

**Issue by mustafapc19** [bigbinary/neeto-ui#831]
Right now, in the development environment, neeto-ui npm package only has the minified version, which gets in the way during development, since features like ctrl-click will not work.

@amaldinesh7 _a

cc @ajmaln

**Comment by amaldinesh7** [comment]
@vysakh-m _a Please explore the possibilities of implementing this.

**Comment by amaldinesh7** [comment]
@mustafapc19 Do we really need this feature? A developer can refer to the docs while developing. What benefits are you proposing by viewing the source code of the component?

**Comment by amaldinesh7** [comment]
@mustafapc19 _A

**Comment by mustafapc19** [comment]
@amaldinesh7 As per we discussed. I will be exploring the possibility and feasibility of not minifying the neeto-ui package, but relying on the bundling and minification process happening during production build stage.
