### ISSUE TITLE
Make `tooltipProps` work even if the `Button` is `disabled`

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#840]
https://www.loom.com/share/cfecf98b2ba84dcaac476473ec01564a

@jagannathBhat _a
This is a bug. Which means, this issue has priority over other assigned issues. If you get assigned with higher priority issues, then please make sure to let me know, so that I can reassign this issue to someone else.

cc: @ajmaln @praveen-murali-ind

**Comment by amaldinesh7** [comment]
This solution will result in wrapping all the elements with a `span` tag wherever there is a tooltip, which might cause some side effects. We need to test this thoroughly before merging. Thus currently putting on-hold. If this is some blocker in any project, please add the necessary fix in the project end.

cc: @praveen-murali-ind @karthiknmenon
