### ISSUE TITLE
Add a Kbd component

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#847]
https://www.loom.com/share/7e00c7bbb5a143f1a338061fcf71a1d6

@karthiknmenon _a Can you comment about the feasibility of adding this? Feel free to close this if it's not required.

cc: @amaldinesh7 @praveen-murali-ind

**Comment by karthiknmenon** [comment]
@yedhink Seems like a good add, however, the focus for now is to stabilise neetoUI for consistency. We will be picking this up in March.

**Comment by karthiknmenon** [comment]
@vysaghsekharbb _a Could you please share the design files for this?

**Comment by vysaghsekharbb** [comment]
@karthiknmenon Sure, I will share the design files.

**Comment by vysaghsekharbb** [comment]
@karthiknmenon @yedhink 

we have a similar design component in neetoChat. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/86587984/191734665-c0505db5-97f1-4498-92a2-d8724d5105af.png)

Figma Link
https://www.figma.com/file/9rPsUXEWN7GA3MNuwd66xC/neetoChat?node-id=9453%3A30697

**Comment by yedhink** [comment]
@vysaghsekharbb I believe that's the keyboard shortcuts listing popup you are talking about. Here I am proposing to add a component that can style item as if it's a key from the keyboard. That's also shown in the screenshot, example `⌘ \`.

Either ways the style for the `kbd` shown in the screenshot is correct.

**Comment by karthiknmenon** [comment]
@ajil-paul _a
