### ISSUE TITLE
[Syncing] form/FormSingleSelectField

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#86]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormSingleSelectField.jsx

Very confusing component. I think this is same as the default `Select` component in neeto-ui itself, but with legacy code.
This is used at many places in neeto-help. Therefore I think we need to sync this. 

But i'm wondering whether we can replace this with our neeto-ui select components.

Let me know your thoughts on what to do.
@goutham-subramanyam _a

cc: @edwinbbu

**Comment by edwinbbu** [comment]
@yedhink Yes we'll be updating `FormSingleSelectField` with `Select` component from neetoui

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
