### ISSUE TITLE
[Syncing] form/FormSingleSelect

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#87]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormSingleSelect.jsx

I feel this one too is just legacy form of our neeto-ui Select component.

But it's used at many places. Therefore I'm confused on whether to sync this or not.

Let me know your thoughts.
@goutham-subramanyam _a

cc: @edwinbbu

**Comment by goutham-subramanyam** [comment]
We don't need to port non neetoui components. All those will be removed after the revamp.
