### ISSUE TITLE
Remove dependency on peer-deps-externals-webpack-plugin

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#875]
https://github.com/bigbinary/neeto-ui/blob/4be7a3d8b1f2c00907a29b7dd363ff4fc6b10212/webpack.config.js#L1

@karthiknmenon I think we can locally maintain this class within neetoUI itself rather than maintaining it as a separate package. Seems a bit of an overkill to maintain it separately.

What are your thoughts?

This change would:
- Avoid dependency on any specific Github user to maintain the repo
- Avoid the hassles related to packaging and publishing to npm registry

**Comment by amaldinesh7** [comment]
We've stopped using this package as we moved from Webpack to Rollup for bundling, thus closing the issue.
