### ISSUE TITLE
Fix the `loading` states in Modal, Alert, and Pane.

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#877]
@praveen-murali-ind _a

Currently, we are using the following loading states

Alert

<img width="1440" alt="Screenshot 2022-02-23 at 9 27 04 AM" src="https://user-images.githubusercontent.com/48869249/155259422-91c7074a-d280-4304-9805-469421dc6f35.png">

Modal & Pane

Empty UI state

<img width="286" alt="Screenshot 2022-02-23 at 9 29 14 AM" src="https://user-images.githubusercontent.com/48869249/155259577-a6cea21c-d1cd-4793-8f96-68c3fc9008bb.png">

Do we need a loader state for these components? Ant Design and Material UI React UI libraries don’t have this prop in these components.

In my opinion, we can remove this prop unless it is needed anywhere.

@amaldinesh7 @karthiknmenon Please share your thoughts on this.

**Comment by amaldinesh7** [comment]
Removed the loading state from modal and alert in the beta-release 1.4.0-beta.0. We can keep the loading state in the pane. @praveen-murali-ind
