### ISSUE TITLE
Truncate email shown in the profile info in the SideBar

### ISSUE THREAD

**Issue by mustafapc19** [bigbinary/neeto-ui#878]
Reference [issue](https://github.com/bigbinary/neeto-auth-web/issues/1145)

Bug:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/35809690/155271309-70db1f72-2aa6-4515-8389-4a405822bd46.png">

**Comment by praveen-murali-ind** [comment]
@praveen-murali-ind _a
