### ISSUE TITLE
Fix email overflow issue in sidebar profile section

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#882]
Ref - https://github.com/bigbinary/neeto-desk-web/issues/12338

@vysakh-m _a

**Comment by vysakh-m** [comment]
@amaldinesh7 The issue seems to be fixed in https://github.com/bigbinary/neeto-ui/pull/879

**Comment by karthiknmenon** [comment]
@vysakh-m _a Please confirm and close the issue.

**Comment by vysakh-m** [comment]
@karthiknmenon Verified that the issue is fixed in the latest version
