### ISSUE TITLE
Fix inconsistency in Text Color

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#895]
@praveen-murali-ind _a

In Toastr we are using a single Text color for all variants. 
But in Tags ( Colored Outline variant ) we are following a slightly different approach.

[Toastr ](https://neetoui.netlify.app/?path=/docs/overlays-toastr--toastrs)

<img width="592" alt="Screenshot 2022-03-01 at 6 13 24 PM" src="https://user-images.githubusercontent.com/48869249/156171065-1cedd58f-1a4c-4f7f-a347-cfa9fff90504.png">

[Tag](https://neetoui.netlify.app/?path=/docs/components-tag--tag-color-story#all-variants)

<img width="740" alt="Screenshot 2022-03-01 at 10 33 28 AM" src="https://user-images.githubusercontent.com/48869249/156108214-78293769-e3f3-4577-b3a8-74f9296da9be.png">

//cc @karthiknmenon

**Comment by praveen-murali-ind** [comment]
@vysaghsekharbb _a 

Additional Tag variations are provided for backward compatibility and are being used in some applications. Could you please confirm the styles?

**Comment by vysaghsekharbb** [comment]
I'll work on revising the tag components and share the designs and documentation with you. @praveen-murali-ind

**Comment by vysaghsekharbb** [comment]
@praveen-murali-ind _a

Please find the updated components.

https://www.figma.com/file/zhdsnPzXzr264x1WUeVdmA/02-Components?node-id=104%3A17
