### ISSUE TITLE
Update Buttons Specs

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#898]
@praveen-murali-ind _a

Design Ref - [Figma Link](https://www.figma.com/file/zhdsnPzXzr264x1WUeVdmA/02-Components?node-id=104%3A18)

**Current Specs**

<img width="539" alt="Screenshot 2022-03-01 at 3 21 08 PM" src="https://user-images.githubusercontent.com/48869249/156146272-42051f98-6a1f-4b6f-8a07-7dad0e7d2b8e.png">

Button styles - `primary`, `secondary `, `text `, `link `, `danger`
Button sizes - 32px - large, 28px - default
Icon sizes - 16px, 16px
Font sizes - 16px, 14px
Icon only button sizes - 16px, 16px

//cc @vysaghsekharbb  @goutham-subramanyam @karthiknmenon

**Comment by praveen-murali-ind** [comment]
@vysaghsekharbb _a

As discussed, please update the Button design. 

- [ ] Add all Button variations (styles and sizes)
- [ ] Add hover/focus states

[Button documentation ref](http://localhost:6006/?path=/docs/components-button--all-variants)

**Comment by vysaghsekharbb** [comment]
@praveen-murali-ind @goutham-subramanyam 

please watch the bubble video
https://app.usebubbles.com/kU2FZfRBDzph9NsnQiYGYg/button-component-documentation

**Comment by vysaghsekharbb** [comment]
https://www.figma.com/file/zhdsnPzXzr264x1WUeVdmA/02-Components?node-id=104%3A18

Figma source file

**Comment by vysaghsekharbb** [comment]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@vysaghsekharbb _a Could you please update the Dropdown design in the UI kit to guide us regarding the Danger actions default and hover state styles? 

<img width="223" alt="Screenshot 2022-03-11 at 8 49 25 PM" src="https://user-images.githubusercontent.com/48869249/157898099-08dd742a-627a-4a3d-ba20-ace84806b7ce.png">

<img width="228" alt="Screenshot 2022-03-11 at 8 49 18 PM" src="https://user-images.githubusercontent.com/48869249/157898138-50107aff-d0ce-4027-86e4-f5d300a1e3c2.png">
