### ISSUE TITLE
[Syncing] form/FormRowLabel

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#90]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormRowLabel.jsx

This is definitely used at several places in neeto-help. I feel we need to sync this. But not sure whether it's an overkill to have this a s a separate component for this on it's own.

I wonder if the `required` attribute in our components can replace this one. Was it an intentions choice to not pass this as render props, but rather keep this a separate component of its own?

Let me know your thoughts.

@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
