### ISSUE TITLE
Remove tailwind dependency from neetoUI components

### ISSUE THREAD

**Issue by goutham-subramanyam** [bigbinary/neeto-ui#905]
neetoUI should be used only for Storybook documentation. The components should all have their own custom classes.

#### Components

- [x] ActionDropdown
- [x] Button
- [x] Callout
- [x] Checkbox
- [x] ColorPicker
- [x] Dropdown
- [x] Email Input
- [x] Input
- [x] Label
- [x] PageLoader
- [x] Pagination
- [x] Radio
- [x] Spinner
- [x] Switch
- [x] Tab
- [x] Tag
- [x] Textarea
- [x] Accordion
- [x] Avatar
- [x] Date and Time
- [x] Select
- [x] Table

#### Overlays

- [x] Alert
- [x] Modal
- [x] Pane
- [x] Toastr
- [x] Tooltip

#### Layouts

- [x] AppSwitcher
- [x] Container
- [x] Header
- [x] Scrollable
- [x] SubHeader

**Comment by praveen-murali-ind** [comment]
@praveen-murali-ind _a

**Comment by goutham-subramanyam** [comment]
Closed by #904
