### ISSUE TITLE
[Syncing] form/FormNumericInput

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#92]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormNumericInput.jsx

Unused component. No sync required.

Please close this issue if you feel the same way.
@goutham-subramanyam _a

**Comment by edwinbbu** [comment]
@yedhink _a Since the component is unused, create a PR for removing the component in NeetoHelp.

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
