### ISSUE TITLE
Add unit tests to components

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#925]
This issue is to track the coverage of the unit tests.

Components:
- [x] Add tests for Button
- [x] #920 
- [x] #915 
- [x] #929
- [x] #930
- [x] #931
- [x] #932
- [x] #933
- [x] #934
- [x] #935
- [x] #936
- [x] #937
- [x] #938
- [x] #939
- [x] #944
- [x] #943
- [x] #967
- [x] #968
- [x] #985
- [x] #978
- [x] #986
- [x] #947
- [x] #946
- [x] #975
- [x] #994
- [x] #997
- [x] #945
- [x] #966
- [x] #1003
- [x] #993

Layouts:
- [x] #1026
- [x] #1027
- [x] #1028
- [x] #1029
- [x] #1005
- [x] #1030
- [x] #1017

Formik:
- [x] #1102
- [x] #1103
- [x] #1088
- [x] #1087
- [x] #1053
- [x] #1086
- [x] #1070
- [x] #1069
- [x] #1068

epic _t

@ajmaln _a

cc: @amaldinesh7 @karthiknmenon

**Comment by neerajdotname** [comment]
Looks like all the sub issues are resolved. Can we close this issue then?
