### ISSUE TITLE
[Syncing] form/FormMultiSelectTextInput

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#93]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormMultiSelectTextInput.jsx

The multi selection feature can be invoked by passing in the `isMulti` as otherProps to our select component.

So do we need to sync this? Is the specific usage of `react-select/creatable` adding any value? This component is currently used at many places in neeto-help. I feel we could replace this component with our neetoui Select.

Let me know your thoughts.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
