### ISSUE TITLE
[Syncing] form/FormInputField

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#94]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormInputField.jsx

I feel we can replace this with our Input component. But the problem is that, this component is also composed of a `textarea` tag which [gets rendered based on type](https://github.com/bigbinary/neeto-help-web/blob/c2034ee6628313c101d0cc6f4123b94f83dfb3f4/app/javascript/Admin/Components/form/FormInputField.jsx#L146). I feel it should be split out and we need to compose them using `Input` and `TextArea` from our neeto-ui, from wherever it's invoked.

One another thing is that I wasn't able to find a place where this component is used as textarea

**The following is an example of where this component is used as input box.  The `Header` and `Search Input text` are both instances of this component. I** feel we should replace this with neetoui. But problem is, it's used at many places in neeto-help.
Let me know your thoughts.

@edwinbbu _a

cc: @goutham-subramanyam 

![image](https://user-images.githubusercontent.com/31244999/102751199-40b53800-438d-11eb-9113-47caaf90c634.png)

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
