### ISSUE TITLE
Add prefix and suffix options to EmailInput

### ISSUE THREAD

**Issue by jagannathBhat** [bigbinary/neeto-ui#948]
Let's add the option to add prefix and suffix props to `EmailInput` just like we have in the `Input` component.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/29631578/157592463-c4276261-954c-4323-9517-a2ae38f0fbe5.png">

**Comment by karthiknmenon** [comment]
@mohit-s96 _a
