### ISSUE TITLE
[Syncing] form/FormInputError

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#95]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormInputError.jsx

This is already handled in our Input component. Therefore I think we can replace this.

Let me know your thoughts.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
