### ISSUE TITLE
[Syncing] form/FormInputDescription

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#96]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormInputDescription.jsx

No sync required. Can be handled in our Input component itself.

Let me know your thoughts.
@goutham-subramanyam _a

cc: @edwinbbu

**Comment by yedhink** [comment]
On second look, it looks unused.

Will migrate.
@yedhink _a

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
