### ISSUE TITLE
[Syncing] form/FormInputCharactersCount

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#97]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormInputCharactersCount.jsx

Already handled in neeto-ui Input component. No sync required in my opinion.

Let me know your thoughts.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by yedhink** [comment]
On second look, it looks unused. 

Will migrate.
@yedhink _a

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
