### ISSUE TITLE
Create public UI Kit for neeto

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#971]
@praveen-murali-ind _a

Ref - [Ant Design System](https://www.figma.com/community/file/822070817360747147)

We should create a solid design reference for the neetoUI kit. Currently, some components are scattered in different files in Figma and are a bit difficult to track. Also, we need to remove the draft design versions from neetoUI kit to get rid of unwanted iterations and confusion.

Plan

1. We will be adding a ref to the UI kit design file in [Storybook documentation](https://neetoui.netlify.app/?path=/story/introduction--page). 

2. Also for each component, we will be adding the respective design references along with the existing documentation.

**This is to ensure the utmost attention to detail, everything is well organized/documented and easy to use.**

### Design Links

- [x] UI Kit link - ?

Foundation 

- [x] [Colors](https://neetoui.onrender.com/?path=/story/foundation-colors--page) - ?
- [x] [Typography](https://neetoui.onrender.com/?path=/story/foundation-typography--variants) - ?
- [x] [Iconography](https://neetoui.onrender.com/?path=/story/foundation-iconography--iconography)  - ?

Components

- [x] [Accordion](https://neetoui.onrender.com/?path=/story/components-accordion--accordion-story) - ?
- [x] [ActionDropdown](https://neetoui.onrender.com/?path=/story/components-actiondropdown--primary-dropdown) - ?
- [x] [Avatar](https://neetoui.onrender.com/?path=/story/components-avatar--all-variants) - ?
- [x] [Button](https://neetoui.onrender.com/?path=/story/components-button--all-variants) - ?
- [x] [Callout](https://neetoui.onrender.com/?path=/story/components-callout--info-callout) - ?
- [x] [Checkbox](https://neetoui.onrender.com/?path=/story/components-checkbox--checked) - ?
- [x] [ColorPicker](https://neetoui.onrender.com/?path=/story/components-colorpicker--color-picker-story) - ?
- [x] [Date and Time](https://neetoui.onrender.com/?path=/story/components-date-and-time--date-input) - ?
- [x] [Dropdown](https://neetoui.onrender.com/?path=/story/components-dropdown--primary-dropdown) - ?
- [x] [Email Input](https://neetoui.onrender.com/?path=/story/components-email-input--controlled) - ?
- [x] [Input](https://neetoui.onrender.com/?path=/story/components-input--all-variants) - ?
- [x] [Label](https://neetoui.onrender.com/?path=/story/components-label--basic) - ?
- [x] [PageLoader](https://neetoui.onrender.com/?path=/story/components-pageloader--basic-usage) - ?
- [x] [Pagination](https://neetoui.onrender.com/?path=/story/components-pagination--basic-usage) - ?
- [x] [Radio](https://neetoui.onrender.com/?path=/story/components-radio--options) - ?
- [x] [Select](https://neetoui.onrender.com/?path=/story/components-select--all-variants) - ?
- [ ] [Spinner](https://neetoui.onrender.com/?path=/story/components-spinner--basic-usage) - ?
- [x] [Switch](https://neetoui.onrender.com/?path=/story/components-switch--checked-state) - ?
- [x] [Tab](https://neetoui.onrender.com/?path=/story/components-tab--default) - ?
- [x] [Table](https://neetoui.onrender.com/?path=/story/components-table--table) - ?
- [x] [Tag](https://neetoui.onrender.com/?path=/story/components-tag--default) - ?
- [x] [Textarea](https://neetoui.onrender.com/?path=/story/components-textarea--basic-usage) - ?

Overlays 

- [ ] [Alert](https://neetoui.netlify.app/?path=/story/overlays-alert--default) - ?
- [x] [Modal](https://neetoui.netlify.app/?path=/story/overlays-modal--default) - ?
- [ ] [Pane](https://neetoui.netlify.app/?path=/story/overlays-pane--panes) - ?
- [x] [Toastr](https://neetoui.netlify.app/?path=/story/overlays-toastr--toastrs) - ?
- [ ] [Tooltip](https://neetoui.netlify.app/?path=/story/overlays-tooltip--auto-hiding-tooltip) - ?

Layouts

- [ ] [AppSwitcher](https://neetoui.netlify.app/?path=/story/layouts-appswitcher--app-switcher-story) - ?
- [ ] [Page](https://neetoui.netlify.app/?path=/story/layouts-page--page) - ?
- [ ] [Container](https://neetoui.netlify.app/?path=/story/layouts-container--container-story) - ?
- [ ] [Header](https://neetoui.netlify.app/?path=/story/layouts-header--basic-usage) - ?
- [ ] [MenuBar](https://neetoui.netlify.app/?path=/story/layouts-menubar--menu-bar-story) - ?
- [ ] [Sidebar](https://neetoui.netlify.app/?path=/story/layouts-sidebar--sidebar-collapsed) - ?
- [ ] [SubHeader](https://neetoui.netlify.app/?path=/story/layouts-subheader--basic-usage) - ?

//cc @karthiknmenon @goutham-subramanyam @amaldinesh7

**Comment by praveen-murali-ind** [comment]
@vysaghsekharbb _a As discussed, please work on the UI kit documentation, and map the design links to the respective checklist item. You can view the existing storybook documentation by clicking each item.

**Comment by praveen-murali-ind** [comment]
@KiranRaj7 _a

**Comment by amaldinesh7** [comment]
@KiranRaj7 could you please update the progress of this issue? You can add links to the design completed ones to the list above.

**Comment by KiranRaj7** [comment]
Here is the link for the completed components.
https://www.figma.com/file/zhdsnPzXzr264x1WUeVdmA/02-Components?node-id=104%3A11.

Note: Consider the name mismatch.
ActionDropdown -> Context Menu
Label -> Badge
Input -> Text Field

**Comment by praveen-murali-ind** [comment]
@vysaghsekharbb _a Could you please verify and close this issue.
