### ISSUE TITLE
Selecting `icon` prop in Storybook yields `Minified React error`

### ISSUE THREAD

**Issue by vysakh-m** [bigbinary/neeto-ui#973]
This behaviour is present in `Button`, `Dropdown` & `Tag` components.

<img width="1440" alt="Screenshot 2022-03-14 at 2 30 31 PM" src="https://user-images.githubusercontent.com/29486171/158138893-e102df25-3794-4b9f-a85b-382c2a412b0c.png">
<img width="1440" alt="Screenshot 2022-03-14 at 4 19 56 PM" src="https://user-images.githubusercontent.com/29486171/158157683-5b3c9d67-d232-44df-8195-14e87f209de4.png">
<img width="1439" alt="Screenshot 2022-03-14 at 2 30 11 PM" src="https://user-images.githubusercontent.com/29486171/158138862-ff5fa132-a4e7-41f2-b1b4-e86faedf3dad.png">

@amaldinesh7 _a

**Comment by amaldinesh7** [comment]
@ajmaln _a Can you please check what we can do to avoid this error?
