### ISSUE TITLE
[Syncing] form/FormInputAutoComplete

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#98]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormInputAutoComplete.jsx

Unused. Can be migrated.

Will raise in neeto-help.

@yedhink _a

cc: @edwinbbu

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
