### ISSUE TITLE
Add what's new/ changelog in storybook

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#980]
Please refer https://storybook.js.org/addons/storybook-addon-whats-new/

@Nuzair46 _a

**Comment by amaldinesh7** [comment]
Having a changelog for each component is not scalable and not useful I feel. Let's implement it in the other way. Please update the PR with a single changelog option for the whole components.

@Nuzair46 _a

**Comment by Nuzair46** [comment]
@amaldinesh7 _a, Please checkout the latest deployment https://deploy-preview-983--neetoui.netlify.app/ to see how the global changelog works.
