### ISSUE TITLE
Add custom props to Sidebar link

### ISSUE THREAD

**Issue by Prasannams97** [bigbinary/neeto-ui#987]
- Need data-cy for all Sidebar links.

![SideBarLinks](https://user-images.githubusercontent.com/75472228/158539929-399ed0f2-9120-4c6c-a8d2-0936413f1727.png)

**Comment by Prasannams97** [comment]
@amaldinesh7 _a

**Comment by amaldinesh7** [comment]
you can add data-cy property in the array that's being passed to the `navLinks` props. @Prasannams97

**Comment by Prasannams97** [comment]
> you can add data-cy property in the array that's being passed to the `navLinks` props. @Prasannams97

Got it, thanks.
