### ISSUE TITLE
Add custom props to Menubar link

### ISSUE THREAD

**Issue by Prasannams97** [bigbinary/neeto-ui#988]
- Need data-cy for all Menubar links.

![MenubarLinks](https://user-images.githubusercontent.com/75472228/158540558-34957033-b686-428e-8f3c-d44d1d914d2b.png)

**Comment by Prasannams97** [comment]
@amaldinesh7 _a

**Comment by amaldinesh7** [comment]
There is provision for providing data-cy into Menubar Item.

```
<MenuBar.Item
	  label="Widget Icon"
	  description="Position, Icon and Label"
	  data-cy="widget-icon-data-cy
/>
```

Please try like this.

@Prasannams97

**Comment by Prasannams97** [comment]
> There is provision for providing data-cy into Menubar Item.
> 
> ```
> <MenuBar.Item
> 	  label="Widget Icon"
> 	  description="Position, Icon and Label"
> 	  data-cy="widget-icon-data-cy
> />
> ```
> 
> Please try like this.
> 
> @Prasannams97

Got it, thanks.
