### ISSUE TITLE
[Syncing] form/FormInput

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#99]
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormInput.jsx

This one looks very similar to the `FormInputField` component. Also we can't keep this component since the dependent `FormInputError` etc are being removed/migrated.

Let me know how we should handle this component.

@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment]
https://github.com/bigbinary/neeto-ui/issues/87#issuecomment-748905496
