### ISSUE TITLE
Repeating dates in DatePicker calendar

### ISSUE THREAD

**Issue by riavarghese** [bigbinary/neeto-ui#992]
Saturday dates are being repeated in the leftmost column.

![image](https://user-images.githubusercontent.com/48003301/158753822-4c3bbcaf-6436-419d-9adb-35512939cee8.png)

**Comment by amaldinesh7** [comment]
can you please post the code snippet here?

<img width="508" alt="Screenshot 2022-03-17 at 12 47 59 PM" src="https://user-images.githubusercontent.com/33386004/158756760-02586879-201b-44e3-a1e9-278989f2341c.png">

In the storybook, I am not able to see this.

@riavarghese

**Comment by riavarghese** [comment]
@amaldinesh7 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/48003301/158759253-09341872-03ea-458a-87c5-28e151b58072.png">

**Comment by amaldinesh7** [comment]
It is not an issue @riavarghese. It's just showing the week's count. If you go back to the month of Jan, you will find the first week's number appears to be 1.
